#!/bin/bash

set -x
set -e
set -u

SPHINX="$1/scroom/doc/_build/html"
COMMIT_USER="Documentation Builder"
COMMIT_EMAIL="project@mandryn.org"
CHANGESET=$(git rev-parse --verify HEAD)
BRANCH="${GITHUB_REF#refs/heads/}"

cd ../doc

if [ -e "${BRANCH}" ]
then
  git rm -rf "${BRANCH}"
fi
mkdir -p "${BRANCH}"
pushd "${BRANCH}"
mv "${SPHINX}"/* .
touch .documentation_root
git add .

# Regenerate master index
popd
cat > index.html <<EOF
<html>
<head>
<title>Scroom doxygen documentation</title>
<link href="$(find master -name doxygen.css)" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
<tbody>
<tr style="height: 56px;">
<td style="padding-left: 0.5em;">
<div id="projectname">Scroom doxygen documentation</div>
</td>
</tr>
</tbody>
</table>
</div>
<table>
$(for f in $(find * -mindepth 1 -maxdepth 1 -name index.html)
  do
    if [ -f "$(dirname "$f")/_static/doxygen/index.html" ]
    then
      echo "<tr>"
      echo "<td><h1><li><a href=\"$f\">$(dirname $f)</a></li></h1></td>"
      echo "<td><h2><a href=\"$(dirname "$f")/_static/doxygen\">Doxygen</a></h2></td>"
      echo "</tr>"
    else
      echo "<tr>"
      echo "<td><h1><li>$(dirname $f)</li></h1></td>"
      echo "<td><h2><a href=\"$f\">Doxygen</a></h2></td>"
      echo "</tr>"
    fi
  done)
</table>
</body>
</html>
EOF
git add index.html

# Commit and push
git config user.name "${COMMIT_USER}"
git config user.email "${COMMIT_EMAIL}"
git commit -m "Automated documentation build for branch ${BRANCH}, changeset ${CHANGESET}."
git push origin gh-pages
