Scroom: libs/threadpool/test/async-deleter-tests.cc File Reference
async-deleter-tests.cc File Reference
#include <scroom/async-deleter.hh>
#include <iostream>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/thread.hpp>
#include <scroom/function-additor.hh>
#include <scroom/semaphore.hh>
#include "helpers.hh"
Classes
class A
Functions
static const millisec short_timeout (250)
static const millisec long_timeout (2000)
BOOST_AUTO_TEST_CASE (deleter_deletes_asynchronously)
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (deleter_deletes_asynchronously)
 {
   Semaphore            barrier1;
   Semaphore            destroyed;
   boost::shared_ptr<A> a = boost::shared_ptr<A>(new A(&barrier1, &destroyed), AsyncDeleter<A>());
   BOOST_CHECK(!destroyed.P(short_timeout));
   Semaphore barrier2;
   Semaphore signal;
   CpuBound()->schedule(pass(&barrier2) + destroy(a) + clear(&signal));
   a.reset();
   barrier2.V();
   BOOST_CHECK(signal.P(long_timeout));
   BOOST_CHECK(!destroyed.P(short_timeout));
   barrier1.V();
   BOOST_CHECK(destroyed.P(long_timeout));
 }
long_timeout()
static const millisec long_timeout (2000) static
Referenced by BOOST_AUTO_TEST_CASE().
short_timeout()
static const millisec short_timeout (250) static
Referenced by BOOST_AUTO_TEST_CASE(), and anonymous_namespace{threadpoolimpl.cc}::ThreadList::wait().