Scroom: ProgressStateInterfaceStub Class Reference
ProgressStateInterfaceStub Class Reference
#include <progressstateinterfacestub.hh>
Public Types
using Ptr = boost::shared_ptr< ProgressStateInterfaceStub >
Public Types inherited from Scroom::Utils::ProgressStateInterface
enum State { IDLE, WAITING, WORKING, FINISHED }
using Ptr = boost::shared_ptr< ProgressStateInterface >
using WeakPtr = boost::weak_ptr< ProgressStateInterface >
Public Member Functions
void setProgress (State s, double d) override
Static Public Member Functions
static Ptr create ()
Public Attributes
State state {IDLE}
double progress {0.0}
Private Member Functions
ProgressStateInterfaceStub ()=default
Member Typedef Documentation
Ptr
using ProgressStateInterfaceStub::Ptr = boost::shared_ptr<ProgressStateInterfaceStub>
Constructor & Destructor Documentation
ProgressStateInterfaceStub()
ProgressStateInterfaceStub::ProgressStateInterfaceStub () private default
Referenced by create().
Member Function Documentation
create()
ProgressStateInterfaceStub::Ptr ProgressStateInterfaceStub::create () static
 { return Ptr(new ProgressStateInterfaceStub()); }
Referenced by BOOST_AUTO_TEST_CASE(), and ProgressInterfaceMultiplexer_Fixture::ProgressInterfaceMultiplexer_Fixture().
setProgress()
void ProgressStateInterfaceStub::setProgress (State s, double d) override virtual
Implements Scroom::Utils::ProgressStateInterface.
 {
   state    = s;
   progress = d;
 }
Member Data Documentation
progress
double ProgressStateInterfaceStub::progress {0.0}
Referenced by setProgress().
state
State ProgressStateInterfaceStub::state {IDLE}
Referenced by setProgress().
The documentation for this class was generated from the following files:
libs/util/test/progressstateinterfacestub.hh
libs/util/test/progressstateinterfacestub.cc