Scroom: TransformationData Class Reference
TransformationData Class Reference
#include <transformpresentation.hh>
Public Types
using Ptr = boost::shared_ptr< TransformationData >
Public Member Functions
void setAspectRatio (double x, double y)
void setAspectRatio (Scroom::Utils::Point< double > aspectRatio_)
Scroom::Utils::Point< double > getAspectRatio () const
Static Public Member Functions
static Ptr create (Scroom::Utils::Point< double > aspectRatio_)
static Ptr create ()
Private Member Functions
TransformationData ()
TransformationData (Scroom::Utils::Point< double > aspectRatio_)
Private Attributes
Scroom::Utils::Point< double > aspectRatio
Member Typedef Documentation
Ptr
using TransformationData::Ptr = boost::shared_ptr<TransformationData>
Constructor & Destructor Documentation
TransformationData() [1/2]
TransformationData::TransformationData () private
   : aspectRatio(1, 1)
 {}
Referenced by create().
TransformationData() [2/2]
TransformationData::TransformationData (Scroom::Utils::Point< double > aspectRatio_) explicit private
   : aspectRatio(aspectRatio_)
 {}
Member Function Documentation
create() [1/2]
TransformationData::Ptr TransformationData::create () static
 { return Ptr(new TransformationData()); }
Referenced by anonymous_namespace{tiledbitmappresentation.cc}::OpenTiledBitmapAsPresentation::open(), and TEST().
create() [2/2]
TransformationData::Ptr TransformationData::create (Scroom::Utils::Point< double > aspectRatio_) static
 {
   return Ptr(new TransformationData(aspectRatio_));
 }
getAspectRatio()
Scroom::Utils::Point< double > TransformationData::getAspectRatio () const
 { return aspectRatio; }
setAspectRatio() [1/2]
void TransformationData::setAspectRatio (double x, double y)
 { aspectRatio = Scroom::Utils::make_point(x, y); }
setAspectRatio() [2/2]
void TransformationData::setAspectRatio (Scroom::Utils::Point< double > aspectRatio_)
 { aspectRatio = aspectRatio_; }
Member Data Documentation
aspectRatio
Scroom::Utils::Point<double> TransformationData::aspectRatio private
Referenced by getAspectRatio(), and setAspectRatio().
The documentation for this class was generated from the following files:
inc/scroom/transformpresentation.hh
libs/scroom/src/transformpresentation.cc