Scroom: Scroom::ColormapImpl::ColormapProvider Class Reference
Scroom::ColormapImpl::ColormapProvider Class Reference
#include <colormapprovider.hh>
Public Types
using Ptr = boost::shared_ptr< ColormapProvider >
Public Types inherited from Viewable
using Ptr = boost::shared_ptr< Viewable >
using WeakPtr = boost::weak_ptr< Viewable >
Public Member Functions
~ColormapProvider () override
ColormapProvider (const ColormapProvider &)=delete
ColormapProvider (ColormapProvider &&)=delete
ColormapProvider operator= (const ColormapProvider &)=delete
ColormapProvider operator= (ColormapProvider &&)=delete
void open (ViewInterface::WeakPtr vi) override
void close (ViewInterface::WeakPtr vi) override
void on_colormap_selected (GtkTreeView *tv)
Static Public Member Functions
static ColormapProvider::Ptr create (PresentationInterface::Ptr p)
Private Member Functions
ColormapProvider (Colormappable::Ptr c)
Private Attributes
Colormappable::WeakPtr colormappable
std::map< ViewInterface::WeakPtr, GtkTreeView * > views
GtkListStore * colormaps
Scroom::Utils::Stuff registration
Detailed Description
Provide the colormap widget to the Viewable.
When the user selects one of the colormaps, they will be set.
Member Typedef Documentation
Ptr
using Scroom::ColormapImpl::ColormapProvider::Ptr = boost::shared_ptr<ColormapProvider>
Constructor & Destructor Documentation
ColormapProvider() [1/3]
ColormapProvider::ColormapProvider (Colormappable::Ptr c) private
Constructor
       : colormappable(c)
       , colormaps(nullptr)
     {
       unsigned int                  numColors = c->getNumberOfColors();
       std::list<Colormap::ConstPtr> maps      = Colormaps::getInstance().getColormaps();
       colormaps = gtk_list_store_new(N_COLUMNS, G_TYPE_STRING, G_TYPE_POINTER);
       {
         // Add the original colormap, if any
         Colormap::Ptr orig = c->getOriginalColormap();
         if(orig)
         {
           auto*       cc = new Colormap::ConstPtr(orig);
           GtkTreeIter iter;
           gtk_list_store_append(colormaps, &iter);
           gtk_list_store_set(colormaps, &iter, COLUMN_NAME, (*cc)->name.c_str(), COLUMN_POINTER, cc, -1);
         }
       }
       while(!maps.empty())
       {
         if(maps.front()->colors.size() >= numColors)
         {
           auto* cc = new Colormap::ConstPtr(maps.front());
           GtkTreeIter iter;
           gtk_list_store_append(colormaps, &iter);
           gtk_list_store_set(colormaps, &iter, COLUMN_NAME, (*cc)->name.c_str(), COLUMN_POINTER, cc, -1);
         }
         maps.pop_front();
       }
     }
Referenced by create().
~ColormapProvider()
ColormapProvider::~ColormapProvider () override
Destructor
     {
       // Clear out all the smart pointers
       printf("ColormapProvider: Destructing...\n");
       if(colormaps)
       {
         GtkTreeIter iter;
         while(gtk_tree_model_get_iter_first(GTK_TREE_MODEL(colormaps), &iter))
         {
           gpointer* pointer = nullptr;
           gtk_tree_model_get(GTK_TREE_MODEL(colormaps), &iter, COLUMN_POINTER, &pointer, -1);
           auto* colormap = reinterpret_cast<Colormap::Ptr*>(pointer);
           delete colormap;
           gtk_list_store_remove(colormaps, &iter);
         }
         g_object_unref(colormaps);
       }
       colormaps = nullptr;
     }
ColormapProvider() [2/3]
Scroom::ColormapImpl::ColormapProvider::ColormapProvider (const ColormapProvider &) delete
ColormapProvider() [3/3]
Scroom::ColormapImpl::ColormapProvider::ColormapProvider (ColormapProvider &&) delete
Member Function Documentation
close()
void ColormapProvider::close (ViewInterface::WeakPtr vi) override virtual
An existing view was closed
Implements Viewable.
     {
       printf("ColormapProvider: Removing a view.\n");
       views.erase(vi);
       if(views.empty())
       {
         printf("ColormapProvider: Last view has gone.\n");
       }
     }
create()
ColormapProvider::Ptr ColormapProvider::create (PresentationInterface::Ptr p) static
Constructor
     {
       Colormappable::Ptr    c = boost::dynamic_pointer_cast<Colormappable, PresentationInterface>(p);
       ColormapProvider::Ptr result;
       if(c)
       {
         result = ColormapProvider::Ptr(new ColormapProvider(c));
         Scroom::Utils::Stuff r = p->registerStrongObserver(result);
         result->registration   = r;
       }
       else
       {
         printf("PANIC: Presentation doesn't implement Colormappable\n");
       }
       return result;
     }
Referenced by Scroom::ColormapImpl::ColormapPlugin::presentationAdded().
on_colormap_selected()
void ColormapProvider::on_colormap_selected (GtkTreeView * tv)
The user selected a colormap
     {
       Colormappable::Ptr c = colormappable.lock();
       if(c)
       {
         GtkTreeSelection* ts = gtk_tree_view_get_selection(tv);
         GtkTreeIter       iter;
         GtkTreeModel*     model    = nullptr;
         bool              selected = gtk_tree_selection_get_selected(ts, &model, &iter);
         if(selected)
         {
           if(gtk_list_store_iter_is_valid(colormaps, &iter))
           {
             gpointer* pointer = nullptr;
             gtk_tree_model_get(GTK_TREE_MODEL(colormaps), &iter, COLUMN_POINTER, &pointer, -1);
             Colormap::Ptr& colormap = *reinterpret_cast<Colormap::Ptr*>(pointer);
             c->setColormap(colormap);
           }
         }
       }
       else
       {
         printf("PANIC: Colormappable Presentation is gone??\n");
       }
     }
Referenced by anonymous_namespace{colormapprovider.cc}::on_colormap_selected(), and open().
open()
void ColormapProvider::open (ViewInterface::WeakPtr vi) override virtual
A new view was opened
Implements Viewable.
     {
       ViewInterface::Ptr vil(vi);
       printf("ColormapProvider: Adding a view.\n");
       GtkTreeView*     tv  = GTK_TREE_VIEW(gtk_tree_view_new_with_model(GTK_TREE_MODEL(colormaps)));
       GtkCellRenderer* txt = GTK_CELL_RENDERER(gtk_cell_renderer_text_new());
       gtk_tree_view_insert_column_with_attributes(tv, -1, "Name", txt, "text", COLUMN_NAME, NULL);
       g_signal_connect(static_cast<gpointer>(tv), "cursor_changed", G_CALLBACK(::on_colormap_selected), this);
       views[vi] = tv;
       vil->addSideWidget("Colormap", GTK_WIDGET(tv));
     }
operator=() [1/2]
ColormapProvider Scroom::ColormapImpl::ColormapProvider::operator= (ColormapProvider &&) delete
operator=() [2/2]
ColormapProvider Scroom::ColormapImpl::ColormapProvider::operator= (const ColormapProvider &) delete
Member Data Documentation
colormappable
Colormappable::WeakPtr Scroom::ColormapImpl::ColormapProvider::colormappable private
The Colormappable interface of the presentation to which we're associated
Referenced by on_colormap_selected().
colormaps
GtkListStore* Scroom::ColormapImpl::ColormapProvider::colormaps private
The colormaps we're offering to our views
Referenced by ColormapProvider(), on_colormap_selected(), open(), and ~ColormapProvider().
registration
Scroom::Utils::Stuff Scroom::ColormapImpl::ColormapProvider::registration private
Our registration with the Colormappable
views
std::map<ViewInterface::WeakPtr, GtkTreeView*> Scroom::ColormapImpl::ColormapProvider::views private
The views to which we're associated
Referenced by close(), and open().
The documentation for this class was generated from the following files:
plugins/colormap/colormapprovider.hh
plugins/colormap/colormapprovider.cc