Scroom: Scroom::Bookkeeping::Detail::TokenImpl Class Reference
Scroom::Bookkeeping::Detail::TokenImpl Class Reference
#include <bookkeepingimpl.hh>
Public Types
using Ptr = boost::shared_ptr< TokenImpl >
Public Member Functions
void add (const Stuff &s)
void add (const StuffList l_)
void merge (StuffList &l_)
void merge (Ptr &rhs)
Static Public Member Functions
static Scroom::Bookkeeping::Token create ()
Protected Member Functions
TokenImpl ()=default
Private Attributes
StuffList l
Member Typedef Documentation
Ptr
using Scroom::Bookkeeping::Detail::TokenImpl::Ptr = boost::shared_ptr<TokenImpl>
Constructor & Destructor Documentation
TokenImpl()
Scroom::Bookkeeping::Detail::TokenImpl::TokenImpl () protected default
Member Function Documentation
add() [1/2]
void Scroom::Bookkeeping::Detail::TokenImpl::add (const Stuff & s) inline
 { l.push_back(s); }
add() [2/2]
void Scroom::Bookkeeping::Detail::TokenImpl::add (const StuffList l_) inline
 { l.insert(l.end(), l_.begin(), l_.end()); }
create()
static Scroom::Bookkeeping::Token Scroom::Bookkeeping::Detail::TokenImpl::create () inline static
 { return Scroom::Bookkeeping::Token(Ptr(new TokenImpl)); }
Referenced by Scroom::Bookkeeping::MapBase< ObserverWeak, typename Registration::Ptr >::reReserve(), and Scroom::Bookkeeping::MapBase< ObserverWeak, typename Registration::Ptr >::reserve().
merge() [1/2]
void Scroom::Bookkeeping::Detail::TokenImpl::merge (Ptr & rhs) inline
 { merge(rhs->l); }
Referenced by merge().
merge() [2/2]
void Scroom::Bookkeeping::Detail::TokenImpl::merge (StuffList & l_) inline
 { l.splice(l.end(), l_); }
Member Data Documentation
l
StuffList Scroom::Bookkeeping::Detail::TokenImpl::l private
Referenced by add(), and merge().
The documentation for this class was generated from the following file:
inc/scroom/impl/bookkeepingimpl.hh