Scroom: Scroom::ColormapImpl::Colormaps Class Reference
Scroom::ColormapImpl::Colormaps Class Reference
#include <colormaps.hh>
Public Member Functions
std::list< Colormap::ConstPtr > getColormaps ()
Static Public Member Functions
static Colormaps & getInstance ()
static char * getColormapDirPath ()
static Colormap::Ptr load (const char *name)
Private Member Functions
Colormaps ()
Private Attributes
std::list< Colormap::ConstPtr > colormaps
Detailed Description
Manage the list of colormap files.
Upon request, load the selected file, producing a Colormap object.
This is a singleton object.
Constructor & Destructor Documentation
Colormaps()
Scroom::ColormapImpl::Colormaps::Colormaps () private
Constructor
     {
       char* colormapDirPath = getColormapDirPath();
       DIR*  colormapDir     = opendir(colormapDirPath);
       if(colormapDir)
       {
         for(struct dirent* d = readdir(colormapDir); d; d = readdir(colormapDir))
         {
           // At this point, we're not sure if d is a regular file or a
           // directory or whatever. However, we can safely assume that in
           // all bad cases, the load() will fail :-)
           char* name = d->d_name;
           int   len  = strlen(name);
           if(!strcmp(name + len - strlen(COLORMAPEXT), COLORMAPEXT))
           {
             Colormap::Ptr c = load(name);
             if(c)
             {
               colormaps.emplace_back(c);
             }
           }
         }
         closedir(colormapDir);
       }
       else
       {
         printf("Failed to open dir %s: (%d, %s)\n", colormapDirPath, errno, strerror(errno));
       }
       g_free(colormapDirPath);
     }
Member Function Documentation
getColormapDirPath()
char * Scroom::ColormapImpl::Colormaps::getColormapDirPath () static
Get the path where the colormap files are located
     {
 #ifdef _WIN32
       // We want to keep everything portable on windows so we look for the colormaps folder in the same directory as the .exe
       char buffer[2048];
       GetModuleFileName(NULL, buffer, 2047);
       std::string modulePath(buffer);
       auto        pos = modulePath.rfind("\\");
       return g_build_filename(modulePath.substr(0, pos).c_str(), "\\", COLORMAPDIR, NULL);
 #else
       const char* homedir = g_getenv("HOME");
       if(!homedir)
       {
         homedir = g_get_home_dir();
       }
       return g_build_filename(homedir, SCROOMDIR, COLORMAPDIR, NULL);
 #endif
     }
Referenced by Colormaps(), and load().
getColormaps()
std::list< Colormap::ConstPtr > Scroom::ColormapImpl::Colormaps::getColormaps ()
Get a copy of the list of Colormap objects.
 { return colormaps; }
Referenced by Scroom::ColormapImpl::ColormapProvider::ColormapProvider().
getInstance()
Colormaps & Scroom::ColormapImpl::Colormaps::getInstance () static
Get a reference to the instance
     {
       static Colormaps instance;
       return instance;
     }
Referenced by Scroom::ColormapImpl::ColormapProvider::ColormapProvider().
load()
Colormap::Ptr Scroom::ColormapImpl::Colormaps::load (const char * name) static
Load a colormap by name
     {
       Colormap::Ptr colormap;
       char* fullName = g_build_filename(getColormapDirPath(), name, NULL);
       FILE* f        = fopen(fullName, "r");
       if(f)
       {
         try
         {
           char buffer[BUFFERSIZE];
           // Read header
           char* result = fgets(buffer, BUFFERSIZE, f);
           if(!result)
           {
             throw std::exception();
           }
           if(0 != strncmp(buffer, PAL_HEADER, strlen(PAL_HEADER)))
           {
             throw std::exception();
           }
           // Read version
           result = fgets(buffer, BUFFERSIZE, f);
           if(!result)
           {
             throw std::exception();
           }
           if(0 != strncmp(buffer, PAL_VERSION, strlen(PAL_VERSION)))
           {
             throw std::exception();
           }
           // Read ColorCount
           result = fgets(buffer, BUFFERSIZE, f);
           if(!result)
           {
             throw std::exception();
           }
           unsigned int count = atoi(result);
           if(count == 0)
           {
             throw std::exception();
           }
           colormap                   = Colormap::create();
           colormap->name             = name;
           std::vector<Color>& colors = colormap->colors;
           int                 red    = 0;
           int                 green  = 0;
           int                 blue   = 0;
           while(colors.size() < count && fgets(buffer, BUFFERSIZE, f) && 3 == sscanf(buffer, "%d %d %d", &red, &green, &blue))
           {
             colors.emplace_back(red / 255.0, green / 255.0, blue / 255.0);
           }
           if(colors.size() != count)
           {
             throw std::exception();
           }
         }
         catch(std::exception& e)
         {
           printf("ERROR: Couldn't parse file\n");
           colormap.reset();
         }
         fclose(f);
       }
       g_free(fullName);
       return colormap;
     }
Referenced by Colormaps().
Member Data Documentation
colormaps
std::list<Colormap::ConstPtr> Scroom::ColormapImpl::Colormaps::colormaps private
Referenced by Colormaps(), and getColormaps().
The documentation for this class was generated from the following files:
plugins/colormap/colormaps.hh
plugins/colormap/colormaps.cc