Scroom: DummyColormapProvider Class Reference
DummyColormapProvider Class Reference
#include <test-helpers.hh>
Public Types
using Ptr = boost::shared_ptr< DummyColormapProvider >
Public Types inherited from ColormapProvider
using Ptr = boost::shared_ptr< ColormapProvider >
Public Member Functions
Colormap::Ptr getColormap () override
Static Public Member Functions
static Ptr create (Colormap::Ptr colormap)
Private Member Functions
DummyColormapProvider (Colormap::Ptr colormap)
Private Attributes
Colormap::Ptr colormap
Member Typedef Documentation
Ptr
using DummyColormapProvider::Ptr = boost::shared_ptr<DummyColormapProvider>
Constructor & Destructor Documentation
DummyColormapProvider()
DummyColormapProvider::DummyColormapProvider (Colormap::Ptr colormap) private
   : colormap(colormap_)
 {}
Referenced by create().
Member Function Documentation
create()
DummyColormapProvider::Ptr DummyColormapProvider::create (Colormap::Ptr colormap) static
 {
   return Ptr(new DummyColormapProvider(colormap));
 }
Referenced by setupTest1bpp(), setupTest2bpp(), setupTest4bpp(), setupTest8bpp(), and setupTest8bppColormapped().
getColormap()
Colormap::Ptr DummyColormapProvider::getColormap () override virtual
Implements ColormapProvider.
 { return colormap; }
Member Data Documentation
colormap
Colormap::Ptr DummyColormapProvider::colormap private
Referenced by create(), and getColormap().
The documentation for this class was generated from the following files:
libs/tiled-bitmap/tools/test-helpers.hh
libs/tiled-bitmap/tools/test-helpers.cc