Scroom: DummyView Class Reference
DummyView Class Reference
Public Types
using Ptr = boost::shared_ptr< DummyView >
Public Types inherited from ViewInterface
using Ptr = boost::shared_ptr< ViewInterface >
using WeakPtr = boost::weak_ptr< ViewInterface >
Public Member Functions
DummyView (PresentationInterface::Ptr presentation_)
void invalidate () override
ProgressInterface::Ptr getProgressInterface () override
void addSideWidget (std::string, GtkWidget *) override
void removeSideWidget (GtkWidget *) override
void addToToolbar (GtkToolItem *) override
void removeFromToolbar (GtkToolItem *) override
void registerSelectionListener (SelectionListener::Ptr) override
void registerPostRenderer (PostRenderer::Ptr) override
void setStatusMessage (const std::string &msg) override
PresentationInterface::Ptr getCurrentPresentation () override
void addToolButton (GtkToggleButton *, ToolStateListener::Ptr) override
std::string nextStatusMessage ()
Static Public Member Functions
static Ptr createWithPresentation ()
static Ptr createWithoutPresentation ()
static Ptr create (PresentationInterface::Ptr presentation_)
Public Attributes
int reg_sel = 0
int reg_post = 0
int tool_btn = 0
PresentationInterface::Ptr presentation
boost::mutex mut
boost::condition_variable cond
std::list< std::string > statusMessages
Member Typedef Documentation
Ptr
using DummyView::Ptr = boost::shared_ptr<DummyView>
Constructor & Destructor Documentation
DummyView()
DummyView::DummyView (PresentationInterface::Ptr presentation_) inline explicit
     : presentation(std::move(presentation_))
   {}
Referenced by create().
Member Function Documentation
addSideWidget()
void DummyView::addSideWidget (std::string title, GtkWidget * w) inline override virtual
Request that the given widget be added to the sidebar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 {}
addToolButton()
void DummyView::addToolButton (GtkToggleButton * , ToolStateListener::Ptr) inline override virtual
Adds a new tool button to the toolbar. The given ToolStateListener will be informed when the tool is turned on or off. Only one tool will be active at the same time.
See also
ToolStateListener
Implements ViewInterface.
 { tool_btn++; }
addToToolbar()
void DummyView::addToToolbar (GtkToolItem * ti) inline override virtual
Request that the given tool item be added to the toolbar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 {}
create()
static Ptr DummyView::create (PresentationInterface::Ptr presentation_) inline static
 { return Ptr(new DummyView(std::move(presentation_))); }
Referenced by createWithoutPresentation(), and createWithPresentation().
createWithoutPresentation()
static Ptr DummyView::createWithoutPresentation () inline static
 { return create(nullptr); }
Referenced by BOOST_AUTO_TEST_CASE().
createWithPresentation()
static Ptr DummyView::createWithPresentation () inline static
 { return create(DummyPresentation::create()); }
Referenced by BOOST_AUTO_TEST_CASE().
getCurrentPresentation()
PresentationInterface::Ptr DummyView::getCurrentPresentation () inline override virtual
Returns a shared pointer to the current presentation.
See also
PresentationInterface
Implements ViewInterface.
 { return presentation; }
getProgressInterface()
ProgressInterface::Ptr DummyView::getProgressInterface () inline override virtual
Return a pointer to the progess interface associated with the View
Note
The progress bar should only be manipulated from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 { return nullptr; }
invalidate()
void DummyView::invalidate () inline override virtual
Request that the window content is redrawn.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 {}
nextStatusMessage()
std::string DummyView::nextStatusMessage () inline
   {
     boost::mutex::scoped_lock l(mut);
     BOOST_REQUIRE(cond.wait_for(l, boost::chrono::milliseconds(500), [&] { return !statusMessages.empty(); }));
     auto result = statusMessages.front();
     statusMessages.pop_front();
     return result;
   }
registerPostRenderer()
void DummyView::registerPostRenderer (PostRenderer::Ptr) inline override virtual
Register a postrenderer to be updated whenever a redraw occurs. When this happens, the 'render' function gets called on the instance that is passed to the given instance.
Note that the order in which different registered instances get updated is the order in which they register to the view. This order remains constant throughout the view's lifetime.
See also
PostRenderer
Implements ViewInterface.
 { reg_post++; }
registerSelectionListener()
void DummyView::registerSelectionListener (SelectionListener::Ptr) inline override virtual
Register a SelectionListener to be updated whenever the user selects a region . When the user changes the selection, various functions on the given instance are called.
See also
SelectionListener
Implements ViewInterface.
 { reg_sel++; }
removeFromToolbar()
void DummyView::removeFromToolbar (GtkToolItem * ti) inline override virtual
Request that the given tool item be removed from the toolbar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 {}
removeSideWidget()
void DummyView::removeSideWidget (GtkWidget * w) inline override virtual
Request that the given widget be removed from the sidebar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 {}
setStatusMessage()
void DummyView::setStatusMessage (const std::string &) inline override virtual
Sets the status message in the status bar of the application.
Implements ViewInterface.
   {
     boost::mutex::scoped_lock l(mut);
     statusMessages.push_back(msg);
     cond.notify_all();
   }
Member Data Documentation
cond
boost::condition_variable DummyView::cond
Referenced by nextStatusMessage(), and setStatusMessage().
mut
boost::mutex DummyView::mut
Referenced by nextStatusMessage(), and setStatusMessage().
presentation
PresentationInterface::Ptr DummyView::presentation
Referenced by getCurrentPresentation().
reg_post
int DummyView::reg_post = 0
Referenced by registerPostRenderer().
reg_sel
int DummyView::reg_sel = 0
Referenced by registerSelectionListener().
statusMessages
std::list<std::string> DummyView::statusMessages
Referenced by nextStatusMessage(), and setStatusMessage().
tool_btn
int DummyView::tool_btn = 0
Referenced by addToolButton().
The documentation for this class was generated from the following file:
plugins/pipette/test/pipette-tests.cc