Scroom: Scroom::Utils::Count Class Reference
Scroom::Utils::Count Class Reference
#include <utilities.hh>
Public Types
using Ptr = boost::shared_ptr< Count >
Public Member Functions
void ping ()
void inc ()
void dec ()
Static Public Member Functions
static Ptr create (const std::string &name)
Public Attributes
const std::string name
boost::mutex mut
long count
Private Member Functions
Count (const std::string &name)
Member Typedef Documentation
Ptr
using Scroom::Utils::Count::Ptr = boost::shared_ptr<Count>
Constructor & Destructor Documentation
Count()
Count::Count (const std::string & name) private
   : name(name_)
   , count(0)
 {}
Referenced by create().
Member Function Documentation
create()
Count::Ptr Count::create (const std::string & name) static
 {
   Ptr result = Ptr(new Count(name));
   Counter::instance()->registerCount(result);
   return result;
 }
Referenced by Scroom::Utils::Counted< TestCounted >::count_instance().
dec()
void Scroom::Utils::Count::dec () inline
       {
         boost::unique_lock<boost::mutex> lock(mut);
         --count;
         ping();
       }
inc()
void Scroom::Utils::Count::inc () inline
       {
         boost::unique_lock<boost::mutex> lock(mut);
         ++count;
         ping();
       }
ping()
void Scroom::Utils::Count::ping () inline
       { /* dumpCounts(); */
       }
Referenced by dec(), and inc().
Member Data Documentation
count
long Scroom::Utils::Count::count
Referenced by dec(), and inc().
mut
boost::mutex Scroom::Utils::Count::mut
Referenced by dec(), and inc().
name
const std::string Scroom::Utils::Count::name
Referenced by create().
The documentation for this class was generated from the following files:
inc/scroom/utilities.hh
libs/util/src/counter.cc