Scroom: MonochromeColormapHelper Class Reference
MonochromeColormapHelper Class Reference
#include <colormappable.hh>
Public Member Functions
std::map< std::string, std::string > getProperties () override
Color getMonochromeColor () override
void setMonochromeColor (const Color &c) override
void setTransparentBackground () override
void disableTransparentBackground () override
bool getTransparentBackground () override
Public Member Functions inherited from ColormapHelperBase
ColormapHelperBase (Colormap::Ptr const &colormap)
void setColormap (Colormap::Ptr colormap) override
Colormap::Ptr getOriginalColormap () override
int getNumberOfColors () override
Colormap::Ptr getColormap () override
virtual void setOriginalColormap (Colormap::Ptr colormap)
For monochrome presentations: Set/Get the current color
Manipulate the "Transparent Background" setting of the presentation
Static Public Member Functions
static Ptr create (int numberOfColors)
static Ptr createInverted (int numberOfColors)
Private Member Functions
MonochromeColormapHelper (int numberOfColors, bool inverted)
void regenerateColormap ()
Static Private Member Functions
static Colormap::Ptr generateInitialColormap (int numberOfColors, bool inverted)
Private Attributes
int numberOfColors
bool inverted
Color blackish
Color whitish
bool transparentBackground
Additional Inherited Members
Public Types inherited from ColormapHelperBase
using Ptr = boost::shared_ptr< ColormapHelperBase >
Public Types inherited from ColormapProvider
using Ptr = boost::shared_ptr< ColormapProvider >
Public Types inherited from Colormappable
using Ptr = boost::shared_ptr< Colormappable >
using WeakPtr = boost::weak_ptr< Colormappable >
Public Attributes inherited from ColormapHelperBase
Colormap::Ptr colormap
Colormap::Ptr originalColormap
Constructor & Destructor Documentation
MonochromeColormapHelper()
MonochromeColormapHelper::MonochromeColormapHelper (int numberOfColors, bool inverted) private
   : ColormapHelperBase(generateInitialColormap(numberOfColors_, inverted_))
   , numberOfColors(numberOfColors_)
   , inverted(inverted_)
   , blackish(Color(inverted_ ? 1 : 0))
   , whitish(Color(inverted_ ? 0 : 1))
   , transparentBackground(false)
 {}
Referenced by create(), and createInverted().
Member Function Documentation
create()
MonochromeColormapHelper::Ptr MonochromeColormapHelper::create (int numberOfColors) static
 {
   return Ptr(new MonochromeColormapHelper(numberOfColors, false));
 }
Referenced by BOOST_AUTO_TEST_CASE(), Scroom::TiledBitmap::GreyscaleBitmap(), and Scroom::Tiff::open().
createInverted()
MonochromeColormapHelper::Ptr MonochromeColormapHelper::createInverted (int numberOfColors) static
 {
   return Ptr(new MonochromeColormapHelper(numberOfColors, true));
 }
Referenced by BOOST_AUTO_TEST_CASE(), and Scroom::Tiff::open().
disableTransparentBackground()
void MonochromeColormapHelper::disableTransparentBackground () override virtual
Reimplemented from ColormapHelperBase.
 {
   transparentBackground = false;
   regenerateColormap();
 }
generateInitialColormap()
Colormap::Ptr MonochromeColormapHelper::generateInitialColormap (int numberOfColors, bool inverted) static private
 {
   return inverted ? Colormap::createDefaultInverted(numberOfColors) : Colormap::createDefault(numberOfColors);
 }
getMonochromeColor()
Color MonochromeColormapHelper::getMonochromeColor () override virtual
Reimplemented from ColormapHelperBase.
 { return inverted ? whitish : blackish; }
getProperties()
std::map< std::string, std::string > MonochromeColormapHelper::getProperties () override virtual
Implements ColormapHelperBase.
 {
   return {{MONOCHROME_COLORMAPPABLE_PROPERTY_NAME, ""}};
 }
getTransparentBackground()
bool MonochromeColormapHelper::getTransparentBackground () override virtual
Reimplemented from ColormapHelperBase.
 { return transparentBackground; }
regenerateColormap()
void MonochromeColormapHelper::regenerateColormap () private
 {
   Color w = whitish;
   Color b = blackish;
   if(transparentBackground)
   {
     if(inverted)
     {
       b.setAlpha(0);
     }
     else
     {
       w.setAlpha(0);
     }
   }
   for(int i = 0; i < numberOfColors; i++)
   {
     colormap->colors[i] = mix(w, b, 1.0 * i / (numberOfColors - 1));
   }
 }
Referenced by disableTransparentBackground(), setMonochromeColor(), and setTransparentBackground().
setMonochromeColor()
void MonochromeColormapHelper::setMonochromeColor (const Color & c) override virtual
Reimplemented from ColormapHelperBase.
 {
   if(inverted)
   {
     whitish = c;
   }
   else
   {
     blackish = c;
   }
   regenerateColormap();
 }
setTransparentBackground()
void MonochromeColormapHelper::setTransparentBackground () override virtual
Reimplemented from ColormapHelperBase.
 {
   transparentBackground = true;
   regenerateColormap();
 }
Member Data Documentation
blackish
Color MonochromeColormapHelper::blackish private
Referenced by getMonochromeColor(), regenerateColormap(), and setMonochromeColor().
inverted
bool MonochromeColormapHelper::inverted private
Referenced by generateInitialColormap(), getMonochromeColor(), regenerateColormap(), and setMonochromeColor().
numberOfColors
int MonochromeColormapHelper::numberOfColors private
Referenced by create(), createInverted(), generateInitialColormap(), and regenerateColormap().
transparentBackground
bool MonochromeColormapHelper::transparentBackground private
Referenced by disableTransparentBackground(), getTransparentBackground(), regenerateColormap(), and setTransparentBackground().
whitish
Color MonochromeColormapHelper::whitish private
Referenced by getMonochromeColor(), regenerateColormap(), and setMonochromeColor().
The documentation for this class was generated from the following files:
inc/scroom/colormappable.hh
libs/scroom/src/colormap-helpers.cc