Scroom: RulerDrawStrategy Class Reference
RulerDrawStrategy Class Reference abstract
#include <rulerstrategies.hh>
Public Types
using Ptr = boost::shared_ptr< RulerDrawStrategy >
Public Member Functions
virtual double getMajorTickLength (double percentage)=0
virtual double getDrawAreaSize ()=0
virtual void drawOutline (cairo_t *cr, double lineWidth)=0
virtual void drawTickLine (cairo_t *cr, double linePosition, double lineWidth, double lineLength)=0
virtual void drawTickText (cairo_t *cr, const std::string &label, double linePosition, double labelOffset, double labelAlign, double lineLength)=0
void setAllocatedSize (int newWidth, int height)
int getWidth () const
int getHeight () const
Static Protected Attributes
static constexpr double LINE_COORD_OFFSET {0.5}
static constexpr double TEXT_ANCHOR {0.5}
Private Attributes
int width
int height
Additional Inherited Members
Private Member Functions inherited from Interface
Interface ()=default
Interface (const Interface &)=delete
Interface & operator= (const Interface &)=delete
Interface (const Interface &&)=delete
Interface & operator= (const Interface &&)=delete
virtual ~Interface ()=default
Detailed Description
The Ruler class employs the Strategy pattern to draw the horizontal and vertical ruler. Implementations of this class contain the code to draw the parts of the ruler that need to be oriented differently.
Member Typedef Documentation
Ptr
using RulerDrawStrategy::Ptr = boost::shared_ptr<RulerDrawStrategy>
Member Function Documentation
drawOutline()
virtual void RulerDrawStrategy::drawOutline (cairo_t * cr, double lineWidth) pure virtual
Draws the outline around the ruler.
Parameters
cr Cairo context to draw to.
lineWidth Width of the outline in pixels.
width Allocated width for the ruler in pixels.
height Allocated height for the ruler in pixels.
Implemented in VerticalDrawStrategy, and HorizontalDrawStrategy.
drawTickLine()
virtual void RulerDrawStrategy::drawTickLine (cairo_t * cr, double linePosition, double lineWidth, double lineLength) pure virtual
Draws the line for a ruler tick.
Parameters
cr Cairo context to draw to.
linePosition Position of the line along the ruler in pixels.
lineWidth Width of the tick line in pixels.
lineLength Length of the tick line in pixels.
width Allocated width for the ruler in pixels.
height Allocated height for the ruler in pixels.
Implemented in VerticalDrawStrategy, and HorizontalDrawStrategy.
drawTickText()
virtual void RulerDrawStrategy::drawTickText (cairo_t * cr, const std::string & label, double linePosition, double labelOffset, double labelAlign, double lineLength) pure virtual
Draws the label to the right of a tick line.
Parameters
cr Cairo context to draw to.
label Text to draw to right of tick line.
linePosition Position of the line along the ruler in pixels.
labelOffset Offset between tick line and label in pixels.
labelAlign Alignment of label along tick line as a fraction of line length.
lineLength Length of the tick line in pixels.
width Allocated width for the ruler in pixels.
height Allocated height for the ruler in pixels.
Implemented in VerticalDrawStrategy, and HorizontalDrawStrategy.
getDrawAreaSize()
virtual double RulerDrawStrategy::getDrawAreaSize () pure virtual
Returns the length in pixels along the ruler. For a horizontal ruler, this is its width. For a vertical ruler, this is its height.
Parameters
width Allocated width for the ruler in pixels.
height Allocated height for the ruler in pixels.
Returns
The length in pixels along the ruler in pixels.
Implemented in VerticalDrawStrategy, and HorizontalDrawStrategy.
getHeight()
int RulerDrawStrategy::getHeight () const
Returns the allocated height.
Returns
The allocated height.
 { return height; }
Referenced by HorizontalDrawStrategy::drawOutline(), VerticalDrawStrategy::drawOutline(), HorizontalDrawStrategy::drawTickLine(), HorizontalDrawStrategy::drawTickText(), VerticalDrawStrategy::getDrawAreaSize(), and HorizontalDrawStrategy::getMajorTickLength().
getMajorTickLength()
virtual double RulerDrawStrategy::getMajorTickLength (double percentage) pure virtual
Returns the length of the major tick lines, given the ruler dimensions.
Parameters
width Allocated width for the ruler in pixels.
height Allocated height for the ruler in pixels.
percentage Percentage of the /p width or /p height to be the length of the major ticks.
Returns
The length of the major tick lines in pixels.
Implemented in VerticalDrawStrategy, and HorizontalDrawStrategy.
getWidth()
int RulerDrawStrategy::getWidth () const
Returns the allocated width.
Returns
The allocated width.
 { return width; }
Referenced by HorizontalDrawStrategy::drawOutline(), VerticalDrawStrategy::drawOutline(), VerticalDrawStrategy::drawTickLine(), VerticalDrawStrategy::drawTickText(), HorizontalDrawStrategy::getDrawAreaSize(), and VerticalDrawStrategy::getMajorTickLength().
setAllocatedSize()
void RulerDrawStrategy::setAllocatedSize (int newWidth, int height)
Sets the allocated newWidth and height for the ruler.
Parameters
newWidth Allocated newWidth for the ruler in pixels.
height Allocated height for the ruler in pixels.
 {
   this->width  = newWidth;
   this->height = newHeight;
 }
Member Data Documentation
height
int RulerDrawStrategy::height private
Allocated height for the ruler in pixels.
Referenced by getHeight(), and setAllocatedSize().
LINE_COORD_OFFSET
constexpr double RulerDrawStrategy::LINE_COORD_OFFSET {0.5} static constexpr protected
Referenced by HorizontalDrawStrategy::drawOutline(), VerticalDrawStrategy::drawOutline(), HorizontalDrawStrategy::drawTickLine(), and VerticalDrawStrategy::drawTickLine().
TEXT_ANCHOR
constexpr double RulerDrawStrategy::TEXT_ANCHOR {0.5} static constexpr protected
Referenced by HorizontalDrawStrategy::drawTickText(), and VerticalDrawStrategy::drawTickText().
width
int RulerDrawStrategy::width private
Allocated width for the ruler in pixels.
Referenced by getWidth(), and setAllocatedSize().
The documentation for this class was generated from the following files:
gui/ruler/src/rulerstrategies.hh
gui/ruler/src/rulerstrategies.cc