Scroom: A Class Reference
A Class Reference
Public Types
using Ptr = boost::shared_ptr< A >
using Ptr = boost::shared_ptr< A >
Public Member Functions
A (int &i_)
void set (int v)
int get () const
A (Semaphore *s1_, Semaphore *s2_)
~A ()
A (const A &)=delete
A (A &&)=delete
A & operator= (const A &)=delete
A & operator= (A &&)=delete
A (Semaphore *s_)
void operator() ()
Static Public Member Functions
static Ptr create (int &i)
static Ptr create (Semaphore *s)
Private Attributes
int & i
Semaphore * s1
Semaphore * s2
Semaphore * s
Member Typedef Documentation
Ptr [1/2]
using A::Ptr = boost::shared_ptr<A>
Ptr [2/2]
using A::Ptr = boost::shared_ptr<A>
Constructor & Destructor Documentation
A() [1/5]
A::A (int & i_) inline
     : i(i_)
   {}
Referenced by anonymous_namespace{boost-smart-pointers.cc}::A::create(), and create().
A() [2/5]
A::A (Semaphore * s1_, Semaphore * s2_) inline
     : s1(s1_)
     , s2(s2_)
   {}
~A()
A::~A () inline
   {
     s1->P();
     s2->V();
   }
A() [3/5]
A::A (const A &) delete
A() [4/5]
A::A (A &&) delete
A() [5/5]
A::A (Semaphore * s_) inline
     : s(s_)
   {}
Member Function Documentation
create() [1/2]
static Ptr A::create (int & i) inline static
 { return Ptr(new A(i)); }
Referenced by BOOST_AUTO_TEST_CASE().
create() [2/2]
static Ptr A::create (Semaphore * s) inline static
 { return Ptr(new A(s)); }
get()
int A::get () const inline
 { return i; }
Referenced by BOOST_AUTO_TEST_CASE().
operator()()
void A::operator() () inline
 { s->V(); }
operator=() [1/2]
A& A::operator= (A &&) delete
operator=() [2/2]
A& A::operator= (const A &) delete
set()
void A::set (int v) inline
 { i = v; }
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
i
int& A::i private
Referenced by create(), get(), and set().
s
Semaphore* A::s private
s1
Semaphore* A::s1 private
s2
Semaphore* A::s2 private
The documentation for this class was generated from the following files:
libs/sanity-tests/boost-bind.cc
libs/threadpool/test/threadpool-tests.cc
libs/threadpool/test/async-deleter-tests.cc