Scroom: Scroom::Semaphore Class Reference
Scroom::Semaphore Class Reference
#include <semaphore.hh>
Public Member Functions
Semaphore (unsigned int count=0)
void P ()
void V ()
template<typename duration_type >
bool P (duration_type const &rel_time)
bool try_P ()
Private Attributes
unsigned int count
boost::condition_variable cond
boost::mutex mut
Constructor & Destructor Documentation
Semaphore()
Scroom::Semaphore::Semaphore (unsigned int count = 0) inline
     : count(count_)
   {}
Member Function Documentation
P() [1/2]
void Scroom::Semaphore::P () inline
   {
     boost::mutex::scoped_lock lock(mut);
     while(count == 0)
     {
       cond.wait(lock);
     }
     count--;
   }
Referenced by BOOST_AUTO_TEST_CASE(), WaitForAsyncOp::operator()(), anonymous_namespace{helpers.cc}::passImpl(), and A::~A().
P() [2/2]
template<typename duration_type > bool Scroom::Semaphore::P (duration_type const & rel_time) inline
   {
     boost::posix_time::ptime timeout = boost::posix_time::second_clock::universal_time() + rel_time;
     boost::mutex::scoped_lock lock(mut);
     while(count == 0)
     {
       if(!cond.timed_wait(lock, timeout))
       {
         return false;
       }
     }
     count--;
     return true;
   }
try_P()
bool Scroom::Semaphore::try_P () inline
   {
     boost::mutex::scoped_lock lock(mut);
     if(count > 0)
     {
       count--;
       return true;
     }
     return false;
   }
Referenced by BOOST_AUTO_TEST_CASE(), and test_count_equals().
V()
void Scroom::Semaphore::V () inline
   {
     boost::mutex::scoped_lock lock(mut);
     count++;
     cond.notify_one();
   }
Referenced by BOOST_AUTO_TEST_CASE(), clear(), anonymous_namespace{helpers.cc}::clearImpl(), no_op(), A::operator()(), B< R >::operator()(), and A::~A().
Member Data Documentation
cond
boost::condition_variable Scroom::Semaphore::cond private
Referenced by P(), and V().
count
unsigned int Scroom::Semaphore::count private
Referenced by P(), try_P(), and V().
mut
boost::mutex Scroom::Semaphore::mut private
Referenced by P(), try_P(), and V().
The documentation for this class was generated from the following file:
inc/scroom/semaphore.hh