Scroom: Scroom::GtkHelpers::Detail::Wrapper Class Reference
Scroom::GtkHelpers::Detail::Wrapper Class Reference
Public Member Functions
Wrapper (const boost::function< bool()> &f)
Static Public Member Functions
static gpointer create (const boost::function< bool()> &f)
Public Attributes
boost::function< bool()> f
Constructor & Destructor Documentation
Wrapper()
Scroom::GtkHelpers::Detail::Wrapper::Wrapper (const boost::function< bool()> & f)
         : f(f_)
       {}
Referenced by create().
Member Function Documentation
create()
gpointer Scroom::GtkHelpers::Detail::Wrapper::create (const boost::function< bool()> & f) static
 { return new Wrapper(f); }
Member Data Documentation
f
boost::function<bool()> Scroom::GtkHelpers::Detail::Wrapper::f
Referenced by create(), and Scroom::GtkHelpers::Detail::gtkWrapper().
The documentation for this class was generated from the following file:
libs/util/src/gtk-helpers.cc