Scroom: libs/scroom/test/colormaphelpers_test.cc File Reference
colormaphelpers_test.cc File Reference
#include <list>
#include <type_traits>
#include <boost/assign/list_of.hpp>
#include <boost/test/data/monomorphic.hpp>
#include <boost/test/data/test_case.hpp>
#include <boost/test/parameterized_test.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/test/unit_test_suite.hpp>
#include <scroom/colormappable.hh>
#include <scroom/unused.hh>
Classes
struct anonymous_namespace{colormaphelpers_test.cc}::Data
Namespaces
anonymous_namespace{colormaphelpers_test.cc}
Functions
std::ostream & anonymous_namespace{colormaphelpers_test.cc}::operator<< (std::ostream &os, const Data &)
BOOST_REQUIRE (originalColormap)
BOOST_CHECK_EQUAL (sample.expectedColors, originalColormap->colors.size())
BOOST_REQUIRE (colormap)
BOOST_CHECK_EQUAL (sample.expectedColors, colormap->colors.size())
BOOST_CHECK_EQUAL (originalColormap, colormap)
BOOST_AUTO_TEST_CASE (regular_colormaps_cant_have_their_colors_set)
BOOST_AUTO_TEST_CASE (monochrome_colormap_can_have_its_color_set)
BOOST_AUTO_TEST_CASE (inverted_monochrome_colormap_can_have_its_color_set)
Variables
const Color anonymous_namespace{colormaphelpers_test.cc}::Blue (0, 0, 1)
const double anonymous_namespace{colormaphelpers_test.cc}::accuracy = 1e-4
std::list< Data > anonymous_namespace{colormaphelpers_test.cc}::helpers
Colormap::Ptr colormap = sample.helper->getColormap()
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (inverted_monochrome_colormap_can_have_its_color_set)
 {
   ColormapHelper::Ptr helper                   = MonochromeColormapHelper::createInverted(256);
   Colormap::Ptr       originalOriginalColormap = helper->getOriginalColormap();
   // At least one color in the current colormap doesn't have a blue component
   BOOST_CHECK_NE(1, helper->getColormap()->colors.back().blue);
   helper->setMonochromeColor(Blue);
   BOOST_CHECK_EQUAL(originalOriginalColormap, helper->getOriginalColormap());
   Colormap::Ptr newColorMap = helper->getColormap();
   for(Color& c: newColorMap->colors)
   {
     BOOST_CHECK_CLOSE(1, c.blue, accuracy);
   }
   Color currentColor = helper->getMonochromeColor();
   BOOST_CHECK_CLOSE(Blue.red, currentColor.red, accuracy);
   BOOST_CHECK_CLOSE(Blue.green, currentColor.green, accuracy);
   BOOST_CHECK_CLOSE(Blue.blue, currentColor.blue, accuracy);
 }
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (monochrome_colormap_can_have_its_color_set)
 {
   ColormapHelper::Ptr helper                   = MonochromeColormapHelper::create(256);
   Colormap::Ptr       originalOriginalColormap = helper->getOriginalColormap();
   // At least one color in the current colormap doesn't have a blue component
   BOOST_CHECK_NE(1, helper->getColormap()->colors[0].blue);
   helper->setMonochromeColor(Blue);
   BOOST_CHECK_EQUAL(originalOriginalColormap, helper->getOriginalColormap());
   Colormap::Ptr newColorMap = helper->getColormap();
   for(Color& c: newColorMap->colors)
   {
     BOOST_CHECK_CLOSE(1, c.blue, accuracy);
   }
   Color currentColor = helper->getMonochromeColor();
   BOOST_CHECK_CLOSE(Blue.red, currentColor.red, accuracy);
   BOOST_CHECK_CLOSE(Blue.green, currentColor.green, accuracy);
   BOOST_CHECK_CLOSE(Blue.blue, currentColor.blue, accuracy);
 }
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (regular_colormaps_cant_have_their_colors_set)
 {
   ColormapHelper::Ptr helper = ColormapHelper::create(256);
   BOOST_CHECK_THROW(helper->setMonochromeColor(Color(0, 0, 1)), std::runtime_error);
 }
BOOST_CHECK_EQUAL() [1/3]
BOOST_CHECK_EQUAL (originalColormap , colormap)
BOOST_CHECK_EQUAL() [2/3]
BOOST_CHECK_EQUAL (sample. expectedColors, colormap->colors. size())
BOOST_CHECK_EQUAL() [3/3]
BOOST_CHECK_EQUAL (sample. expectedColors, originalColormap->colors. size())
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE_TEMPLATE(), anonymous_namespace{determine-size-test.cc}::ResizablePresentationInterfaceStub::CheckAllEqual(), containedSegmentEqualsIntersection(), intersectsImpliesNonEmptyIntersection(), and ProgressInterfaceMultiplexer_Fixture::ProgressInterfaceMultiplexer_Fixture().
BOOST_REQUIRE() [1/2]
BOOST_REQUIRE (colormap)
BOOST_REQUIRE() [2/2]
BOOST_REQUIRE (originalColormap)
Referenced by BOOST_AUTO_TEST_CASE(), and DummyView::nextStatusMessage().
Variable Documentation
colormap
Colormap::Ptr colormap = sample.helper->getColormap()
Referenced by Operations1bpp::cache(), Operations8bpp::cache(), Operations::cache(), OperationsColormapped::cache(), Operations1bppClipped::cacheZoom(), Operations1bpp::draw(), Operations8bpp::draw(), Operations::draw(), Scroom::Tiff::getColorMap(), Scroom::ColormapImpl::Colormaps::load(), Scroom::ColormapImpl::ColormapProvider::on_colormap_selected(), TransformPresentation::setColormap(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::setColormap(), setupTest1bpp(), setupTest2bpp(), setupTest4bpp(), setupTest8bpp(), setupTest8bppColormapped(), and Scroom::ColormapImpl::ColormapProvider::~ColormapProvider().