Scroom: libs/threadpool/test/helpers.cc File Reference
helpers.cc File Reference
#include "helpers.hh"
#include <scroom/semaphore.hh>
Namespaces
anonymous_namespace{helpers.cc}
Functions
void anonymous_namespace{helpers.cc}::passImpl (Semaphore *s)
void anonymous_namespace{helpers.cc}::clearImpl (Semaphore *s)
void anonymous_namespace{helpers.cc}::destroyImpl (boost::shared_ptr< void > &p)
boost::function< void()> pass (Semaphore *s)
boost::function< void()> clear (Semaphore *s)
boost::function< void()> destroy (boost::shared_ptr< void > p)
Function Documentation
clear()
boost::function<void()> clear (Semaphore * s)
 { return boost::bind(clearImpl, s); }
Referenced by BOOST_AUTO_TEST_CASE(), and has_at_least_n_threads().
destroy()
boost::function<void()> destroy (boost::shared_ptr< void > p)
 { return boost::bind(destroyImpl, p); }
Referenced by BOOST_AUTO_TEST_CASE().
pass()
boost::function<void()> pass (Semaphore * s)
 { return boost::bind(passImpl, s); }
Referenced by BOOST_AUTO_TEST_CASE(), and has_at_least_n_threads().