Scroom: libs/tiled-bitmap/tools/measure-framerate-callbacks.cc File Reference
measure-framerate-callbacks.cc File Reference
#include "measure-framerate-callbacks.hh"
#include <scroom/unused.hh>
#include "test-helpers.hh"
Functions
static gboolean on_configure (GtkWidget *, GdkEventConfigure *, gpointer)
static void on_hide (GtkWidget *, gpointer)
static gboolean on_expose (GtkWidget *widget, GdkEventExpose *, gpointer)
static gboolean on_idle (gpointer)
GtkWidget * create_window ()
void init ()
void invalidate ()
Variables
std::vector< boost::function< bool()> > functions
static unsigned int current = 0
static GtkWidget * drawingArea = nullptr
Function Documentation
create_window()
GtkWidget* create_window ()
 {
   GtkWidget* window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
   gtk_window_set_title(GTK_WINDOW(window), "Measure Framerate");
   gtk_window_maximize(GTK_WINDOW(window));
   g_signal_connect(static_cast<gpointer>(window), "hide", G_CALLBACK(on_hide), NULL);
   drawingArea = gtk_drawing_area_new();
   gtk_container_add(GTK_CONTAINER(window), drawingArea);
   g_signal_connect(static_cast<gpointer>(drawingArea), "draw", G_CALLBACK(on_expose), NULL);
   g_signal_connect(static_cast<gpointer>(drawingArea), "configure_event", G_CALLBACK(on_configure), NULL);
   gtk_widget_show(drawingArea);
   gtk_widget_show(window);
   return window;
 }
Referenced by main().
init()
void init ()
 { gdk_threads_add_idle(on_idle, nullptr); }
Referenced by main().
invalidate()
void invalidate ()
 {
   GdkWindow* window = gtk_widget_get_window(drawingArea);
   gdk_window_invalidate_rect(window, nullptr, false);
 }
Referenced by Invalidator::operator()(), and InvalidatingCounter::operator()().
on_configure()
static gboolean on_configure (GtkWidget * , GdkEventConfigure * , gpointer) static
 {
   // There should be a simpler way to do this...
   cairo_region_t*       r = gdk_window_get_visible_region(gtk_widget_get_window(drawingArea));
   cairo_rectangle_int_t rect;
   cairo_region_get_extents(r, &rect);
   drawingAreaWidth  = rect.width;
   drawingAreaHeight = rect.height;
   cairo_region_destroy(r);
   return FALSE;
 }
Referenced by create_window().
on_expose()
static gboolean on_expose (GtkWidget * widget, GdkEventExpose * , gpointer) static
 {
   cairo_region_t* re = cairo_region_create();
   GdkDrawingContext* dc;
   dc = gdk_window_begin_draw_frame(gtk_widget_get_window(widget), re);
   cairo_t* cr = gdk_drawing_context_get_cairo_context(dc);
   if(testData)
   {
     testData->redraw(cr);
   }
   gdk_window_end_draw_frame(gtk_widget_get_window(widget), dc);
   cairo_region_destroy(re);
   return FALSE;
 }
Referenced by create_window().
on_hide()
static void on_hide (GtkWidget * , gpointer) static
 { gtk_main_quit(); }
Referenced by create_window().
on_idle()
static gboolean on_idle (gpointer) static
 {
   if(current >= functions.size())
   {
     return false;
   }
   if(!functions[current]())
   {
     current++;
   }
   return true;
 }
Referenced by init().
Variable Documentation
current
unsigned int current = 0 static
Referenced by anonymous_namespace{progressbarmanager.cc}::ProgressBarPulser::doWork(), Operations1bpp::draw(), Operations::draw(), on_idle(), Operations1bpp::reduce(), Operations8bpp::reduce(), Operations24bpp::reduce(), Operations::reduce(), OperationsColormapped::reduce(), Operations1bppClipped::reduce(), OperationsCMYK32::reduce(), OperationsCMYK16::reduce(), OperationsCMYK8::reduce(), OperationsCMYK4::reduce(), and anonymous_namespace{progressbarmanager.cc}::ProgressBarPulser::start().
drawingArea
GtkWidget* drawingArea = nullptr static
Referenced by BOOST_AUTO_TEST_CASE(), create_scroom(), create_window(), invalidate(), and on_configure().
functions
std::vector<boost::function<bool()> > functions
Referenced by Scroom::Detail::ThreadPool::FunctionAdditor::addAfter(), init_tests(), on_idle(), and Scroom::Detail::ThreadPool::FunctionAdditor::operator()().