Scroom: libs/tiled-bitmap/tools/measure-framerate-callbacks.hh File Reference
measure-framerate-callbacks.hh File Reference
#include <vector>
#include <boost/function.hpp>
#include <gtk/gtk.h>
Functions
GtkWidget * create_window ()
void init ()
void invalidate ()
Variables
std::vector< boost::function< bool()> > functions
Function Documentation
create_window()
GtkWidget* create_window ()
 {
   GtkWidget* window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
   gtk_window_set_title(GTK_WINDOW(window), "Measure Framerate");
   gtk_window_maximize(GTK_WINDOW(window));
   g_signal_connect(static_cast<gpointer>(window), "hide", G_CALLBACK(on_hide), NULL);
   drawingArea = gtk_drawing_area_new();
   gtk_container_add(GTK_CONTAINER(window), drawingArea);
   g_signal_connect(static_cast<gpointer>(drawingArea), "draw", G_CALLBACK(on_expose), NULL);
   g_signal_connect(static_cast<gpointer>(drawingArea), "configure_event", G_CALLBACK(on_configure), NULL);
   gtk_widget_show(drawingArea);
   gtk_widget_show(window);
   return window;
 }
Referenced by main().
init()
void init ()
 { gdk_threads_add_idle(on_idle, nullptr); }
Referenced by main().
invalidate()
void invalidate ()
 {
   GdkWindow* window = gtk_widget_get_window(drawingArea);
   gdk_window_invalidate_rect(window, nullptr, false);
 }
Referenced by Invalidator::operator()(), and InvalidatingCounter::operator()().
Variable Documentation
functions
std::vector<boost::function<bool()> > functions
Referenced by Scroom::Detail::ThreadPool::FunctionAdditor::addAfter(), init_tests(), on_idle(), and Scroom::Detail::ThreadPool::FunctionAdditor::operator()().