Scroom: anonymous_namespace{cmyklayeroperations.cc} Namespace Reference
anonymous_namespace{cmyklayeroperations.cc} Namespace Reference
Functions
boost::shared_ptr< unsigned char > shared_malloc (size_t size)
Function Documentation
shared_malloc()
boost::shared_ptr<unsigned char> anonymous_namespace{cmyklayeroperations.cc}::shared_malloc (size_t size)
   {
     return boost::shared_ptr<unsigned char>(static_cast<unsigned char*>(malloc(size)), free);
   }
Referenced by OperationsCMYK32::cache(), OperationsCMYK16::cache(), OperationsCMYK8::cache(), and OperationsCMYK4::cache().