Scroom: anonymous_namespace{helpers.cc} Namespace Reference
anonymous_namespace{helpers.cc} Namespace Reference
Functions
void passImpl (Semaphore *s)
void clearImpl (Semaphore *s)
void destroyImpl (boost::shared_ptr< void > &p)
Function Documentation
clearImpl()
void anonymous_namespace{helpers.cc}::clearImpl (Semaphore * s)
 { s->V(); }
Referenced by clear().
destroyImpl()
void anonymous_namespace{helpers.cc}::destroyImpl (boost::shared_ptr< void > & p)
 { p.reset(); }
Referenced by destroy().
passImpl()
void anonymous_namespace{helpers.cc}::passImpl (Semaphore * s)
 { s->P(); }
Referenced by pass().