Scroom: anonymous_namespace{progressbarmanager.cc} Namespace Reference
anonymous_namespace{progressbarmanager.cc} Namespace Reference
Classes
class ProgressBarPulser
Functions
ProgressBarPulser::Ptr instance ()
Function Documentation
instance()
ProgressBarPulser::Ptr anonymous_namespace{progressbarmanager.cc}::instance ()
   {
     static ProgressBarPulser::Ptr pulser = ProgressBarPulser::Ptr(new ProgressBarPulser());
     return pulser;
   }
Referenced by ThreadPool::add(), Scroom::Utils::Counted< TestCounted >::count_instance(), Scroom::MemoryBlocks::getBlockFactoryInterface(), Scroom::ColormapImpl::Colormaps::getInstance(), anonymous_namespace{threadpoolimpl.cc}::NotifyThreadList< T >::NotifyThreadList(), on_done_loading_plugins(), ProgressBarManager::startWaiting(), and ProgressBarManager::stopWaiting().