Scroom: libs/tiled-bitmap/test/sampleiterator-tests.cc File Reference
sampleiterator-tests.cc File Reference
#include <list>
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include <scroom/bitmap-helpers.hh>
Namespaces
anonymous_namespace{sampleiterator-tests.cc}
Scroom
Scroom::Bitmap
Functions
template<typename T >
std::ostream & Scroom::Bitmap::operator<< (std::ostream &os, const SampleIterator< T > &it)
for (auto i=0;i< it.samplesPerBase;i++, it++, out++)
BOOST_CHECK_EQUAL (0, memcmp(testData, output, 2))
BOOST_AUTO_TEST_CASE (equality)
BOOST_DATA_TEST_CASE (arithmetic, data::make(bit_depths) *data::make(initial_offsets) *data::make(deltas), bps, initial_offset, delta)
Variables
const uint8_t anonymous_namespace{sampleiterator-tests.cc}::testData [] = {0x65, 0xC7}
const int anonymous_namespace{sampleiterator-tests.cc}::bit_depths [] = {1, 2, 4, 8}
const int anonymous_namespace{sampleiterator-tests.cc}::initial_offsets [] = {0, 1}
const int anonymous_namespace{sampleiterator-tests.cc}::deltas [] = {0, 1, 5}
uint8_t output [] = {0, 0}
SampleIterator< uint8_t > out (output, 0, bps)
const unsigned int mask = (1 << bps) - 1
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (equality)
 {
   BOOST_CHECK_EQUAL(SampleIterator<uint8_t>(nullptr, 0, 1), SampleIterator<uint8_t>(nullptr, 0, 1));
   BOOST_CHECK_NE(SampleIterator<const uint8_t>(nullptr, 0, 1), SampleIterator<const uint8_t>(testData, 0, 1));
   BOOST_CHECK_NE(SampleIterator<uint8_t>(nullptr, 0, 1), SampleIterator<uint8_t>(nullptr, 1, 1));
   BOOST_CHECK_NE(SampleIterator<uint8_t>(nullptr, 0, 1), SampleIterator<uint8_t>(nullptr, 0, 2));
 }
BOOST_CHECK_EQUAL()
BOOST_CHECK_EQUAL (0 , memcmp(testData, output, 2))
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), and for().
BOOST_DATA_TEST_CASE()
BOOST_DATA_TEST_CASE (arithmetic , data::make(bit_depths) *data::make(initial_offsets) *data::make(deltas) , bps , initial_offset , delta)
 {
   const SampleIterator<const uint8_t> start(nullptr, initial_offset, bps);
   SampleIterator<const uint8_t>       expected = start;
   for(auto i = 0; i < delta; i++, expected++)
   {
   }
   SampleIterator<const uint8_t> result = start;
   result += delta;
   BOOST_CHECK_EQUAL(result, expected);
   BOOST_CHECK_EQUAL(start + delta, expected);
   BOOST_CHECK_EQUAL(delta + start, expected);
 }
for()
for ()
   {
     BOOST_CHECK_EQUAL((testData[0] >> (8 - bps * (i + 1))) & mask, *it);
     BOOST_CHECK_EQUAL((testData[0] >> (8 - bps * (i + 1))) & mask, it.get());
     out.set(*it);
   }
Variable Documentation
mask
const unsigned int mask = (1 << bps) - 1
Referenced by BOOST_AUTO_TEST_CASE(), and for().
out
SampleIterator<uint8_t> out(output, 0, bps)
Referenced by BOOST_AUTO_TEST_CASE(), Scroom::MemoryBlobs::Detail::decompressBlob(), and for().
output
uint8_t output[] = {0, 0}