Scroom: libs/tiled-bitmap/src/tiled-bitmap.cc File Reference
tiled-bitmap.cc File Reference
#include "tiled-bitmap.hh"
#include <cmath>
#include <cstdio>
#include <boost/thread/mutex.hpp>
#include <scroom/cairo-helpers.hh>
#include <scroom/semaphore.hh>
#include <scroom/unused.hh>
#include "tileviewstate.hh"
Functions
TiledBitmapInterface::Ptr createTiledBitmap (int bitmapWidth, int bitmapHeight, LayerSpec const &ls)
Scroom::Utils::Rectangle< int > TileAreaForIndex (Scroom::Utils::Point< int > tileIndex)
Function Documentation
createTiledBitmap()
TiledBitmapInterface::Ptr createTiledBitmap (int bitmapWidth, int bitmapHeight, LayerSpec const & ls)
Create a tiled bitmap.
In a TiledBitmap, your bitmap is distributed over tiles, that each contain a square portion of your bitmap. These tiles will be swapped in or out as required, depending on the amount of available memory. This way, you can "load" bitmaps that are larger than your amount of memory would normally allow.
Of course, when zooming out, you'd still need all the data in your bitmap, in order to show the scaled down version. To avoid this, createTiledBitmap() creates pre-scaled versions of your bitmap, that are reduced by a factor 8. Such a pre-scaled version is called a Layer. If your bitmap gets very large, several pre-scaled versions are created, reduced by a factor 8, 64, 512, 4096, etc.
So, to summarize, createTiledBitmap() creates several layers of your bitmap, at zoom levels 1:1, 1:8, 1:64, etc. Each layer is then divided into tiles, such that only the relevant part can be loaded into memory.
Of course createTiledBitmap() doesn't know anything about how you choose to represent your bitmap data, so you'll have to specify (by implementing LayerOperations) how to draw portions of your bitmap at given zoom levels, and how to pre-scale your bitmap.
Note
When calling createTiledBitmap(), all the internal data structures will be set up. You still have to fill your bitmap with data, for example by calling TiledBitmapInterface::setSource()
Parameters
bitmapWidth the width of the bitmap
bitmapHeight the height of the bitmap
ls LayerOperations objects, specifying how to draw (portions of) your bitmap at given zoom levels
Returns
A pointer to a newly created TiledBitmapInterface. You can use this pointer to manipulate your bitmap.
 {
   return TiledBitmap::create(bitmapWidth, bitmapHeight, ls);
 }
Referenced by BOOST_AUTO_TEST_CASE(), setupTest1bpp(), setupTest2bpp(), setupTest4bpp(), setupTest8bpp(), and setupTest8bppColormapped().
TileAreaForIndex()
Scroom::Utils::Rectangle<int> TileAreaForIndex (Scroom::Utils::Point< int > tileIndex) inline
 {
   return (Scroom::Utils::Rectangle<int>(0, 0, 1, 1) + tileIndex) * TILESIZE;
 }
Referenced by TiledBitmap::redraw().