#!/bin/sh

remove_if_exists()
{
    if [ -e "$1" ] && ! rm -rf "$1"
    then
        exit 1
    fi
}

echo_me()
{
    echo "$ME: $*"
}

cleanup()
{
    echo_me "Performing cleanup"
    remove_if_exists "$TMPDIR"
}

prepare()
{
    remove_if_exists config.log
    remove_if_exists configure.log
    remove_if_exists package-helper
}

ME="$0"
trap cleanup 0
prepare

echo_me "Build:  ${BUILD:=${HOME}/build}"
echo_me "Tmp:    ${TMP:=/tmp}"
echo_me "Name:   ${NAME:=Kees-Jan Dijkzeul}"
echo_me "E-mail: ${EMAIL:=kees-jan.dijkzeul@iae.nl}"
echo ""


if [ ! -d "$BUILD" -o ! -w "$BUILD" ]
then
    echo_me "ERROR: Build directory ($BUILD) not writable or no directory"
    exit 1
fi

if [ ! -d "$TMP" -o ! -w "$TMP" ]
then
    echo_me "ERROR: Temporary directory ($TMP) not writable or no directory"
    exit 1
fi

if [ -z "$1" ]
then
    echo_me "ERROR: Nothing to package"
    exit 1
fi

SOURCE="$1"
TMPDIR=$(mktemp -d -p $TMP) || exit 1

case "$SOURCE" in
    *.tar.gz|*.tgz)
        echo_me "Untarring $SOURCE"
        tar xzfC "$SOURCE" "$TMPDIR" || exit 1
        ;;
    *)
        echo_me "ERROR: Input tarball in unrecognized format"
        exit 1
        ;;
esac

ROOTDIR="$(ls $TMPDIR)" # yuk
TMPSRCDIR="$TMPDIR/$ROOTDIR" 
if [ ! -x "$TMPSRCDIR/configure"  ]
then
    echo_me "ERROR: Configure ($TMPSRCDIR/configure) not executable"
    exit 1;
fi

echo_me "Executing configure"

if ! (cd "$TMPSRCDIR" && ./configure ) > configure.log 2>&1
then
    echo_me "ERROR: Configure failed. See configure.log"
    mv "$TMPSRCDIR/config.log" .
    exit 1
fi

export TMPSRCDIR SOURCE BUILD NAME EMAIL

"$TMPSRCDIR/config.status" --file package-helper && chmod +x ./package-helper && ./package-helper
