#!/bin/sh -uex

parallel --tag docker build -t test-scroom-dockerfiles:\{\} \{\} < supported-ubuntu-releases

echo Docker images built succesfully

if [ -n "${1+x}" ] && [ -n "$1" ] && [ -d "$1" ]
then
    SCROOM="$1"

    SCROOM_ABSOLUTE="$(cd $SCROOM && pwd)"
    for d in $(cat supported-ubuntu-releases)
    do
        echo $d
        if docker run -v "$SCROOM_ABSOLUTE":/home/build/scroom --rm test-scroom-dockerfiles:$d sh -x -c \
              "D=\$(mktemp -d) && cmake -S /home/build/scroom -B \$D -GNinja && cmake --build \$D && cd \$D && xvfb-run ctest -j \$(nproc)" > $d.log 2>&1
        then
            echo "$d - succeeded"
        else
            echo "$d - failed"
        fi
    done    
fi
