#!/bin/bash

set -x
set -u
set -e

find inc libs plugins gui External -name CMakeLists.txt -exec cmake-format -i '{}' +
cmake-format -i CMakeLists.txt
find cmake -name \*.cmake -exec cmake-format -i '{}' +