#!/bin/bash -eux
set -o pipefail

MY_LOCATION=$(dirname "${BASH_SOURCE[0]}")
source "${MY_LOCATION}/clang-tidy-inc.sh"

find_sources_print0 | parallel -0 clang-tidy-${CLANG_VERSION} --quiet -p="$BUILD" \{\} | tee ct.log
