Scroom: Detail::ViewData Class Reference
Detail::ViewData Class Reference
#include <transformpresentation.hh>
Public Types
using Ptr = std::shared_ptr< ViewData >
Public Types inherited from ViewInterface
using Ptr = std::shared_ptr< ViewInterface >
using WeakPtr = std::weak_ptr< ViewInterface >
Public Member Functions
ViewInterface::Ptr parent () const
void invalidate () override
ProgressInterface::Ptr getProgressInterface () override
void addSideWidget (std::string title, GtkWidget *w) override
void removeSideWidget (GtkWidget *w) override
void addToToolbar (GtkToolItem *ti) override
void removeFromToolbar (GtkToolItem *ti) override
void registerSelectionListener (SelectionListener::Ptr ptr) override
void registerPostRenderer (PostRenderer::Ptr ptr) override
void setStatusMessage (const std::string &string) override
std::shared_ptr< PresentationInterface > getCurrentPresentation () override
void addToolButton (GtkToggleButton *button, ToolStateListener::Ptr ptr) override
Static Public Member Functions
static ViewData::Ptr create (const ViewInterface::WeakPtr &parent)
Public Attributes
Scroom::Utils::Rectangle< double > presentationArea
int zoom {0}
Scroom::Bitmap::BitmapSurface::Ptr image
ViewInterface::WeakPtr weakParent
Private Member Functions
ViewData (ViewInterface::WeakPtr parent_)
Member Typedef Documentation
Ptr
using Detail::ViewData::Ptr = std::shared_ptr<ViewData>
Constructor & Destructor Documentation
ViewData()
Detail::ViewData::ViewData (ViewInterface::WeakPtr parent_) explicit private
     : weakParent(std::move(parent_))
   {
   }
Referenced by create().
Member Function Documentation
addSideWidget()
void Detail::ViewData::addSideWidget (std::string title, GtkWidget * w) override virtual
Request that the given widget be added to the sidebar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 { parent()->addSideWidget(title, w); }
addToolButton()
void Detail::ViewData::addToolButton (GtkToggleButton * , ToolStateListener::Ptr) override virtual
Adds a new tool button to the toolbar. The given ToolStateListener will be informed when the tool is turned on or off. Only one tool will be active at the same time.
See also
ToolStateListener
Implements ViewInterface.
 { parent()->addToolButton(button, ptr); }
addToToolbar()
void Detail::ViewData::addToToolbar (GtkToolItem * ti) override virtual
Request that the given tool item be added to the toolbar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 { parent()->addToToolbar(ti); }
create()
ViewData::Ptr Detail::ViewData::create (const ViewInterface::WeakPtr & parent) static
 { return ViewData::Ptr(new ViewData(parent)); }
Referenced by TransformPresentation::open().
getCurrentPresentation()
std::shared_ptr< PresentationInterface > Detail::ViewData::getCurrentPresentation () override virtual
Returns a shared pointer to the current presentation.
See also
PresentationInterface
Implements ViewInterface.
 { return parent()->getCurrentPresentation(); }
getProgressInterface()
ProgressInterface::Ptr Detail::ViewData::getProgressInterface () override virtual
Return a pointer to the progess interface associated with the View
Note
The progress bar should only be manipulated from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 { return parent()->getProgressInterface(); }
invalidate()
void Detail::ViewData::invalidate () override virtual
Request that the window content is redrawn.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
   {
     image.reset();
     parent()->invalidate();
   }
parent()
ViewInterface::Ptr Detail::ViewData::parent () const
 { return ViewInterface::Ptr(weakParent); }
Referenced by addSideWidget(), addToolButton(), addToToolbar(), create(), getCurrentPresentation(), getProgressInterface(), invalidate(), registerPostRenderer(), registerSelectionListener(), removeFromToolbar(), removeSideWidget(), and setStatusMessage().
registerPostRenderer()
void Detail::ViewData::registerPostRenderer (PostRenderer::Ptr) override virtual
Register a postrenderer to be updated whenever a redraw occurs. When this happens, the 'render' function gets called on the instance that is passed to the given instance.
Note that the order in which different registered instances get updated is the order in which they register to the view. This order remains constant throughout the view's lifetime.
See also
PostRenderer
Implements ViewInterface.
 { parent()->registerPostRenderer(ptr); }
registerSelectionListener()
void Detail::ViewData::registerSelectionListener (SelectionListener::Ptr) override virtual
Register a SelectionListener to be updated whenever the user selects a region . When the user changes the selection, various functions on the given instance are called.
See also
SelectionListener
Implements ViewInterface.
 { parent()->registerSelectionListener(ptr); }
removeFromToolbar()
void Detail::ViewData::removeFromToolbar (GtkToolItem * ti) override virtual
Request that the given tool item be removed from the toolbar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 { parent()->removeFromToolbar(ti); }
removeSideWidget()
void Detail::ViewData::removeSideWidget (GtkWidget * w) override virtual
Request that the given widget be removed from the sidebar.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements ViewInterface.
 { parent()->removeSideWidget(w); }
setStatusMessage()
void Detail::ViewData::setStatusMessage (const std::string &) override virtual
Sets the status message in the status bar of the application.
Implements ViewInterface.
 { parent()->setStatusMessage(string); }
Member Data Documentation
image
Scroom::Bitmap::BitmapSurface::Ptr Detail::ViewData::image
Referenced by invalidate().
presentationArea
Scroom::Utils::Rectangle<double> Detail::ViewData::presentationArea
weakParent
ViewInterface::WeakPtr Detail::ViewData::weakParent
Referenced by parent().
zoom
int Detail::ViewData::zoom {0}
The documentation for this class was generated from the following files:
libs/scroom/inc/scroom/transformpresentation.hh
libs/scroom/src/transformpresentation.cc