Scroom: Operations8bpp Class Reference
Operations8bpp Class Reference
#include <layeroperations.hh>
Public Member Functions
Operations8bpp (ColormapProvider::Ptr colormapProvider)
int getBpp () override
Scroom::Utils::Stuff cache (const ConstTile::Ptr &tile) override
void reduce (Tile::Ptr target, ConstTile::Ptr source, int x, int y) override
void draw (cairo_t *cr, const ConstTile::Ptr &tile, Scroom::Utils::Rectangle< double > tileArea, Scroom::Utils::Rectangle< double > viewArea, int zoom, Scroom::Utils::Stuff cache) override
Public Member Functions inherited from CommonOperations
void initializeCairo (cairo_t *cr) override
void drawState (cairo_t *cr, TileState s, Scroom::Utils::Rectangle< double > viewArea) override
Scroom::Utils::Stuff cacheZoom (const ConstTile::Ptr &tile, int zoom, Scroom::Utils::Stuff &cache) override
Static Public Member Functions
static Ptr create (ColormapProvider::Ptr colormapProvider)
Static Public Member Functions inherited from CommonOperations
static void drawPixelValue (cairo_t *cr, int x, int y, int size, int value)
static void drawPixelValue (cairo_t *cr, int x, int y, int size, int value, Color const &bgColor)
Private Attributes
ColormapProvider::Ptr colormapProvider
Additional Inherited Members
Public Types inherited from LayerOperations
using Ptr = std::shared_ptr< LayerOperations >
Constructor & Destructor Documentation
Operations8bpp()
Operations8bpp::Operations8bpp (ColormapProvider::Ptr colormapProvider) explicit
   : colormapProvider(std::move(colormapProvider_))
 {
 }
Referenced by create().
Member Function Documentation
cache()
Scroom::Utils::Stuff Operations8bpp::cache (const ConstTile::Ptr &) override virtual
Cache data for use during later cacheZoom() calls.
This function is called for a given tile, and then the results are passed to the cacheZoom() function. Because draw() is called relatively frequently (i.e. when scrolling), it is recommended to do cpu-intensive work in the cache() and cacheZoom() functions, and then re-use the data to make the draw() faster.
The default implementation returns an empty reference, meaning nothing is cached. As a result, the draw() function will receive an empty reference.
Parameters
tile the Tile for which caching is requested
Reimplemented from LayerOperations.
 {
   const int                            stride   = cairo_format_stride_for_width(CAIRO_FORMAT_ARGB32, tile->width);
   std::shared_ptr<unsigned char> const data     = shared_malloc(stride * tile->height);
   Colormap::Ptr const                  colormap = colormapProvider->getColormap();
   const Color&                         c1       = colormap->colors[0];
   const Color&                         c2       = colormap->colors[1];
   unsigned char* row = data.get();
   for(int j = 0; j < tile->height; j++, row += stride)
   {
     const byte* cur = tile->data.get() + j * tile->width;
     auto* pixel = reinterpret_cast<uint32_t*>(row);
     for(int i = 0; i < tile->width; i++)
     {
       *pixel = mix(c2, c1, 1.0 * *cur / 255).getARGB32();
       pixel++;
       ++cur;
     }
   }
   return BitmapSurface::create(tile->width, tile->height, CAIRO_FORMAT_ARGB32, stride, data);
 }
Referenced by draw().
create()
LayerOperations::Ptr Operations8bpp::create (ColormapProvider::Ptr colormapProvider) static
 {
   return Ptr(new Operations8bpp(std::move(colormapProvider)));
 }
Referenced by Scroom::TiledBitmap::GreyscaleBitmap(), setupTest1bpp(), and setupTest8bpp().
draw()
void Operations8bpp::draw (cairo_t * cr, const ConstTile::Ptr & tile, Scroom::Utils::Rectangle< double > tileArea, Scroom::Utils::Rectangle< double > viewArea, int zoom, Scroom::Utils::Stuff cache) override virtual
Draw the given tileArea into the given viewArea at the requested zoom level
Parameters
cr The canvas on which to draw
tile The tile to take data from
tileArea Area of the tile that needs to be drawn
viewArea Area of the canvas that the tile needs to be drawn in
zoom The requested zoom level. One pixel of your presentation should have size 2**zoom when drawn. zoom will be negative for all but the first layer.
cache Depending on whether the cacheZoom() function finished already, this may either be an empty reference, or a reference to the value returned by cacheZoom()
Reimplemented from CommonOperations.
 {
   cairo_save(cr);
   CommonOperations::draw(cr, tile, tileArea, viewArea, zoom, cache);
   cairo_restore(cr);
   // Draw pixelvalues at 32:1 zoom
   if(zoom == 5)
   {
     const int multiplier = 1 << zoom;
     const int stride     = tile->width;
     cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
     cairo_set_font_size(cr, 12.0);
     Colormap::Ptr const colormap = colormapProvider->getColormap();
     const Color&        c1       = colormap->colors[0];
     const Color&        c2       = colormap->colors[1];
     const byte* const   data     = tile->data.get();
     auto tileAreaInt = roundOutward(tileArea).to<int>();
     auto offset      = tileAreaInt.getTopLeft() - tileArea.getTopLeft();
     viewArea += offset * multiplier;
     for(int x = 0; x < tileAreaInt.width(); x++)
     {
       for(int y = 0; y < tileAreaInt.height(); y++)
       {
         const int   value = data[(tileAreaInt.y() + y) * stride + tileAreaInt.x() + x];
         Color const c     = mix(c2, c1, 1.0 * value / 255);
         cairo_save(cr);
         drawPixelValue(cr, viewArea.x() + multiplier * x, viewArea.y() + multiplier * y, multiplier, value, c);
         cairo_restore(cr);
       }
     }
   }
 }
getBpp()
int Operations8bpp::getBpp () override virtual
Return the number of bits per pixel that the layer will use.
This number will be used to compute the amount of memory required to store one tile
Implements LayerOperations.
 { return 8; }
reduce()
void Operations8bpp::reduce (Tile::Ptr target, ConstTile::Ptr source, int x, int y) override virtual
Reduce the source tile by a factor of 8
The target tile will contain data for 8*8 source tiles. Offsets x and y indicate which of those 64 source tiles is currently being processed
Parameters
target Tile that will contain the reduced bitmap
source Tile that is to be reduced
x x-offset (0..7) of the source tile in the target tile
y y-offset (0..7) of the source tile in the target tile
Note
The target tile belongs to a different layer, and hence possibly has a different bpp than the current one, depending on the LayerSpec given to createTiledBitmap()
Implements LayerOperations.
 {
   // Reducing by a factor 8. Source tile is 8bpp. Target tile is 8bpp
   const int   sourceStride = source->width;
   const byte* sourceBase   = source->data.get();
   const int targetStride = target->width;
   byte*     targetBase   = target->data.get() + target->height * y * targetStride / 8 + target->width * x / 8;
   for(int j = 0; j < source->height / 8; j++, targetBase += targetStride, sourceBase += sourceStride * 8)
   {
     // Iterate vertically over target
     const byte* sourcePtr = sourceBase;
     byte*       targetPtr = targetBase;
     for(int i = 0; i < source->width / 8; i++, sourcePtr += 8, targetPtr++)
     {
       // Iterate horizontally over target
       // Goal is to compute a 8-bit grey value from a 8*8 grey image.
       const byte* base = sourcePtr;
       int         sum  = 0;
       for(int k = 0; k < 8; k++, base += sourceStride)
       {
         const byte* current = base;
         for(int l = 0; l < 8; l++, current++)
         {
           sum += *current;
         }
       }
       *targetPtr = sum / 64;
     }
   }
 }
Member Data Documentation
colormapProvider
ColormapProvider::Ptr Operations8bpp::colormapProvider private
Referenced by cache(), create(), and draw().
The documentation for this class was generated from the following files:
libs/tiled-bitmap/inc/scroom/layeroperations.hh
libs/tiled-bitmap/src/layeroperations.cc