Scroom: Scroom::Utils::RecursiveContext Class Reference
Scroom::Utils::RecursiveContext Class Reference
#include <recursive-context.hh>
Public Member Functions
RecursiveContext (std::string name, Context::Ptr first_)
std::string name () const override
void set (std::string name, std::any value) override
const std::any & get (std::string name) const override
std::any try_get (std::string name) const override
void add (Context::ConstPtr child)
Public Member Functions inherited from Interface
Interface ()=default
Interface (const Interface &)=delete
Interface & operator= (const Interface &)=delete
Interface (const Interface &&)=delete
Interface & operator= (const Interface &&)=delete
virtual ~Interface ()=default
Private Attributes
std::string contextName
Context::Ptr first
std::vector< Context::ConstPtr > contexts
Additional Inherited Members
Public Types inherited from Scroom::Utils::Context
using Ptr = std::shared_ptr< Context >
using ConstPtr = std::shared_ptr< const Context >
Constructor & Destructor Documentation
RecursiveContext()
Scroom::Utils::RecursiveContext::RecursiveContext (std::string name, Context::Ptr first_) explicit
     : contextName(std::move(name))
     , first(std::move(first_))
   {
     require(this->first);
     contexts.emplace_back(this->first);
   }
Member Function Documentation
add()
void Scroom::Utils::RecursiveContext::add (Context::ConstPtr child)
   {
     require(child);
     contexts.emplace_back(std::move(child));
   }
Referenced by RecursiveContextFixture::RecursiveContextFixture().
get()
const std::any & Scroom::Utils::RecursiveContext::get (std::string name) const override virtual
Implements Scroom::Utils::Context.
   {
     for(const auto& context: contexts)
     {
       try
       {
         return context->get(name);
       }
       catch(name_not_found&)
       {
         // Try the next one
       }
     }
     throw name_not_found();
   }
name()
std::string Scroom::Utils::RecursiveContext::name () const override virtual
Implements Scroom::Utils::Context.
 { return contextName; }
Referenced by get(), set(), and try_get().
set()
void Scroom::Utils::RecursiveContext::set (std::string name, std::any value) override virtual
Implements Scroom::Utils::Context.
 { first->set(std::move(name), std::move(value)); }
try_get()
std::any Scroom::Utils::RecursiveContext::try_get (std::string name) const override virtual
Implements Scroom::Utils::Context.
   {
     std::any result;
     for(const auto& context: contexts)
     {
       result = context->try_get(name);
       if(result.has_value())
       {
         break;
       }
     }
     return result;
   }
Member Data Documentation
contextName
std::string Scroom::Utils::RecursiveContext::contextName private
Referenced by name().
contexts
std::vector<Context::ConstPtr> Scroom::Utils::RecursiveContext::contexts private
Referenced by add(), get(), RecursiveContext(), and try_get().
first
Context::Ptr Scroom::Utils::RecursiveContext::first private
Referenced by RecursiveContext(), and set().
The documentation for this class was generated from the following files:
libs/util/src/recursive-context.hh
libs/util/src/recursive-context.cc