Scroom: Scroom::Utils::SingleContext Class Reference
Scroom::Utils::SingleContext Class Reference
#include <single-context.hh>
Public Member Functions
SingleContext (std::string name)
std::string name () const override
void set (std::string name, std::any value) override
const std::any & get (std::string name) const override
std::any try_get (std::string name) const override
Public Member Functions inherited from Interface
Interface ()=default
Interface (const Interface &)=delete
Interface & operator= (const Interface &)=delete
Interface (const Interface &&)=delete
Interface & operator= (const Interface &&)=delete
virtual ~Interface ()=default
Private Attributes
std::string contextName
std::map< std::string, std::any > content
Additional Inherited Members
Public Types inherited from Scroom::Utils::Context
using Ptr = std::shared_ptr< Context >
using ConstPtr = std::shared_ptr< const Context >
Constructor & Destructor Documentation
SingleContext()
Scroom::Utils::SingleContext::SingleContext (std::string name) explicit
     : contextName(std::move(name))
   {
   }
Member Function Documentation
get()
const std::any & Scroom::Utils::SingleContext::get (std::string name) const override virtual
Implements Scroom::Utils::Context.
   {
     auto item = content.find(name);
     if(item == content.end())
     {
       throw name_not_found();
     }
     return item->second;
   }
name()
std::string Scroom::Utils::SingleContext::name () const override virtual
Implements Scroom::Utils::Context.
 { return contextName; }
Referenced by get(), set(), and try_get().
set()
void Scroom::Utils::SingleContext::set (std::string name, std::any value) override virtual
Implements Scroom::Utils::Context.
   {
     auto [it, added] = content.insert({std::move(name), std::move(value)});
     if(!added)
     {
       throw name_exists();
     }
   }
try_get()
std::any Scroom::Utils::SingleContext::try_get (std::string name) const override virtual
Implements Scroom::Utils::Context.
   {
     auto item = content.find(name);
     if(item == content.end())
     {
       return {};
     }
     return item->second;
   }
Member Data Documentation
content
std::map<std::string, std::any> Scroom::Utils::SingleContext::content private
Referenced by get(), set(), and try_get().
contextName
std::string Scroom::Utils::SingleContext::contextName private
Referenced by name().
The documentation for this class was generated from the following files:
libs/util/src/single-context.hh
libs/util/src/single-context.cc