Scroom: libs/util/test/gtkhelper-tests.cc File Reference
gtkhelper-tests.cc File Reference
#include <memory>
#include <boost/test/unit_test.hpp>
#include <gtk/gtk.h>
#include <scroom/gtk-helpers.hh>
#include <scroom/gtk-test-helpers.hh>
Classes
class anonymous_namespace{gtkhelper-tests.cc}::B
Namespaces
anonymous_namespace{gtkhelper-tests.cc}
Functions
static void b (const B::Ptr &)
BOOST_AUTO_TEST_CASE (function_returning_bool)
BOOST_AUTO_TEST_CASE (on_ui_thread_test)
Function Documentation
b()
static void b (const B::Ptr &) static
 {}
Referenced by Scroom::Utils::areEqual(), BOOST_AUTO_TEST_CASE(), doubleFromByte(), Scroom::Tiff::getColorMap(), intersectsImpliesNonEmptyIntersection(), mix(), operator==(), points_are_close(), rects_are_close(), MonochromeColormapHelper::regenerateColormap(), and Scroom::TiledBitmap::anonymous_namespace{layerspecforbitmap.cc}::to_string().
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (function_returning_bool)
 {
   GSourceFunc f    = nullptr;
   gpointer    data = nullptr;
   B::WeakPtr  wb;
   {
     B::Ptr const sb                          = B::create();
     wb                                       = sb;
     std::pair<GSourceFunc, gpointer> const w = wrap([sb] { return b(sb); });
     f                                        = w.first;
     data                                     = w.second;
   }
   BOOST_CHECK(wb.lock());
   bool const result = (*f)(data);
   BOOST_CHECK_EQUAL(false, result);
   BOOST_CHECK(!wb.lock());
 }
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (on_ui_thread_test)
 {
   Scroom::GtkTestHelpers::GtkMainLoop const mainLoop;
   BOOST_REQUIRE(!on_ui_thread());
   sync_on_ui_thread([] { BOOST_CHECK(on_ui_thread()); });
 }