Scroom: libs/threadpool/test/helpers.hh File Reference
helpers.hh File Reference
#include <memory>
#include <boost/function.hpp>
#include <scroom/semaphore.hh>
#include <scroom/threadpool.hh>
Functions
boost::function< void()> pass (Semaphore *s)
boost::function< void()> clear (Semaphore *s)
boost::function< void()> destroy (std::shared_ptr< void > &p)
template<typename T >
boost::function< void()> destroy (std::shared_ptr< T > &p)
Function Documentation
clear()
boost::function<void()> clear (Semaphore * s)
 {
   return [s] { s->V(); };
 }
Referenced by BOOST_AUTO_TEST_CASE(), and has_at_least_n_threads().
destroy() [1/2]
template<typename T > boost::function<void()> destroy (std::shared_ptr< T > & p)
 {
   std::shared_ptr<void> pv = std::move(p);
   return destroy(pv);
 }
destroy() [2/2]
boost::function<void()> destroy (std::shared_ptr< void > & p)
 {
   return [p = std::move(p)]() mutable { p.reset(); };
 }
Referenced by BOOST_AUTO_TEST_CASE(), and destroy().
pass()
boost::function<void()> pass (Semaphore * s)
 {
   return [s] { s->P(); };
 }
Referenced by BOOST_AUTO_TEST_CASE(), and has_at_least_n_threads().