Scroom: anonymous_namespace{view.cc} Namespace Reference
anonymous_namespace{view.cc} Namespace Reference
Helpers.
Functions
Scroom::Utils::Point< double > eventToPoint (GdkEventButton *event)
Scroom::Utils::Point< double > eventToPoint (GdkEventMotion *event)
void on_newWindow_activate (GtkMenuItem *, gpointer user_data)
Detailed Description
Helpers.
Function Documentation
eventToPoint() [1/2]
Scroom::Utils::Point<double> anonymous_namespace{view.cc}::eventToPoint (GdkEventButton * event)
 { return {event->x, event->y}; }
eventToPoint() [2/2]
Scroom::Utils::Point<double> anonymous_namespace{view.cc}::eventToPoint (GdkEventMotion * event)
 { return {event->x, event->y}; }
Referenced by View::on_buttonPress(), View::on_buttonRelease(), and View::on_motion_notify().
on_newWindow_activate()
void anonymous_namespace{view.cc}::on_newWindow_activate (GtkMenuItem * , gpointer user_data)
   {
     PresentationInterface::WeakPtr const& wp = *static_cast<PresentationInterface::WeakPtr*>(user_data); // Yuk!
     PresentationInterface::Ptr const      p  = wp.lock();
     if(p)
     {
       find_or_create_scroom(p);
     }
   }
Referenced by View::updateNewWindowMenu().