Scroom: Scroom::GtkHelpers Namespace Reference
Scroom::GtkHelpers Namespace Reference
Namespaces
Detail
Functions
template<typename T >
std::pair< GSourceFunc, gpointer > wrap (T f)
bool on_ui_thread ()
template<typename T >
void async_on_ui_thread (T f)
template<typename T >
void async_on_ui_thread_and_wait (T f)
template<typename T >
void sync_on_ui_thread (T f)
cairo_rectangle_int_t createCairoIntRectangle (int x, int y, int width, int height)
GtkWindow * get_parent_window (GtkWidget *widget)
Function Documentation
async_on_ui_thread()
template<typename T > void Scroom::GtkHelpers::async_on_ui_thread (T f)
   {
     const auto& [function, data] = wrap(std::move(f));
     gdk_threads_add_idle(function, data);
   }
Referenced by async_on_ui_thread_and_wait(), TiledBitmapViewData::tileLoaded(), and Scroom::GtkTestHelpers::GtkMainLoop::~GtkMainLoop().
async_on_ui_thread_and_wait()
template<typename T > void Scroom::GtkHelpers::async_on_ui_thread_and_wait (T f)
   {
     require(!on_ui_thread());
     std::packaged_task<void(void)> t(f);
     std::future<void> const        future = t.get_future();
     async_on_ui_thread(std::move(t));
     future.wait();
   }
Referenced by sync_on_ui_thread().
createCairoIntRectangle()
cairo_rectangle_int_t Scroom::GtkHelpers::createCairoIntRectangle (int x, int y, int width, int height) inline
   {
     cairo_rectangle_int_t rect;
     rect.x      = x;
     rect.y      = y;
     rect.width  = width;
     rect.height = height;
     return rect;
   }
Referenced by BOOST_AUTO_TEST_CASE(), and Scroom::Utils::Rectangle< int >::toGdkRectangle().
get_parent_window()
GtkWindow * Scroom::GtkHelpers::get_parent_window (GtkWidget * widget)
   {
     auto* topLevel = gtk_widget_get_toplevel(widget);
     if(GTK_IS_WINDOW(topLevel))
     {
       return GTK_WINDOW(topLevel);
     }
     return nullptr;
   }
Referenced by on_image_properties_activate().
on_ui_thread()
bool Scroom::GtkHelpers::on_ui_thread ()
 { return g_main_context_is_owner(g_main_context_default()); }
Referenced by async_on_ui_thread_and_wait(), BOOST_AUTO_TEST_CASE(), and sync_on_ui_thread().
sync_on_ui_thread()
template<typename T > void Scroom::GtkHelpers::sync_on_ui_thread (T f)
   {
     if(on_ui_thread())
     {
       f();
     }
     else
     {
       async_on_ui_thread_and_wait(std::move(f));
     }
   }
Referenced by View::addToolButton(), BOOST_AUTO_TEST_CASE(), PipetteHandler::computeValues(), PipetteHandler::displayValues(), invalidate_view(), Scroom::TiledBitmap::scheduleLoadingBitmap(), ProgressBarManager::setWorking(), TiledBitmap::tileFinished(), and Metadata::viewAdded().
wrap()
template<typename T > std::pair<GSourceFunc, gpointer> Scroom::GtkHelpers::wrap (T f)
   {
     return std::make_pair<GSourceFunc, gpointer>(Detail::gtkWrapper<T>, new T(std::move(f)));
   }
Referenced by async_on_ui_thread(), and BOOST_AUTO_TEST_CASE().