Scroom: Scroom::Utils Namespace Reference
Scroom::Utils Namespace Reference
Namespaces
Detail
Classes
class Base
class Context
class Count
class Counted
class Counter
class DefaultTweakPresentationPosition
class DefaultTweakSelection
class ITweakPositionTextBox
class ITweakPresentationPosition
class ITweakRulers
class ITweakSelection
class Observable
class on_scope_exit
class optional_cleanup
class ParentContext
class Point
class ProgressInterfaceBroadcaster
class ProgressInterfaceFromProgressStateInterface
class ProgressInterfaceFromProgressStateInterfaceForwarder
class ProgressInterfaceMultiplexer
class ProgressStateInterface
class ProgressStateInterfaceFromProgressInterface
class ProgressStateInterfaceFromProgressInterfaceForwarder
class Rectangle
class RecursiveContext
class Segment
class SingleContext
class TweakPositionTextBox
class TweakRulers
Typedefs
using Stuff = std::shared_ptr< void >
using StuffWeak = std::weak_ptr< void >
using StuffList = std::list< Stuff >
template<typename K , typename V >
using WeakKeyMap = std::map< K, V, std::owner_less< K > >
template<typename K >
using WeakKeySet = std::set< K, std::owner_less< K > >
Functions
ITweakPresentationPosition::Ptr getDefaultTweakPresentationPosition ()
ITweakRulers::Ptr getDefaultTweakRulers ()
ITweakSelection::Ptr getDefaultTweakSelection ()
ITweakPositionTextBox::Ptr getDefaultTweakPositionTextBox ()
template<typename T >
T get (const Context::ConstPtr &context, std::string name)
template<typename T >
T get (const Context::ConstPtr &context)
template<typename T , typename Callable >
auto get_or (const Context::ConstPtr &context, std::string name, Callable default_value) -> std::enable_if_t< std::is_same_v< T, std::remove_reference_t< decltype(default_value())>>, T >
template<typename T , typename Callable >
auto get_or (const Context::ConstPtr &context, Callable default_value) -> std::enable_if_t< std::is_same_v< T, std::remove_reference_t< decltype(default_value())>>, T >
template<typename T >
T get_or (const Context::ConstPtr &context, std::string name, T default_value)
template<typename T >
T get_or (const Context::ConstPtr &context, T default_value)
template<typename T >
void set (const Context::Ptr &context, std::string name, T value)
template<typename T >
void set (const Context::Ptr &context, T value)
template<typename Callable >
void setFactory (const Context::Ptr &context, std::string name, Callable value)
template<typename Callable >
void setFactory (const Context::Ptr &context, Callable value)
template<typename T >
bool isZero (T v)
template<>
bool isZero< int > (int v)
template<>
bool isZero< double > (double v)
template<typename T >
bool areEqual (T a, T b)
template<typename T >
Segment< T > make_segment (T start, T size)
template<typename T >
Segment< T > make_segment_from_start_end (T start, T end)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Segment< T > &s)
Segment< double > roundOutward (Segment< double > s)
template<typename T >
T center (Segment< T > s)
template<typename T >
Point< T > make_point (T x, T y)
template<typename T >
Point< T > make_point (T c)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Point< T > &p)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator- (Point< T > left, Point< U > right)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator+ (Point< T > left, Point< U > right)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator* (Point< T > left, Point< U > right)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator/ (Point< T > left, Point< U > right)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator/ (T left, Point< U > right)
template<typename T , typename U >
Point< typename std::common_type< T, U >::type > operator/ (Point< T > left, U right)
template<typename T >
Point< T > rounded_divide_by (Point< T > value, T factor)
template<typename T >
Point< T > ceiled_divide_by (Point< T > value, T factor)
template<typename T >
Point< T > floored_divide_by (Point< T > value, T factor)
template<typename T >
Point< T > rounded_divide_by (Point< T > value, Point< T > factor)
template<typename T >
Point< T > ceiled_divide_by (Point< T > value, Point< T > factor)
template<typename T >
Point< T > floored_divide_by (Point< T > value, Point< T > factor)
template<typename T >
Point< T > ceil (Point< T > p)
template<typename T >
Rectangle< T > make_rect (T x, T y, T width, T height)
template<typename T >
Rectangle< T > make_rect (Point< T > position, Point< T > size)
template<typename T >
Rectangle< T > make_rect_from_start_end (Point< T > start, Point< T > end)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Rectangle< T > &r)
std::ostream & operator<< (std::ostream &os, const cairo_rectangle_int_t &r)
template<typename T , typename U >
Rectangle< typename std::common_type< T, U >::type > operator* (Rectangle< T > left, U right)
template<typename T , typename U >
Rectangle< typename std::common_type< T, U >::type > operator* (T left, Rectangle< U > right)
Rectangle< double > operator* (cairo_rectangle_int_t const &r, Point< double > const &p)
Rectangle< double > operator* (Point< double > const &p, cairo_rectangle_int_t const &r)
template<typename T , typename U >
Rectangle< typename std::common_type< T, U >::type > operator- (Rectangle< T > left, Point< U > right)
Rectangle< double > roundOutward (Rectangle< double > r)
Rectangle< double > roundCorners (Rectangle< double > r)
template<typename T >
Point< T > center (Rectangle< T > r)
Stuff Empty ()
template<typename F >
std::shared_ptr< void > on_destruction (F f)
std::shared_ptr< unsigned char > shared_malloc (size_t size)
void dumpCounts ()
Variables
constexpr double epsilon = 1e-6
Typedef Documentation
Stuff
using Scroom::Utils::Stuff = typedef std::shared_ptr<void>
Stuff is a pointer to some private data.
StuffList
using Scroom::Utils::StuffList = typedef std::list<Stuff>
StuffWeak
using Scroom::Utils::StuffWeak = typedef std::weak_ptr<void>
WeakKeyMap
template<typename K , typename V > using Scroom::Utils::WeakKeyMap = typedef std::map<K, V, std::owner_less<K> >
WeakKeySet
template<typename K > using Scroom::Utils::WeakKeySet = typedef std::set<K, std::owner_less<K> >
Function Documentation
areEqual()
template<typename T > bool Scroom::Utils::areEqual (T a, T b)
   {
     return isZero(a - b);
   }
Referenced by Scroom::Utils::Segment< value_type >::operator==().
ceil()
template<typename T > Point<T> Scroom::Utils::ceil (Point< T > p)
   {
     using std::ceil;
     return {ceil(p.x), ceil(p.y)};
   }
Referenced by ceiled_divide_by(), createProvider(), TransformPresentation::redraw(), and testCorrectIntervalForMinWidth().
ceiled_divide_by() [1/2]
template<typename T > Point<T> Scroom::Utils::ceiled_divide_by (Point< T > value, Point< T > factor)
   {
     using ::ceiled_divide_by;
     return {ceiled_divide_by(value.x, factor.x), ceiled_divide_by(value.y, factor.y)};
   }
Referenced by ceiled_divide_by().
ceiled_divide_by() [2/2]
template<typename T > Point<T> Scroom::Utils::ceiled_divide_by (Point< T > value, T factor)
   {
     using ::ceiled_divide_by;
     return {ceiled_divide_by(value.x, factor), ceiled_divide_by(value.y, factor)};
   }
Referenced by ceiled_divide_by().
center() [1/2]
template<typename T > Point<T> Scroom::Utils::center (Rectangle< T > r) inline
   {
     return make_point(center(r.getHorizontally()), center(r.getVertically()));
   }
center() [2/2]
template<typename T > T Scroom::Utils::center (Segment< T > s)
   {
     return s.getStart() + s.getSize() / 2;
   }
Referenced by center(), Scroom::Utils::TweakPositionTextBox::display(), TweakPositionTextBox::display(), and find_closest_corner().
dumpCounts()
void Scroom::Utils::dumpCounts ()
 { Counter::instance()->dump(); }
Empty()
Stuff Scroom::Utils::Empty () inline
 { return {}; }
Referenced by Tiff::open().
floored_divide_by() [1/2]
template<typename T > Point<T> Scroom::Utils::floored_divide_by (Point< T > value, Point< T > factor)
   {
     using ::floored_divide_by;
     return {floored_divide_by(value.x, factor.x), floored_divide_by(value.y, factor.y)};
   }
Referenced by floored_divide_by().
floored_divide_by() [2/2]
template<typename T > Point<T> Scroom::Utils::floored_divide_by (Point< T > value, T factor)
   {
     using ::floored_divide_by;
     return {floored_divide_by(value.x, factor), floored_divide_by(value.y, factor)};
   }
Referenced by floored_divide_by().
get() [1/2]
template<typename T > T Scroom::Utils::get (const Context::ConstPtr & context)
   {
     return get<T>(context, typeid(T).name());
   }
get() [2/2]
template<typename T > T Scroom::Utils::get (const Context::ConstPtr & context, std::string name)
   {
     const std::any& result = context->get(std::move(name));
     try
     {
       return std::any_cast<T>(result);
     }
     catch(std::bad_any_cast&)
     {
       using F = std::function<T()>;
       return std::any_cast<F>(result)();
     }
   }
Referenced by Scroom::Bookkeeping::Token::add(), Scroom::Bookkeeping::Token::merge(), and Scroom::Bookkeeping::Token::Token().
get_or() [1/4]
template<typename T , typename Callable > auto Scroom::Utils::get_or (const Context::ConstPtr & context, Callable default_value) -> std::enable_if_t<std::is_same_v<T, std::remove_reference_t<decltype(default_value())>>, T>
   {
     return get_or<T>(context, typeid(T).name(), default_value);
   }
get_or() [2/4]
template<typename T , typename Callable > auto Scroom::Utils::get_or (const Context::ConstPtr & context, std::string name, Callable default_value) -> std::enable_if_t<std::is_same_v<T, std::remove_reference_t<decltype(default_value())>>, T>
   {
     try
     {
       return get<T>(context, std::move(name));
     }
     catch(...)
     {
       return default_value();
     }
   }
get_or() [3/4]
template<typename T > T Scroom::Utils::get_or (const Context::ConstPtr & context, std::string name, T default_value)
   {
     return get_or<T>(context, std::move(name), [default_value] { return default_value; });
   }
get_or() [4/4]
template<typename T > T Scroom::Utils::get_or (const Context::ConstPtr & context, T default_value)
   {
     return get_or<T>(context, typeid(T).name(), [default_value] { return default_value; });
   }
getDefaultTweakPositionTextBox()
ITweakPositionTextBox::Ptr Scroom::Utils::getDefaultTweakPositionTextBox ()
 { return ITweakPositionTextBox::Ptr(); }
getDefaultTweakPresentationPosition()
ITweakPresentationPosition::Ptr Scroom::Utils::getDefaultTweakPresentationPosition ()
   {
     return std::make_shared<DefaultTweakPresentationPosition>();
   }
getDefaultTweakRulers()
ITweakRulers::Ptr Scroom::Utils::getDefaultTweakRulers ()
 { return std::make_shared<TweakRulers>(); }
getDefaultTweakSelection()
ITweakSelection::Ptr Scroom::Utils::getDefaultTweakSelection ()
 { return std::make_shared<DefaultTweakSelection>(); }
isZero()
template<typename T > bool Scroom::Utils::isZero (T v)
Referenced by areEqual(), and Scroom::Utils::Segment< value_type >::isEmpty().
isZero< double >()
template<> bool Scroom::Utils::isZero< double > (double v) inline
   {
     return std::abs(v) < epsilon;
   }
isZero< int >()
template<> bool Scroom::Utils::isZero< int > (int v) inline
   {
     return v == 0;
   }
make_point() [1/2]
template<typename T > Point<T> Scroom::Utils::make_point (T c)
   {
     return Point<T>(c, c);
   }
make_point() [2/2]
template<typename T > Point<T> Scroom::Utils::make_point (T x, T y)
   {
     return Point<T>(x, y);
   }
Referenced by BOOST_AUTO_TEST_CASE(), center(), RectangleHorizontalTestScaffold::contains(), RectangleVerticalTestScaffold::contains(), PresentationInterface::getAspectRatio(), RectangleHorizontalTestScaffold::moveTo(), RectangleVerticalTestScaffold::moveTo(), operator/(), roundCorners(), and TransformationData::setAspectRatio().
make_rect() [1/2]
template<typename T > Rectangle<T> Scroom::Utils::make_rect (Point< T > position, Point< T > size)
   {
     return Rectangle<T>(position.x, position.y, size.x, size.y);
   }
make_rect() [2/2]
template<typename T > Rectangle<T> Scroom::Utils::make_rect (T x, T y, T width, T height)
   {
     return Rectangle<T>(x, y, width, height);
   }
Referenced by BOOST_AUTO_TEST_CASE(), View::redraw(), TEST(), Scroom::Utils::TweakRulers::tweakRulers(), and TweakRulers::tweakRulers().
make_rect_from_start_end()
template<typename T > Rectangle<T> Scroom::Utils::make_rect_from_start_end (Point< T > start, Point< T > end)
   {
     return Rectangle<T>(make_segment_from_start_end(start.x, end.x), make_segment_from_start_end(start.y, end.y));
   }
Referenced by PipetteHandler::onSelectionEnd(), roundCorners(), and toRectangle().
make_segment()
template<typename T > Segment<T> Scroom::Utils::make_segment (T start, T size)
   {
     return Segment<T>(start, size);
   }
Referenced by BOOST_AUTO_TEST_CASE().
make_segment_from_start_end()
template<typename T > Segment<T> Scroom::Utils::make_segment_from_start_end (T start, T end)
   {
     return Segment<T>(start, end - start);
   }
Referenced by make_rect_from_start_end(), and roundOutward().
on_destruction()
template<typename F > std::shared_ptr<void> Scroom::Utils::on_destruction (F f)
   {
     return std::make_shared<on_scope_exit<F>>(std::move(f));
   }
Referenced by BOOST_AUTO_TEST_CASE(), and Scroom::TiledBitmap::scheduleLoadingBitmap().
operator*() [1/5]
Rectangle<double> Scroom::Utils::operator* (cairo_rectangle_int_t const & r, Point< double > const & p) inline
 { return Rectangle<double>(r) * p; }
operator*() [2/5]
Rectangle<double> Scroom::Utils::operator* (Point< double > const & p, cairo_rectangle_int_t const & r) inline
 { return Rectangle<double>(r) * p; }
operator*() [3/5]
template<typename T , typename U > Point<typename std::common_type<T, U>::type> Scroom::Utils::operator* (Point< T > left, Point< U > right)
   {
     using R = typename std::common_type<T, U>::type;
     Point<R> result(left);
     result *= Point<R>(right);
     return result;
   }
operator*() [4/5]
template<typename T , typename U > Rectangle<typename std::common_type<T, U>::type> Scroom::Utils::operator* (Rectangle< T > left, U right)
   {
     Rectangle<typename std::common_type<T, U>::type> result(left);
     result *= static_cast<typename std::common_type<T, U>::type>(right);
     return result;
   }
operator*() [5/5]
template<typename T , typename U > Rectangle<typename std::common_type<T, U>::type> Scroom::Utils::operator* (T left, Rectangle< U > right)
   {
     return right * left;
   }
operator+()
template<typename T , typename U > Point<typename std::common_type<T, U>::type> Scroom::Utils::operator+ (Point< T > left, Point< U > right)
   {
     using R = typename std::common_type<T, U>::type;
     Point<R> result(left);
     result += Point<R>(right);
     return result;
   }
operator-() [1/2]
template<typename T , typename U > Point<typename std::common_type<T, U>::type> Scroom::Utils::operator- (Point< T > left, Point< U > right)
   {
     using R = typename std::common_type<T, U>::type;
     Point<R> result(left);
     result -= Point<R>(right);
     return result;
   }
operator-() [2/2]
template<typename T , typename U > Rectangle<typename std::common_type<T, U>::type> Scroom::Utils::operator- (Rectangle< T > left, Point< U > right)
   {
     using R = typename std::common_type<T, U>::type;
     return Rectangle<R>(left) - Point<R>(right);
   }
operator/() [1/3]
template<typename T , typename U > Point<typename std::common_type<T, U>::type> Scroom::Utils::operator/ (Point< T > left, Point< U > right)
   {
     using R = typename std::common_type<T, U>::type;
     Point<R> result(left);
     result /= Point<R>(right);
     return result;
   }
operator/() [2/3]
template<typename T , typename U > Point<typename std::common_type<T, U>::type> Scroom::Utils::operator/ (Point< T > left, U right)
   {
     return left / make_point(right, right);
   }
operator/() [3/3]
template<typename T , typename U > Point<typename std::common_type<T, U>::type> Scroom::Utils::operator/ (T left, Point< U > right)
   {
     return make_point(left, left) / right;
   }
operator<<() [1/4]
std::ostream& Scroom::Utils::operator<< (std::ostream & os, const cairo_rectangle_int_t & r) inline
 { return os << Rectangle<double>(r); }
operator<<() [2/4]
template<typename T > std::ostream& Scroom::Utils::operator<< (std::ostream & os, const Point< T > & p)
   {
     return os << '(' << p.x << ',' << p.y << ')';
   }
operator<<() [3/4]
template<typename T > std::ostream& Scroom::Utils::operator<< (std::ostream & os, const Rectangle< T > & r)
   {
     os << '<' << r.getLeft() << ',' << r.getTop() << ',' << r.getWidth() << ',' << r.getHeight() << '>';
     return os;
   }
operator<<() [4/4]
template<typename T > std::ostream& Scroom::Utils::operator<< (std::ostream & os, const Segment< T > & s)
   {
     return os << '(' << s.getStart() << ',' << s.getSize() << ')';
   }
roundCorners()
Rectangle<double> Scroom::Utils::roundCorners (Rectangle< double > r) inline
   {
     return make_rect_from_start_end(round_to_multiple_of(r.getTopLeft(), make_point(1.0)),
                                     round_to_multiple_of(r.getBottomRight(), make_point(1.0)));
   }
Referenced by TweakGridSelection::tweakSelection().
rounded_divide_by() [1/2]
template<typename T > Point<T> Scroom::Utils::rounded_divide_by (Point< T > value, Point< T > factor)
   {
     using ::rounded_divide_by;
     return {rounded_divide_by(value.x, factor.x), rounded_divide_by(value.y, factor.y)};
   }
Referenced by rounded_divide_by().
rounded_divide_by() [2/2]
template<typename T > Point<T> Scroom::Utils::rounded_divide_by (Point< T > value, T factor)
   {
     using ::rounded_divide_by;
     return {rounded_divide_by(value.x, factor), rounded_divide_by(value.y, factor)};
   }
Referenced by rounded_divide_by().
roundOutward() [1/2]
Rectangle<double> Scroom::Utils::roundOutward (Rectangle< double > r) inline
   {
     return {
       roundOutward(r.getHorizontally()),
       roundOutward(r.getVertically()),
     };
   }
roundOutward() [2/2]
Segment<double> Scroom::Utils::roundOutward (Segment< double > s) inline
   {
     return make_segment_from_start_end(round_down_to_multiple_of(s.getStart(), 1.0), round_up_to_multiple_of(s.getEnd(), 1.0));
   }
Referenced by PipetteHandler::computeValues(), Operations1bpp::draw(), Operations8bpp::draw(), Operations::draw(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), roundOutward(), and TweakPixelSelection::tweakSelection().
set() [1/2]
template<typename T > void Scroom::Utils::set (const Context::Ptr & context, std::string name, T value)
   {
     context->set(std::move(name), value);
   }
Referenced by BOOST_AUTO_TEST_CASE(), set(), and setFactory().
set() [2/2]
template<typename T > void Scroom::Utils::set (const Context::Ptr & context, T value)
   {
     set(context, typeid(value).name(), std::move(value));
   }
setFactory() [1/2]
template<typename Callable > void Scroom::Utils::setFactory (const Context::Ptr & context, Callable value)
   {
     using T = std::remove_reference_t<decltype(value())>;
     setFactory(context, typeid(T).name(), std::move(value));
   }
setFactory() [2/2]
template<typename Callable > void Scroom::Utils::setFactory (const Context::Ptr & context, std::string name, Callable value)
   {
     using T = std::remove_reference_t<decltype(value())>;
     set(context, std::move(name), std::function<T()>(value));
   }
Referenced by BOOST_AUTO_TEST_CASE(), and setFactory().
shared_malloc()
std::shared_ptr<unsigned char> Scroom::Utils::shared_malloc (size_t size) inline
 { return {static_cast<unsigned char*>(malloc(size)), free}; }
Referenced by OperationsCMYK32::cache(), OperationsCMYK16::cache(), OperationsCMYK8::cache(), and OperationsCMYK4::cache().
Variable Documentation
epsilon
constexpr double Scroom::Utils::epsilon = 1e-6 constexpr
Referenced by isZero< double >().