Scroom: SelectionType Namespace Reference
SelectionType Namespace Reference
Functions
const std::string GRID ("GridSelection")
const std::string PIXEL ("PixelSelection")
const std::string DEFAULT (GRID)
Function Documentation
DEFAULT()
const std::string SelectionType::DEFAULT (GRID)
Referenced by SelectionListener::getSelectionType(), View::on_buttonPress(), View::on_buttonRelease(), and View::on_motion_notify().
GRID()
const std::string SelectionType::GRID ("GridSelection")
Referenced by View::View().
PIXEL()
const std::string SelectionType::PIXEL ("PixelSelection")
Referenced by PipetteHandler::getSelectionType(), and View::View().