Scroom: libs/tiled-bitmap/tools/test-helpers.cc File Reference
test-helpers.cc File Reference
#include "test-helpers.hh"
#include <utility>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include <scroom/colormappable.hh>
#include <scroom/layeroperations.hh>
#include "scroom/cairo-helpers.hh"
Functions
bool quit ()
bool reset ()
bool wait ()
bool setupTest1bpp (int zoom, int width, int height)
bool setupTest2bpp (int zoom, int width, int height)
bool setupTest4bpp (int zoom, int width, int height)
bool setupTest8bpp (int zoom, int width, int height)
bool setupTest8bppColormapped (int zoom, int width, int height)
Variables
int drawingAreaWidth = 0
int drawingAreaHeight = 0
TestData::Ptr testData
Function Documentation
quit()
bool quit ()
 {
   gtk_main_quit();
   return false;
 }
Referenced by init_tests().
reset()
bool reset ()
 {
   testData.reset();
   return false;
 }
Referenced by init_tests().
setupTest1bpp()
bool setupTest1bpp (int zoom, int width, int height)
 {
   Colormap::Ptr const              colormap         = Colormap::createDefault(2);
   DummyColormapProvider::Ptr const colormapProvider = DummyColormapProvider::create(colormap);
   LayerSpec ls;
   ls.push_back(Operations1bpp::create(colormapProvider));
   ls.push_back(Operations8bpp::create(colormapProvider));
   TiledBitmapInterface::Ptr const tbi = createTiledBitmap(width, height, ls);
   SourcePresentation::Ptr const   sp(new Source1Bpp());
   tbi->setSource(sp);
   testData = TestData::create(colormapProvider, ls, tbi, sp, zoom);
   return false;
 }
Referenced by init_tests().
setupTest2bpp()
bool setupTest2bpp (int zoom, int width, int height)
 {
   Colormap::Ptr const              colormap         = Colormap::createDefault(16);
   DummyColormapProvider::Ptr const colormapProvider = DummyColormapProvider::create(colormap);
   LayerSpec ls;
   ls.push_back(Operations::create(colormapProvider, 2));
   ls.push_back(OperationsColormapped::create(colormapProvider, 2));
   TiledBitmapInterface::Ptr const tbi = createTiledBitmap(width, height, ls);
   SourcePresentation::Ptr const   sp(new Source2Bpp());
   tbi->setSource(sp);
   testData = TestData::create(colormapProvider, ls, tbi, sp, zoom);
   return false;
 }
Referenced by init_tests().
setupTest4bpp()
bool setupTest4bpp (int zoom, int width, int height)
 {
   Colormap::Ptr const              colormap         = Colormap::createDefault(16);
   DummyColormapProvider::Ptr const colormapProvider = DummyColormapProvider::create(colormap);
   LayerSpec ls;
   ls.push_back(Operations::create(colormapProvider, 4));
   ls.push_back(OperationsColormapped::create(colormapProvider, 4));
   TiledBitmapInterface::Ptr const tbi = createTiledBitmap(width, height, ls);
   SourcePresentation::Ptr const   sp(new Source4Bpp());
   tbi->setSource(sp);
   testData = TestData::create(colormapProvider, ls, tbi, sp, zoom);
   return false;
 }
Referenced by init_tests().
setupTest8bpp()
bool setupTest8bpp (int zoom, int width, int height)
 {
   Colormap::Ptr const              colormap         = Colormap::createDefault(2);
   DummyColormapProvider::Ptr const colormapProvider = DummyColormapProvider::create(colormap);
   LayerSpec ls;
   ls.push_back(Operations8bpp::create(colormapProvider));
   TiledBitmapInterface::Ptr const tbi = createTiledBitmap(width, height, ls);
   SourcePresentation::Ptr const   sp(new Source8Bpp());
   tbi->setSource(sp);
   testData = TestData::create(colormapProvider, ls, tbi, sp, zoom);
   return false;
 }
Referenced by init_tests().
setupTest8bppColormapped()
bool setupTest8bppColormapped (int zoom, int width, int height)
 {
   Colormap::Ptr const              colormap         = Colormap::createDefault(256);
   DummyColormapProvider::Ptr const colormapProvider = DummyColormapProvider::create(colormap);
   LayerSpec ls;
   ls.push_back(Operations::create(colormapProvider, 8));
   ls.push_back(OperationsColormapped::create(colormapProvider, 8));
   TiledBitmapInterface::Ptr const tbi = createTiledBitmap(width, height, ls);
   SourcePresentation::Ptr const   sp(new Source8Bpp());
   tbi->setSource(sp);
   testData = TestData::create(colormapProvider, ls, tbi, sp, zoom);
   return false;
 }
Referenced by init_tests().
wait()
bool wait ()
 {
   if(testData)
   {
     return testData->wait();
   }
   return false;
 }
Referenced by init_tests().
Variable Documentation
drawingAreaHeight
int drawingAreaHeight = 0
Referenced by logSizes(), on_configure(), and TestData::redraw().
drawingAreaWidth
int drawingAreaWidth = 0
Referenced by logSizes(), on_configure(), and TestData::redraw().
testData
TestData::Ptr testData
Referenced by reset(), setupTest1bpp(), setupTest2bpp(), setupTest4bpp(), setupTest8bpp(), setupTest8bppColormapped(), and wait().