var searchData=
[
  ['sampleiterator_1671',['SampleIterator',['../classScroom_1_1Bitmap_1_1SampleIterator.html',1,'Scroom::Bitmap']]],
  ['scroominterface_1672',['ScroomInterface',['../classScroomInterface.html',1,'']]],
  ['scroominterfaceimpl_1673',['ScroomInterfaceImpl',['../classScroomInterfaceImpl.html',1,'']]],
  ['scroomplugininterface_1674',['ScroomPluginInterface',['../classScroomPluginInterface.html',1,'']]],
  ['segment_1675',['Segment',['../classScroom_1_1Utils_1_1Segment.html',1,'Scroom::Utils']]],
  ['segment_3c_20value_5ftype_20_3e_1676',['Segment&lt; value_type &gt;',['../classScroom_1_1Utils_1_1Segment.html',1,'Scroom::Utils']]],
  ['selection_1677',['Selection',['../structSelection.html',1,'']]],
  ['selectionlistener_1678',['SelectionListener',['../classSelectionListener.html',1,'']]],
  ['semaphore_1679',['Semaphore',['../classScroom_1_1Semaphore.html',1,'Scroom']]],
  ['showmetadatainterface_1680',['ShowMetadataInterface',['../classShowMetadataInterface.html',1,'']]],
  ['sidebarmanager_1681',['SidebarManager',['../classSidebarManager.html',1,'']]],
  ['singlecontext_1682',['SingleContext',['../classScroom_1_1Utils_1_1SingleContext.html',1,'Scroom::Utils']]],
  ['singlecontextfixture_1683',['SingleContextFixture',['../structSingleContextFixture.html',1,'']]],
  ['sizedeterminer_1684',['SizeDeterminer',['../classSizeDeterminer.html',1,'']]],
  ['sleeper_1685',['Sleeper',['../classSleeper.html',1,'']]],
  ['source_1686',['Source',['../classScroom_1_1Tiff_1_1Source.html',1,'Scroom::Tiff']]],
  ['source1bpp_1687',['Source1Bpp',['../classSource1Bpp.html',1,'']]],
  ['source2bpp_1688',['Source2Bpp',['../classSource2Bpp.html',1,'']]],
  ['source4bpp_1689',['Source4Bpp',['../classSource4Bpp.html',1,'']]],
  ['source8bpp_1690',['Source8Bpp',['../classSource8Bpp.html',1,'']]],
  ['sourcepresentation_1691',['SourcePresentation',['../classSourcePresentation.html',1,'']]],
  ['swapbasedblockallocator_1692',['SwapBasedBlockAllocator',['../classScroom_1_1MemoryBlocks_1_1Detail_1_1SwapBasedBlockAllocator.html',1,'Scroom::MemoryBlocks::Detail']]],
  ['swapbasedblockallocatorfactory_1693',['SwapBasedBlockAllocatorFactory',['../classScroom_1_1MemoryBlocks_1_1Detail_1_1SwapBasedBlockAllocatorFactory.html',1,'Scroom::MemoryBlocks::Detail']]]
];
