var searchData=
[
  ['sampleiterator_1655',['SampleIterator',['../classScroom_1_1Bitmap_1_1SampleIterator.html',1,'Scroom::Bitmap']]],
  ['scroominterface_1656',['ScroomInterface',['../classScroomInterface.html',1,'']]],
  ['scroominterfaceimpl_1657',['ScroomInterfaceImpl',['../classScroomInterfaceImpl.html',1,'']]],
  ['scroomplugininterface_1658',['ScroomPluginInterface',['../classScroomPluginInterface.html',1,'']]],
  ['segment_1659',['Segment',['../classScroom_1_1Utils_1_1Segment.html',1,'Scroom::Utils']]],
  ['segment_3c_20value_5ftype_20_3e_1660',['Segment&lt; value_type &gt;',['../classScroom_1_1Utils_1_1Segment.html',1,'Scroom::Utils']]],
  ['selection_1661',['Selection',['../structSelection.html',1,'']]],
  ['selectionlistener_1662',['SelectionListener',['../classSelectionListener.html',1,'']]],
  ['semaphore_1663',['Semaphore',['../classScroom_1_1Semaphore.html',1,'Scroom']]],
  ['showmetadatainterface_1664',['ShowMetadataInterface',['../classShowMetadataInterface.html',1,'']]],
  ['sidebarmanager_1665',['SidebarManager',['../classSidebarManager.html',1,'']]],
  ['singlecontext_1666',['SingleContext',['../classScroom_1_1Utils_1_1SingleContext.html',1,'Scroom::Utils']]],
  ['singlecontextfixture_1667',['SingleContextFixture',['../structSingleContextFixture.html',1,'']]],
  ['sizedeterminer_1668',['SizeDeterminer',['../classSizeDeterminer.html',1,'']]],
  ['sleeper_1669',['Sleeper',['../classSleeper.html',1,'']]],
  ['source_1670',['Source',['../classScroom_1_1Tiff_1_1Source.html',1,'Scroom::Tiff']]],
  ['source1bpp_1671',['Source1Bpp',['../classSource1Bpp.html',1,'']]],
  ['source2bpp_1672',['Source2Bpp',['../classSource2Bpp.html',1,'']]],
  ['source4bpp_1673',['Source4Bpp',['../classSource4Bpp.html',1,'']]],
  ['source8bpp_1674',['Source8Bpp',['../classSource8Bpp.html',1,'']]],
  ['sourcepresentation_1675',['SourcePresentation',['../classSourcePresentation.html',1,'']]],
  ['swapbasedblockallocator_1676',['SwapBasedBlockAllocator',['../classScroom_1_1MemoryBlocks_1_1Detail_1_1SwapBasedBlockAllocator.html',1,'Scroom::MemoryBlocks::Detail']]],
  ['swapbasedblockallocatorfactory_1677',['SwapBasedBlockAllocatorFactory',['../classScroom_1_1MemoryBlocks_1_1Detail_1_1SwapBasedBlockAllocatorFactory.html',1,'Scroom::MemoryBlocks::Detail']]]
];
