var searchData=
[
  ['anonymous_5fnamespace_7blayerspecforbitmap_2ecc_7d_1606',['anonymous_namespace{layerspecforbitmap.cc}',['../namespaceScroom_1_1TiledBitmap_1_1anonymous__namespace_02layerspecforbitmap_8cc_03.html',1,'Scroom::TiledBitmap']]],
  ['anonymous_5fnamespace_7bswapbasedblockallocator_2ecc_7d_1607',['anonymous_namespace{swapbasedblockallocator.cc}',['../namespaceScroom_1_1MemoryBlocks_1_1Detail_1_1anonymous__namespace_02swapbasedblockallocator_8cc_03.html',1,'Scroom::MemoryBlocks::Detail']]],
  ['bitmap_1608',['Bitmap',['../namespaceScroom_1_1Bitmap.html',1,'Scroom']]],
  ['bookkeeping_1609',['Bookkeeping',['../namespaceScroom_1_1Bookkeeping.html',1,'Scroom']]],
  ['colormapimpl_1610',['ColormapImpl',['../namespaceScroom_1_1ColormapImpl.html',1,'Scroom']]],
  ['detail_1611',['Detail',['../namespaceScroom_1_1Bookkeeping_1_1Detail.html',1,'Scroom::Bookkeeping::Detail'],['../namespaceScroom_1_1Detail.html',1,'Scroom::Detail'],['../namespaceScroom_1_1GtkHelpers_1_1Detail.html',1,'Scroom::GtkHelpers::Detail'],['../namespaceScroom_1_1MemoryBlobs_1_1Detail.html',1,'Scroom::MemoryBlobs::Detail'],['../namespaceScroom_1_1MemoryBlocks_1_1Detail.html',1,'Scroom::MemoryBlocks::Detail'],['../namespaceScroom_1_1Utils_1_1Detail.html',1,'Scroom::Utils::Detail']]],
  ['gtkhelpers_1612',['GtkHelpers',['../namespaceScroom_1_1GtkHelpers.html',1,'Scroom']]],
  ['memoryblobs_1613',['MemoryBlobs',['../namespaceScroom_1_1MemoryBlobs.html',1,'Scroom']]],
  ['memoryblocks_1614',['MemoryBlocks',['../namespaceScroom_1_1MemoryBlocks.html',1,'Scroom']]],
  ['page_1615',['Page',['../namespaceScroom_1_1MemoryBlobs_1_1Page.html',1,'Scroom::MemoryBlobs']]],
  ['rawpagedata_1616',['RawPageData',['../namespaceScroom_1_1MemoryBlobs_1_1RawPageData.html',1,'Scroom::MemoryBlobs::RawPageData'],['../namespaceScroom_1_1MemoryBlocks_1_1RawPageData.html',1,'Scroom::MemoryBlocks::RawPageData']]],
  ['scroom_1617',['Scroom',['../namespaceScroom.html',1,'']]],
  ['threadpool_1618',['ThreadPool',['../namespaceScroom_1_1Detail_1_1ThreadPool.html',1,'Scroom::Detail']]],
  ['tiff_1619',['Tiff',['../namespaceScroom_1_1Tiff.html',1,'Scroom']]],
  ['tiledbitmap_1620',['TiledBitmap',['../namespaceScroom_1_1TiledBitmap.html',1,'Scroom']]],
  ['utils_1621',['Utils',['../namespaceScroom_1_1Utils.html',1,'Scroom']]]
];
