#!/bin/bash

set -x
set -e
set -u

# Check for non-blocking output.
# Non-blocking output triggers a "resource temporarily unavailable"
# error when catting doxygen.log. See the upload_doxygen_to_github script.
python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'
# Travis claims to have resolved the issue: https://github.com/travis-ci/travis-ci/issues/4704
### python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
### python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'

autoreconf -i

if [ ! -z "${SOME_DISTS+x}" -a "${CC}" = "gcc" ]
then
    make -k -j2 -f build_scripts/docker/docker.mk TARGETS="${SOME_DISTS}"
elif [ ! -z "${OTHER_DISTS+x}" -a "${CC}" != "gcc" ]
then
    make -k -j2 -f build_scripts/docker/docker.mk TARGETS="${OTHER_DISTS}"
else

    ./configure --enable-doxygen-all-code

    make -k -j4 $(build_scripts/travis/extra-targets) distcheck

    ./build_scripts/travis/upload_doxygen_to_github

    if [ "${TRAVIS_JOB_NUMBER}" = "${TRAVIS_BUILD_NUMBER}.1" ]
    then
        cmake .
        cmake --build . -- -j4
        ctest -j4
    fi
fi
