Scroom: libs/scroom/src/cairo-helpers.cc File Reference
cairo-helpers.cc File Reference
#include <iostream>
#include <boost/assign/list_of.hpp>
#include <scroom/cairo-helpers.hh>
Namespaces
Colors
Functions
const Color Colors::OUT_OF_BOUNDS (0.75, 0.75, 1)
void traceRectangleContour (cairo_t *cr, Rectangle< double > const &viewArea)
void drawRectangleContour (cairo_t *cr, Rectangle< double > const &viewArea)
void drawRectangleContour (cairo_t *cr, Color const &c, Rectangle< double > const &viewArea)
void setClip (cairo_t *cr, double x, double y, double width, double height)
void setClip (cairo_t *cr, const Rectangle< double > &area)
void drawRectangle (cairo_t *cr, Color const &c, Rectangle< double > const &viewArea)
void drawOutOfBoundsWithBackground (cairo_t *cr, Rectangle< double > const &requestedPresentationArea, Rectangle< double > const &actualPresentationArea, double pixelSize)
void drawOutOfBoundsWithBackgroundColor (cairo_t *cr, const Color &background, Rectangle< double > const &requestedPresentationArea, Rectangle< double > const &actualPresentationArea, double pixelSize)
void drawOutOfBoundsWithoutBackground (cairo_t *cr, Rectangle< double > const &requestedPresentationArea, Rectangle< double > const &actualPresentationArea, double pixelSize)
double pixelSizeFromZoom (int zoom)
Variables
const Color Colors::IN_BOUNDS (1, 1, 1)
Function Documentation
drawOutOfBoundsWithBackground()
void drawOutOfBoundsWithBackground (cairo_t * cr, Rectangle< double > const & requestedPresentationArea, Rectangle< double > const & actualPresentationArea, double pixelSize)
Definition at line 74 of file cairo-helpers.cc.
 {
   drawRectangle(cr, Colors::OUT_OF_BOUNDS, pixelSize * (requestedPresentationArea.moveTo(0, 0)));
   drawRectangle(cr, Colors::IN_BOUNDS, pixelSize * (actualPresentationArea - requestedPresentationArea.getTopLeft()));
 }
drawOutOfBoundsWithBackgroundColor()
void drawOutOfBoundsWithBackgroundColor (cairo_t * cr, const Color & background, Rectangle< double > const & requestedPresentationArea, Rectangle< double > const & actualPresentationArea, double pixelSize)
Definition at line 83 of file cairo-helpers.cc.
 {
   drawOutOfBoundsWithoutBackground(cr, requestedPresentationArea, actualPresentationArea, pixelSize);
   drawRectangle(cr, background, pixelSize * (actualPresentationArea - requestedPresentationArea.getTopLeft()));
 }
drawOutOfBoundsWithoutBackground()
void drawOutOfBoundsWithoutBackground (cairo_t * cr, Rectangle< double > const & requestedPresentationArea, Rectangle< double > const & actualPresentationArea, double pixelSize)
Definition at line 93 of file cairo-helpers.cc.
Referenced by drawOutOfBoundsWithBackgroundColor(), and anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::redraw().
 {
   std::list<Rectangle<double>> border =
     boost::assign::list_of(requestedPresentationArea.leftOf(actualPresentationArea.getLeft()))(requestedPresentationArea.rightOf(
       actualPresentationArea.getRight()))(requestedPresentationArea.above(actualPresentationArea.getTop()))(
       requestedPresentationArea.below(actualPresentationArea.getBottom()));
   for(const Rectangle<double>& r: border)
   {
     if(!r.isEmpty())
     {
       drawRectangle(cr, Colors::OUT_OF_BOUNDS, pixelSize * (r - requestedPresentationArea.getTopLeft()));
     }
   }
 }
drawRectangle()
void drawRectangle (cairo_t * cr, Color const & c, Rectangle< double > const & viewArea)
Definition at line 62 of file cairo-helpers.cc.
Referenced by drawOutOfBoundsWithBackground(), drawOutOfBoundsWithBackgroundColor(), drawOutOfBoundsWithoutBackground(), and CommonOperations::drawState().
 {
   cairo_save(cr);
   c.setColor(cr);
   setClip(cr, viewArea);
   cairo_paint(cr);
   cairo_restore(cr);
 }
drawRectangleContour() [1/2]
void drawRectangleContour (cairo_t * cr, Rectangle< double > const & viewArea)
Definition at line 31 of file cairo-helpers.cc.
Referenced by drawRectangleContour(), and TiledBitmap::drawTile().
 {
   traceRectangleContour(cr, viewArea);
   cairo_stroke(cr);
 }
drawRectangleContour() [2/2]
void drawRectangleContour (cairo_t * cr, Color const & c, Rectangle< double > const & viewArea)
Definition at line 37 of file cairo-helpers.cc.
 {
   cairo_save(cr);
   c.setColor(cr);
   drawRectangleContour(cr, viewArea);
   cairo_restore(cr);
 }
pixelSizeFromZoom()
double pixelSizeFromZoom (int zoom)
Definition at line 112 of file cairo-helpers.cc.
Referenced by TiledBitmap::redraw(), and anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::redraw().
 {
   double pixelSize = 1.0;
   if(zoom >= 0)
   {
     pixelSize *= 1 << zoom;
   }
   else
   {
     pixelSize /= 1 << (-zoom);
   }
   return pixelSize;
 }
setClip() [1/2]
void setClip (cairo_t * cr, double x, double y, double width, double height)
Definition at line 47 of file cairo-helpers.cc.
Referenced by CommonOperations::draw(), drawRectangle(), and setClip().
 {
   cairo_move_to(cr, x, y);
   cairo_line_to(cr, x + width, y);
   cairo_line_to(cr, x + width, y + height);
   cairo_line_to(cr, x, y + height);
   cairo_line_to(cr, x, y);
   cairo_clip(cr);
 }
setClip() [2/2]
void setClip (cairo_t * cr, const Rectangle< double > & area)
Definition at line 57 of file cairo-helpers.cc.
 {
   setClip(cr, area.getLeft(), area.getTop(), area.getWidth(), area.getHeight());
 }
traceRectangleContour()
void traceRectangleContour (cairo_t * cr, Rectangle< double > const & viewArea)
Definition at line 22 of file cairo-helpers.cc.
Referenced by drawRectangleContour().
 {
   cairo_move_to(cr, viewArea.x(), viewArea.y());
   cairo_line_to(cr, viewArea.x() + viewArea.width(), viewArea.y());
   cairo_line_to(cr, viewArea.x() + viewArea.width(), viewArea.y() + viewArea.height());
   cairo_line_to(cr, viewArea.x(), viewArea.y() + viewArea.height());
   cairo_line_to(cr, viewArea.x(), viewArea.y());
 }