Scroom: gui/src/callbacks.hh File Reference
callbacks.hh File Reference
#include <list>
#include <map>
#include <string>
#include <gdk/gdk.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <scroom/presentationinterface.hh>
#include <scroom/scroominterface.hh>
#include "view.hh"
Typedefs
using FileNameMap = std::map< std::string, std::list< std::string > >
Functions
void on_scroom_hide (GtkWidget *widget, gpointer user_data)
void on_new_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_open_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_save_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_save_as_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_quit_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_cut_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_copy_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_paste_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_delete_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_fullscreen_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_close_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_about_activate (GtkMenuItem *menuitem, gpointer user_data)
gboolean on_drawingarea_expose_event (GtkWidget *widget, GdkEventExpose *event, gpointer user_data)
gboolean on_drawingarea_configure_event (GtkWidget *widget, GdkEventConfigure *event, gpointer user_data)
gboolean on_idle (gpointer user_data)
void on_done_loading_plugins ()
void on_zoombox_changed (GtkComboBox *widget, gpointer user_data)
void on_scrollbar_value_changed (GtkAdjustment *adjustment, gpointer user_data)
void on_textbox_value_changed (GtkEditable *editable, gpointer user_data)
void on_scroom_bootstrap (const FileNameMap &newFilenames)
void on_scroom_terminating ()
void find_or_create_scroom (PresentationInterface::Ptr presentation)
void create_scroom (PresentationInterface::Ptr presentation)
void on_newPresentationInterfaces_update (const std::map< NewPresentationInterface::Ptr, std::string > &newPresentationInterfaces)
void on_presentation_created (PresentationInterface::Ptr p)
void on_view_created (View::Ptr v)
void on_view_destroyed (View *v)
void on_new_presentationobserver (PresentationObserver::Ptr po)
void on_new_viewobserver (ViewObserver::Ptr v)
void on_presentation_possibly_destroyed ()
Variables
const std::string REGULAR_FILES
Typedef Documentation
FileNameMap
using FileNameMap = std::map<std::string, std::list<std::string> >
Definition at line 21 of file callbacks.hh.
Function Documentation
create_scroom()
void create_scroom (PresentationInterface::Ptr presentation)
Definition at line 518 of file callbacks.cc.
Referenced by find_or_create_scroom(), and on_scroom_bootstrap().
 {
   GladeXML* xml = glade_xml_new(xmlFileName.c_str(), "scroom", nullptr);
   if(xml == nullptr)
   {
     printf("Opening xml failed\n");
     exit(-1);
   }
   View::Ptr view = View::create(xml, presentation);
   on_view_created(view);
   GtkWidget* scroom = glade_xml_get_widget(xml, "scroom");
   // GtkWidget* newMenuItem = glade_xml_get_widget(xml, "new");
   GtkWidget*     openMenuItem         = glade_xml_get_widget(xml, "open");
   GtkWidget*     closeMenuItem        = glade_xml_get_widget(xml, "close");
   GtkWidget*     quitMenuItem         = glade_xml_get_widget(xml, "quit");
   GtkWidget*     fullScreenMenuItem   = glade_xml_get_widget(xml, "fullscreen_menu_item");
   GtkWidget*     aboutMenuItem        = glade_xml_get_widget(xml, "about");
   GtkWidget*     drawingArea          = glade_xml_get_widget(xml, "drawingarea");
   GtkWidget*     zoomBox              = glade_xml_get_widget(xml, "zoomboxcombo");
   GtkWidget*     vscrollbar           = glade_xml_get_widget(xml, "vscrollbar");
   GtkWidget*     hscrollbar           = glade_xml_get_widget(xml, "hscrollbar");
   GtkAdjustment* vscrollbaradjustment = gtk_range_get_adjustment(GTK_RANGE(vscrollbar));
   GtkAdjustment* hscrollbaradjustment = gtk_range_get_adjustment(GTK_RANGE(hscrollbar));
   GtkEditable*   xTextBox             = GTK_EDITABLE(glade_xml_get_widget(xml, "x_textbox"));
   GtkEditable*   yTextBox             = GTK_EDITABLE(glade_xml_get_widget(xml, "y_textbox"));
   g_signal_connect(static_cast<gpointer>(scroom), "hide", G_CALLBACK(on_scroom_hide), view.get());
   g_signal_connect(static_cast<gpointer>(closeMenuItem), "activate", G_CALLBACK(on_close_activate), view.get());
   g_signal_connect(static_cast<gpointer>(quitMenuItem), "activate", G_CALLBACK(on_quit_activate), view.get());
   g_signal_connect(static_cast<gpointer>(openMenuItem), "activate", G_CALLBACK(on_open_activate), scroom);
   g_signal_connect(static_cast<gpointer>(fullScreenMenuItem), "activate", G_CALLBACK(on_fullscreen_activate), view.get());
   g_signal_connect(static_cast<gpointer>(zoomBox), "changed", G_CALLBACK(on_zoombox_changed), view.get());
   g_signal_connect(
     static_cast<gpointer>(vscrollbaradjustment), "value-changed", G_CALLBACK(on_scrollbar_value_changed), view.get());
   g_signal_connect(
     static_cast<gpointer>(hscrollbaradjustment), "value-changed", G_CALLBACK(on_scrollbar_value_changed), view.get());
   g_signal_connect(static_cast<gpointer>(xTextBox), "changed", G_CALLBACK(on_textbox_value_changed), view.get());
   g_signal_connect(static_cast<gpointer>(yTextBox), "changed", G_CALLBACK(on_textbox_value_changed), view.get());
   // g_signal_connect ((gpointer) cut, "activate",
   //                   G_CALLBACK (on_cut_activate),
   //                   view.get());
   // g_signal_connect ((gpointer) copy, "activate",
   //                   G_CALLBACK (on_copy_activate),
   //                   view.get());
   // g_signal_connect ((gpointer) paste, "activate",
   //                   G_CALLBACK (on_paste_activate),
   //                   view.get());
   // g_signal_connect ((gpointer) delete, "activate",
   //                   G_CALLBACK (on_delete_activate),
   //                   view.get());
   g_signal_connect(static_cast<gpointer>(aboutMenuItem), "activate", G_CALLBACK(on_about_activate), view.get());
   g_signal_connect(static_cast<gpointer>(drawingArea), "expose_event", G_CALLBACK(on_drawingarea_expose_event), view.get());
   g_signal_connect(static_cast<gpointer>(drawingArea), "configure_event", G_CALLBACK(on_drawingarea_configure_event), view.get());
   g_signal_connect(static_cast<gpointer>(drawingArea), "button-press-event", G_CALLBACK(on_button_press_event), view.get());
   g_signal_connect(static_cast<gpointer>(drawingArea), "button-release-event", G_CALLBACK(on_button_release_event), view.get());
   g_signal_connect(static_cast<gpointer>(drawingArea), "scroll-event", G_CALLBACK(on_scroll_event), view.get());
   g_signal_connect(static_cast<gpointer>(drawingArea), "motion-notify-event", G_CALLBACK(on_motion_notify_event), view.get());
   char           uriList[] = "text/uri-list";
   GtkTargetEntry targets[] = {{uriList, 0, 0}};
   gtk_drag_dest_set(
     scroom, GTK_DEST_DEFAULT_ALL, targets, 1, static_cast<GdkDragAction>(GDK_ACTION_COPY | GDK_ACTION_MOVE | GDK_ACTION_LINK));
   g_signal_connect(static_cast<gpointer>(scroom), "drag_data_received", G_CALLBACK(onDragDataReceived), NULL);
 }
find_or_create_scroom()
void find_or_create_scroom (PresentationInterface::Ptr presentation)
Definition at line 470 of file callbacks.cc.
Referenced by create(), load(), on_done_loading_plugins(), on_newWindow_activate(), and ScroomInterfaceImpl::showPresentation().
 {
   for(const Views::value_type& p: views)
   {
     View::Ptr view = p.first;
     if(!view->hasPresentation())
     {
       view->setPresentation(presentation);
       return;
     }
   }
   create_scroom(presentation);
 }
on_about_activate()
void on_about_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 236 of file callbacks.cc.
Referenced by create_scroom().
 {
   // GtkWidget* aboutdialog;
   // aboutdialog = create_aboutdialog ();
   gtk_dialog_run(GTK_DIALOG(aboutDialog));
   gtk_widget_hide(aboutDialog);
   // gtk_widget_destroy (aboutdialog);
 }
on_close_activate()
void on_close_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 229 of file callbacks.cc.
Referenced by create_scroom().
 {
   View* view = static_cast<View*>(user_data);
   view->hide();
 }
on_copy_activate()
void on_copy_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 207 of file callbacks.cc.
 {}
on_cut_activate()
void on_cut_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 205 of file callbacks.cc.
 {}
on_delete_activate()
void on_delete_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 211 of file callbacks.cc.
 {}
on_done_loading_plugins()
void on_done_loading_plugins ()
Definition at line 277 of file callbacks.cc.
Referenced by PluginManager::doWork().
 {
   if(!filenames.empty())
   {
     {
       std::list<std::string>& fn = filenames[REGULAR_FILES];
       while(!fn.empty())
       {
         std::string& file = fn.front();
         try
         {
           load(file);
         }
         catch(std::exception& ex)
         {
           printf("ERROR: %s\n", ex.what());
           on_presentation_possibly_destroyed();
         }
         gchar* dir    = g_path_get_dirname(file.c_str());
         currentFolder = dir;
         g_free(dir);
         fn.pop_front();
       }
     }
     filenames.erase(REGULAR_FILES);
     PluginManager::Ptr                                       instance               = PluginManager::getInstance();
     std::map<std::string, NewAggregateInterface::Ptr> const& newAggregateInterfaces = instance->getNewAggregateInterfaces();
     for(FileNameMap::value_type const& v: filenames)
     {
       std::string const&            aggregateName = v.first;
       std::list<std::string> const& files         = v.second;
       auto i = newAggregateInterfaces.find(aggregateName);
       if(i != newAggregateInterfaces.end())
       {
         try
         {
           Aggregate::Ptr             aggregate             = i->second->createNew();
           PresentationInterface::Ptr aggregatePresentation = boost::dynamic_pointer_cast<PresentationInterface>(aggregate);
           if(aggregatePresentation)
           {
             for(std::string const& file: files)
             {
               PresentationInterface::Ptr p = loadPresentation(file);
               aggregate->addPresentation(p);
             }
             on_presentation_created(aggregatePresentation);
             find_or_create_scroom(aggregatePresentation);
           }
           else
           {
             printf("ERROR: Don't know how to display a %s\n", aggregateName.c_str());
           }
         }
         catch(std::exception& ex)
         {
           printf("ERROR: While creating %s: %s\n", aggregateName.c_str(), ex.what());
           on_presentation_possibly_destroyed();
         }
       }
       else
       {
         printf("ERROR: Don't know how to create %s\n", aggregateName.c_str());
       }
     }
     if(presentations.empty())
     {
       // Aparently, we couldn't load any of our presentations. Terminate...
       ensure(views.empty());
       gtk_main_quit();
     }
   }
 }
on_drawingarea_configure_event()
gboolean on_drawingarea_configure_event (GtkWidget * widget, GdkEventConfigure * event, gpointer user_data)
Definition at line 257 of file callbacks.cc.
Referenced by create_scroom().
 {
   // printf("configure\n");
   View* view = static_cast<View*>(user_data);
   view->on_configure();
   return FALSE;
 }
on_drawingarea_expose_event()
gboolean on_drawingarea_expose_event (GtkWidget * widget, GdkEventExpose * event, gpointer user_data)
Definition at line 245 of file callbacks.cc.
Referenced by create_scroom().
 {
   // printf("expose\n");
   cairo_t* cr   = gdk_cairo_create(widget->window);
   View*    view = static_cast<View*>(user_data);
   view->redraw(cr);
   cairo_destroy(cr);
   return FALSE;
 }
on_fullscreen_activate()
void on_fullscreen_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 213 of file callbacks.cc.
Referenced by create_scroom().
 {
   View*             view   = static_cast<View*>(user_data);
   GtkCheckMenuItem* cmi    = GTK_CHECK_MENU_ITEM(item);
   gboolean          active = gtk_check_menu_item_get_active(cmi);
   if(active)
   {
     view->setFullScreen();
   }
   else
   {
     view->unsetFullScreen();
   }
 }
on_idle()
gboolean on_idle (gpointer user_data)
Definition at line 265 of file callbacks.cc.
Referenced by PluginManager::addHook(), and anonymous_namespace{progressbarmanager.cc}::ProgressBarPulser::start().
 {
   if(user_data == nullptr)
   {
     return 0;
   }
   else
   {
     return reinterpret_cast<WorkInterface*>(user_data)->doWork();
   }
 }
on_new_activate()
void on_new_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 87 of file callbacks.cc.
Referenced by View::on_newPresentationInterfaces_update().
 {
   auto* newPresentationInterface = static_cast<NewPresentationInterface*>(user_data);
   create(newPresentationInterface);
 }
on_new_presentationobserver()
void on_new_presentationobserver (PresentationObserver::Ptr po)
Definition at line 683 of file callbacks.cc.
 {
   for(auto& presentation: presentations)
   {
     PresentationInterface::Ptr p = presentation.lock();
     if(p)
     {
       po->presentationAdded(p);
     }
   }
 }
on_new_viewobserver()
void on_new_viewobserver (ViewObserver::Ptr v)
Definition at line 695 of file callbacks.cc.
Referenced by PluginManager::registerViewObserver().
 {
   for(Views::value_type& p: views)
   {
     p.second.add(v->viewAdded(p.first));
   }
 }
on_newPresentationInterfaces_update()
void on_newPresentationInterfaces_update (const std::map< NewPresentationInterface::Ptr, std::string > & newPresentationInterfaces)
Definition at line 587 of file callbacks.cc.
Referenced by PluginManager::registerNewPresentationInterface().
 {
   for(const Views::value_type& p: views)
   {
     p.first->on_newPresentationInterfaces_update(newPresentationInterfaces);
   }
 }
on_open_activate()
void on_open_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 111 of file callbacks.cc.
Referenced by create_scroom().
 {
   GtkWidget* dialog;
   auto*      scroom = static_cast<GtkWidget*>(user_data);
   printf("Creating the open dialog\n");
   dialog = gtk_file_chooser_dialog_new("Open File",
                                        GTK_WINDOW(scroom),
                                        GTK_FILE_CHOOSER_ACTION_OPEN,
                                        GTK_STOCK_CANCEL,
                                        GTK_RESPONSE_CANCEL,
                                        GTK_STOCK_OPEN,
                                        GTK_RESPONSE_ACCEPT,
                                        NULL);
   gtk_file_chooser_set_current_folder(GTK_FILE_CHOOSER(dialog), currentFolder.c_str());
   const auto  pm                         = PluginManager::getInstance();
   const auto& openInterfaces             = pm->getOpenInterfaces();
   const auto& openPresentationInterfaces = pm->getOpenPresentationInterfaces();
   // Store all the file filters so that we can create a custom file filter that allows any supported type (by default)
   std::vector<GtkFileFilter*> filters;
   GtkFileFilter*              allSupportedFileTypesFilter = gtk_file_filter_new();
   gtk_file_filter_set_name(allSupportedFileTypesFilter, "Any supported file type");
   // Cannot beforehand determine which data might be needed for the plugins, so we ask GTK to load everything!
   auto filterFlags = static_cast<GtkFileFilterFlags>(GTK_FILE_FILTER_FILENAME | GTK_FILE_FILTER_MIME_TYPE
                                                      | GTK_FILE_FILTER_DISPLAY_NAME | GTK_FILE_FILTER_URI);
   gtk_file_filter_add_custom(allSupportedFileTypesFilter, filterFlags, &combinedFileFilter, &filters, nullptr);
   gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(dialog), allSupportedFileTypesFilter);
   for(auto const& cur: openPresentationInterfaces)
   {
     for(auto const& f: cur.first->getFilters())
     {
       gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(dialog), f);
       filters.push_back(f);
     }
   }
   for(auto const& cur: openInterfaces)
   {
     for(auto const& f: cur.first->getFilters())
     {
       gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(dialog), f);
       filters.push_back(f);
     }
   }
   if(gtk_dialog_run(GTK_DIALOG(dialog)) == GTK_RESPONSE_ACCEPT)
   {
     GFile*            file     = g_file_new_for_path(gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(dialog)));
     GFileInfo*        fileInfo = g_file_query_info(file, "standard::*", G_FILE_QUERY_INFO_NONE, nullptr, nullptr);
     GtkFileFilterInfo filterInfo;
     filterInfo.filename     = gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(dialog));
     filterInfo.mime_type    = g_content_type_get_mime_type(g_file_info_get_content_type(fileInfo));
     filterInfo.display_name = g_file_info_get_display_name(fileInfo);
     filterInfo.contains =
       static_cast<GtkFileFilterFlags>(GTK_FILE_FILTER_FILENAME | GTK_FILE_FILTER_DISPLAY_NAME | GTK_FILE_FILTER_MIME_TYPE);
     printf("Opening file %s\n", filterInfo.filename);
     try
     {
       load(filterInfo);
     }
     catch(std::exception& ex)
     {
       printf("ERROR: %s\n", ex.what());
       on_presentation_possibly_destroyed();
     }
   }
   gchar* cf = gtk_file_chooser_get_current_folder(GTK_FILE_CHOOSER(dialog));
   if(cf)
   {
     currentFolder = cf;
     g_free(cf);
   }
   gtk_widget_destroy(dialog);
 }
on_paste_activate()
void on_paste_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 209 of file callbacks.cc.
 {}
on_presentation_created()
void on_presentation_created (PresentationInterface::Ptr p)
Definition at line 595 of file callbacks.cc.
Referenced by create(), load(), loadPresentation(), ScroomInterfaceImpl::newAggregate(), ScroomInterfaceImpl::newPresentation(), on_done_loading_plugins(), and ScroomInterfaceImpl::showPresentation().
 {
   presentations.emplace_back(presentation);
   for(const Views::value_type& p: views)
   {
     p.first->on_presentation_created(presentation);
   }
   const std::map<PresentationObserver::Ptr, std::string>& presentationObservers =
     PluginManager::getInstance()->getPresentationObservers();
   auto cur = presentationObservers.begin();
   auto end = presentationObservers.end();
   for(; cur != end; cur++)
   {
     cur->first->presentationAdded(presentation);
   }
 }
on_presentation_possibly_destroyed()
void on_presentation_possibly_destroyed ()
Definition at line 639 of file callbacks.cc.
Referenced by on_done_loading_plugins(), on_open_activate(), and on_view_destroyed().
 {
   bool presentationDestroyed = false;
   for(auto cur = presentations.begin(); cur != presentations.end(); cur++)
   {
     PresentationInterface::Ptr p = cur->lock();
     if(!p)
     {
       presentationDestroyed = true;
       auto temp             = cur;
       temp--;
       presentations.erase(cur);
       cur = temp;
     }
   }
   if(presentationDestroyed)
   {
     for(auto const& p: views)
     {
       p.first->on_presentation_destroyed();
     }
     const std::map<PresentationObserver::Ptr, std::string>& presentationObservers =
       PluginManager::getInstance()->getPresentationObservers();
     for(auto const& p: presentationObservers)
     {
       p.first->presentationDeleted();
     }
   }
 }
on_quit_activate()
void on_quit_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 195 of file callbacks.cc.
Referenced by create_scroom().
 {
   Views v(views);
   for(const Views::value_type& p: v)
   {
     p.first->hide();
   }
   gtk_main_quit();
 }
on_save_activate()
void on_save_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 191 of file callbacks.cc.
 {}
on_save_as_activate()
void on_save_as_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 193 of file callbacks.cc.
 {}
on_scrollbar_value_changed()
void on_scrollbar_value_changed (GtkAdjustment * adjustment, gpointer user_data)
Definition at line 369 of file callbacks.cc.
Referenced by create_scroom().
 {
   View* view = static_cast<View*>(user_data);
   view->on_scrollbar_value_changed(adjustment);
 }
on_scroom_bootstrap()
void on_scroom_bootstrap (const FileNameMap & newFilenames)
Definition at line 411 of file callbacks.cc.
Referenced by main().
 {
   printf("Bootstrapping Scroom...\n");
   filenames     = newFilenames;
   currentFolder = ".";
   bool devMode = nullptr != getenv(SCROOM_DEV_MODE.c_str());
   if(devMode)
   {
     printf(
       "+----------------------------------------------------------------------+\n"
       "| ENTERING DEVELOPMENT MODE                                            |\n"
       "| All the default directories are not searched                         |\n"
       "| Instead, only environment variables and the local source tree        |\n"
       "| are consulted.                                                       |\n"
       "+----------------------------------------------------------------------+\n");
   }
   startPluginManager(devMode);
   if(devMode)
   {
     xmlFileName = TOP_SRCDIR "/gui/scroom.glade";
   }
   else
   {
 #ifdef _WIN32
     // We want to keep everything portable on windows so we look for the .glade file in the same directory as the .exe
     xmlFileName = (boost::dll::program_location().parent_path() / "scroom.glade").generic_string();
 #else
     xmlFileName = PACKAGE_DATA_DIR "/scroom.glade";
 #endif
   }
   aboutDialogXml = glade_xml_new(xmlFileName.c_str(), "aboutDialog", nullptr);
   if(aboutDialogXml != nullptr)
   {
     aboutDialog = glade_xml_get_widget(aboutDialogXml, "aboutDialog");
     gtk_about_dialog_set_program_name(GTK_ABOUT_DIALOG(aboutDialog), "Scroom");
     gtk_about_dialog_set_version(GTK_ABOUT_DIALOG(aboutDialog), PACKAGE_VERSION);
 #ifdef _WIN32
     g_signal_connect(G_OBJECT(aboutDialog), "activate-link", G_CALLBACK(on_open_scroom_website), NULL);
 #endif
   }
   else
   {
     printf("Opening xml failed\n");
     exit(-1);
   }
   if(filenames.empty())
   {
     create_scroom(PresentationInterface::Ptr());
   }
 }
on_scroom_hide()
void on_scroom_hide (GtkWidget * widget, gpointer user_data)
Definition at line 76 of file callbacks.cc.
Referenced by create_scroom().
 {
   View* view = static_cast<View*>(user_data);
   on_view_destroyed(view);
   if(views.empty())
   {
     gtk_main_quit();
   }
 }
on_scroom_terminating()
void on_scroom_terminating ()
Definition at line 468 of file callbacks.cc.
Referenced by main().
 { ensure(views.empty()); }
on_textbox_value_changed()
void on_textbox_value_changed (GtkEditable * editable, gpointer user_data)
Definition at line 363 of file callbacks.cc.
Referenced by create_scroom().
 {
   View* view = static_cast<View*>(user_data);
   view->on_textbox_value_changed(editable);
 }
on_view_created()
void on_view_created (View::Ptr v)
Definition at line 615 of file callbacks.cc.
Referenced by create_scroom().
 {
   Scroom::Bookkeeping::Token t;
   views[v] = t;
   for(auto& presentation: presentations)
   {
     PresentationInterface::Ptr p = presentation.lock();
     if(p)
     {
       v->on_presentation_created(p);
     }
   }
   const std::map<ViewObserver::Ptr, std::string>& viewObservers = PluginManager::getInstance()->getViewObservers();
   auto cur = viewObservers.begin();
   auto end = viewObservers.end();
   for(; cur != end; cur++)
   {
     t.add(cur->first->viewAdded(v));
   }
 }
on_view_destroyed()
void on_view_destroyed (View * v)
Definition at line 672 of file callbacks.cc.
Referenced by on_scroom_hide().
 {
   View::Ptr view = v->shared_from_this<View>();
   view->clearPresentation();
   views.erase(view);
   view.reset();
   on_presentation_possibly_destroyed();
 }
on_zoombox_changed()
void on_zoombox_changed (GtkComboBox * widget, gpointer user_data)
Definition at line 357 of file callbacks.cc.
Referenced by create_scroom().
 {
   View* view = static_cast<View*>(user_data);
   view->on_zoombox_changed();
 }
Variable Documentation
REGULAR_FILES
const std::string REGULAR_FILES
Definition at line 48 of file callbacks.cc.
Referenced by main(), and on_done_loading_plugins().