Scroom: Scroom::Utils::Rectangle< T > Class Template Reference
Scroom::Utils::Rectangle< T > Class Template Reference
#include <rectangle.hh>
Public Types
using value_type = T
Public Member Functions
Rectangle ()=default
Rectangle (value_type x_, value_type y_, value_type width_, value_type height_)
Rectangle (const Segment< value_type > &horizontally_, const Segment< value_type > &vertically_)
Rectangle (const GdkRectangle &rect)
Rectangle (const GdkPoint first, const GdkPoint second)
template<bool T_is_int = std::is_same<int, typename std::remove_cv<T>::type>::value>
Rectangle (typename std::enable_if<!T_is_int, Rectangle< int > const &>::type rect)
Implicit conversion from Rectangle<int> to Rectangle<T>.
GdkRectangle toGdkRectangle () const
Rectangle< int > toIntRectangle () const
Rectangle moveTo (Point< value_type > const &other) const
Rectangle moveTo (value_type const &x, value_type const &y) const
bool contains (Point< value_type > const &other) const
bool contains (const Rectangle &other) const
bool intersects (const Rectangle &other) const
void reduceSizeToMultipleOf (value_type size)
Rectangle intersection (const Rectangle &other) const
template<typename U >
Rectangle< typename std::common_type< T, U >::type > intersection (const Rectangle< U > &other) const
value_type getTop () const
value_type getLeft () const
value_type getBottom () const
value_type getRight () const
value_type getWidth () const
value_type getHeight () const
value_type x () const
value_type y () const
value_type width () const
value_type height () const
Point< value_type > getTopLeft () const
Point< value_type > getTopRight () const
Point< value_type > getBottomLeft () const
Point< value_type > getBottomRight () const
bool isEmpty () const
Rectangle< value_type > leftOf (value_type v) const
Rectangle< value_type > rightOf (value_type v) const
Rectangle< value_type > above (value_type v) const
Rectangle< value_type > below (value_type v) const
Rectangle< value_type > leftOf (Rectangle< value_type > const &r) const
Rectangle< value_type > rightOf (Rectangle< value_type > const &r) const
Rectangle< value_type > above (Rectangle< value_type > const &r) const
Rectangle< value_type > below (Rectangle< value_type > const &r) const
bool operator== (const Rectangle &other) const
bool operator!= (const Rectangle &other) const
Rectangle< value_type > & operator+= (Point< value_type > const &other)
Rectangle< value_type > & operator-= (Point< value_type > const &other)
Rectangle< value_type > & operator*= (value_type other)
Rectangle< value_type > & operator*= (Point< value_type > const &other)
Rectangle< value_type > & operator/= (value_type other)
Rectangle< value_type > & operator/= (Point< value_type > const &other)
const Segment< value_type > & getHorizontally () const
const Segment< value_type > & getVertically () const
void setSize (Point< value_type > const &s)
Point< value_type > getSize () const
Private Attributes
Segment< value_type > horizontally
Segment< value_type > vertically
Detailed Description
template<typename T>
class Scroom::Utils::Rectangle< T >
Definition at line 24 of file rectangle.hh.
Member Typedef Documentation
value_type
template<typename T> using Scroom::Utils::Rectangle< T >::value_type = T
Definition at line 33 of file rectangle.hh.
Constructor & Destructor Documentation
Rectangle() [1/6]
template<typename T> Scroom::Utils::Rectangle< T >::Rectangle () default
Referenced by Scroom::Utils::Rectangle< int >::intersection(), and Scroom::Utils::Rectangle< int >::moveTo().
Rectangle() [2/6]
template<typename T> Scroom::Utils::Rectangle< T >::Rectangle (value_type x_, value_type y_, value_type width_, value_type height_) inline
Definition at line 37 of file rectangle.hh.
         : horizontally(x_, width_)
         , vertically(y_, height_)
       {}
Rectangle() [3/6]
template<typename T> Scroom::Utils::Rectangle< T >::Rectangle (const Segment< value_type > & horizontally_, const Segment< value_type > & vertically_) inline
Definition at line 42 of file rectangle.hh.
         : horizontally(horizontally_)
         , vertically(vertically_)
       {}
Rectangle() [4/6]
template<typename T> Scroom::Utils::Rectangle< T >::Rectangle (const GdkRectangle< T > & rect) inline
Definition at line 47 of file rectangle.hh.
         : horizontally(rect.x, rect.width)
         , vertically(rect.y, rect.height)
       {}
Rectangle() [5/6]
template<typename T> Scroom::Utils::Rectangle< T >::Rectangle (const GdkPoint first, const GdkPoint second) inline
Definition at line 52 of file rectangle.hh.
         : horizontally(first.x, second.x - first.x)
         , vertically(first.y, second.y - first.y)
       {}
Rectangle() [6/6]
template<typename T> template<bool T_is_int = std::is_same<int, typename std::remove_cv<T>::type>::value> Scroom::Utils::Rectangle< T >::Rectangle (typename std::enable_if<!T_is_int, Rectangle< int > const &>::type rect) inline
Implicit conversion from Rectangle<int> to Rectangle<T>.
If T!=int
Definition at line 59 of file rectangle.hh.
         : horizontally(rect.getHorizontally())
         , vertically(rect.getVertically())
       {}
Member Function Documentation
above() [1/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::above (value_type v) const inline
Definition at line 164 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
       {
         return Rectangle<value_type>(horizontally, vertically.before(v));
       }
above() [2/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::above (Rectangle< value_type > const & r) const inline
Definition at line 194 of file rectangle.hh.
       {
         if(r.isEmpty())
         {
           return r;
         }
         return Rectangle<value_type>(horizontally.intersection(r.horizontally), vertically.before(r.vertically.getStart()));
       }
below() [1/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::below (value_type v) const inline
Definition at line 169 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
       {
         return Rectangle<value_type>(horizontally, vertically.after(v));
       }
below() [2/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::below (Rectangle< value_type > const & r) const inline
Definition at line 204 of file rectangle.hh.
       {
         if(r.isEmpty())
         {
           return r;
         }
         return Rectangle<value_type>(horizontally.intersection(r.horizontally), vertically.after(r.vertically.getEnd()));
       }
contains() [1/2]
template<typename T> bool Scroom::Utils::Rectangle< T >::contains (Point< value_type > const & other) const inline
Definition at line 78 of file rectangle.hh.
       {
         return horizontally.contains(other.x) && vertically.contains(other.y);
       }
contains() [2/2]
template<typename T> bool Scroom::Utils::Rectangle< T >::contains (const Rectangle< T > & other) const inline
Definition at line 83 of file rectangle.hh.
       {
         return horizontally.contains(other.horizontally) && vertically.contains(other.vertically);
       }
getBottom()
template<typename T> value_type Scroom::Utils::Rectangle< T >::getBottom () const inline
Definition at line 116 of file rectangle.hh.
Referenced by anonymous_namespace{sizedeterminer.cc}::DetermineSize(), drawOutOfBoundsWithoutBackground(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), Scroom::Utils::roundOutward(), PipetteCommonOperationsCMYK::sumPixelValues(), and PipetteCommonOperationsRGB::sumPixelValues().
 { return vertically.getEnd(); }
getBottomLeft()
template<typename T> Point<value_type> Scroom::Utils::Rectangle< T >::getBottomLeft () const inline
Definition at line 142 of file rectangle.hh.
       {
         return Point<value_type>(horizontally.getStart(), vertically.getEnd());
       }
getBottomRight()
template<typename T> Point<value_type> Scroom::Utils::Rectangle< T >::getBottomRight () const inline
Definition at line 147 of file rectangle.hh.
Referenced by PipetteHandler::displayValues().
       {
         return Point<value_type>(horizontally.getEnd(), vertically.getEnd());
       }
getHeight()
template<typename T> value_type Scroom::Utils::Rectangle< T >::getHeight () const inline
Definition at line 122 of file rectangle.hh.
Referenced by PipetteHandler::displayValues(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), Scroom::Utils::Rectangle< int >::height(), setClip(), Scroom::Utils::Rectangle< int >::toGdkRectangle(), and Scroom::Utils::Rectangle< int >::toIntRectangle().
 { return vertically.getSize(); }
getHorizontally()
template<typename T> const Segment<value_type>& Scroom::Utils::Rectangle< T >::getHorizontally () const inline
Definition at line 269 of file rectangle.hh.
 { return horizontally; }
getLeft()
template<typename T> value_type Scroom::Utils::Rectangle< T >::getLeft () const inline
Definition at line 114 of file rectangle.hh.
Referenced by anonymous_namespace{sizedeterminer.cc}::DetermineSize(), drawOutOfBoundsWithoutBackground(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), Scroom::Utils::operator<<(), TiledBitmap::redraw(), Scroom::Utils::roundOutward(), setClip(), PipetteCommonOperationsCMYK::sumPixelValues(), PipetteCommonOperationsRGB::sumPixelValues(), Scroom::Utils::Rectangle< int >::toGdkRectangle(), Scroom::Utils::Rectangle< int >::toIntRectangle(), and Scroom::Utils::Rectangle< int >::x().
 { return horizontally.getStart(); }
getRight()
template<typename T> value_type Scroom::Utils::Rectangle< T >::getRight () const inline
Definition at line 118 of file rectangle.hh.
Referenced by anonymous_namespace{sizedeterminer.cc}::DetermineSize(), drawOutOfBoundsWithoutBackground(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), Scroom::Utils::roundOutward(), PipetteCommonOperationsCMYK::sumPixelValues(), and PipetteCommonOperationsRGB::sumPixelValues().
 { return horizontally.getEnd(); }
getSize()
template<typename T> Point<value_type> Scroom::Utils::Rectangle< T >::getSize () const inline
Definition at line 279 of file rectangle.hh.
 { return Point<value_type>(horizontally.getSize(), vertically.getSize()); }
getTop()
template<typename T> value_type Scroom::Utils::Rectangle< T >::getTop () const inline
Definition at line 112 of file rectangle.hh.
Referenced by anonymous_namespace{sizedeterminer.cc}::DetermineSize(), drawOutOfBoundsWithoutBackground(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), Scroom::Utils::roundOutward(), setClip(), PipetteCommonOperationsCMYK::sumPixelValues(), PipetteCommonOperationsRGB::sumPixelValues(), Scroom::Utils::Rectangle< int >::toGdkRectangle(), Scroom::Utils::Rectangle< int >::toIntRectangle(), and Scroom::Utils::Rectangle< int >::y().
 { return vertically.getStart(); }
getTopLeft()
template<typename T> Point<value_type> Scroom::Utils::Rectangle< T >::getTopLeft () const inline
Definition at line 132 of file rectangle.hh.
Referenced by PipetteHandler::displayValues(), CommonOperations::draw(), Operations1bpp::draw(), Operations8bpp::draw(), Operations::draw(), drawOutOfBoundsWithBackground(), drawOutOfBoundsWithBackgroundColor(), drawOutOfBoundsWithoutBackground(), MeasureHandler::render(), and PipetteHandler::render().
       {
         return Point<value_type>(horizontally.getStart(), vertically.getStart());
       }
getTopRight()
template<typename T> Point<value_type> Scroom::Utils::Rectangle< T >::getTopRight () const inline
Definition at line 137 of file rectangle.hh.
       {
         return Point<value_type>(horizontally.getEnd(), vertically.getStart());
       }
getVertically()
template<typename T> const Segment<value_type>& Scroom::Utils::Rectangle< T >::getVertically () const inline
Definition at line 271 of file rectangle.hh.
 { return vertically; }
getWidth()
template<typename T> value_type Scroom::Utils::Rectangle< T >::getWidth () const inline
Definition at line 120 of file rectangle.hh.
Referenced by PipetteHandler::displayValues(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), setClip(), PipetteCommonOperationsCMYK::sumPixelValues(), PipetteCommonOperationsRGB::sumPixelValues(), Scroom::Utils::Rectangle< int >::toGdkRectangle(), Scroom::Utils::Rectangle< int >::toIntRectangle(), and Scroom::Utils::Rectangle< int >::width().
 { return horizontally.getSize(); }
height()
template<typename T> value_type Scroom::Utils::Rectangle< T >::height () const inline
Definition at line 130 of file rectangle.hh.
Referenced by TiledBitmap::drawTile(), Scroom::Utils::make_rect(), Scroom::Utils::roundOutward(), traceRectangleContour(), View::updateRulers(), View::updateScrollbars(), and View::updateZoom().
 { return getHeight(); }
intersection() [1/2]
template<typename T> Rectangle Scroom::Utils::Rectangle< T >::intersection (const Rectangle< T > & other) const inline
Definition at line 99 of file rectangle.hh.
Referenced by PipetteHandler::computeValues(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages(), Scroom::Utils::Rectangle< int >::intersection(), and TiledBitmap::redraw().
       {
         return Rectangle(horizontally.intersection(other.horizontally), vertically.intersection(other.vertically));
       }
intersection() [2/2]
template<typename T> template<typename U > Rectangle<typename std::common_type<T, U>::type> Scroom::Utils::Rectangle< T >::intersection (const Rectangle< U > & other) const inline
Definition at line 105 of file rectangle.hh.
       {
         using R = typename std::common_type<T, U>::type;
         return Rectangle<R>(*this).intersection(Rectangle<R>(other));
       }
intersects()
template<typename T> bool Scroom::Utils::Rectangle< T >::intersects (const Rectangle< T > & other) const inline
Definition at line 88 of file rectangle.hh.
       {
         return horizontally.intersects(other.horizontally) && vertically.intersects(other.vertically);
       }
isEmpty()
template<typename T> bool Scroom::Utils::Rectangle< T >::isEmpty () const inline
Definition at line 152 of file rectangle.hh.
Referenced by Scroom::Utils::Rectangle< int >::above(), Scroom::Utils::Rectangle< int >::below(), Scroom::Utils::Rectangle< int >::leftOf(), Scroom::Utils::Rectangle< int >::operator==(), and Scroom::Utils::Rectangle< int >::rightOf().
 { return horizontally.isEmpty() || vertically.isEmpty(); }
leftOf() [1/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::leftOf (value_type v) const inline
Definition at line 154 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
       {
         return Rectangle<value_type>(horizontally.before(v), vertically);
       }
leftOf() [2/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::leftOf (Rectangle< value_type > const & r) const inline
Definition at line 174 of file rectangle.hh.
       {
         if(r.isEmpty())
         {
           return r;
         }
         return Rectangle<value_type>(horizontally.before(r.horizontally.getStart()), vertically.intersection(r.vertically));
       }
moveTo() [1/2]
template<typename T> Rectangle Scroom::Utils::Rectangle< T >::moveTo (Point< value_type > const & other) const inline
Definition at line 71 of file rectangle.hh.
Referenced by drawOutOfBoundsWithBackground(), and Scroom::Utils::Rectangle< int >::moveTo().
 { return moveTo(other.x, other.y); }
moveTo() [2/2]
template<typename T> Rectangle Scroom::Utils::Rectangle< T >::moveTo (value_type const & x, value_type const & y) const inline
Definition at line 73 of file rectangle.hh.
       {
         return Rectangle(horizontally.moveTo(x), vertically.moveTo(y));
       }
operator!=()
template<typename T> bool Scroom::Utils::Rectangle< T >::operator!= (const Rectangle< T > & other) const inline
Definition at line 230 of file rectangle.hh.
 { return !(*this == other); }
operator*=() [1/2]
template<typename T> Rectangle<value_type>& Scroom::Utils::Rectangle< T >::operator*= (value_type other) inline
Definition at line 241 of file rectangle.hh.
       {
         horizontally *= other;
         vertically *= other;
         return *this;
       }
operator*=() [2/2]
template<typename T> Rectangle<value_type>& Scroom::Utils::Rectangle< T >::operator*= (Point< value_type > const & other) inline
Definition at line 248 of file rectangle.hh.
       {
         horizontally *= other.x;
         vertically *= other.y;
         return *this;
       }
operator+=()
template<typename T> Rectangle<value_type>& Scroom::Utils::Rectangle< T >::operator+= (Point< value_type > const & other) inline
Definition at line 232 of file rectangle.hh.
       {
         horizontally += other.x;
         vertically += other.y;
         return *this;
       }
operator-=()
template<typename T> Rectangle<value_type>& Scroom::Utils::Rectangle< T >::operator-= (Point< value_type > const & other) inline
Definition at line 239 of file rectangle.hh.
 { return *this += -other; }
operator/=() [1/2]
template<typename T> Rectangle<value_type>& Scroom::Utils::Rectangle< T >::operator/= (value_type other) inline
Definition at line 255 of file rectangle.hh.
       {
         horizontally /= other;
         vertically /= other;
         return *this;
       }
operator/=() [2/2]
template<typename T> Rectangle<value_type>& Scroom::Utils::Rectangle< T >::operator/= (Point< value_type > const & other) inline
Definition at line 262 of file rectangle.hh.
       {
         horizontally /= other.x;
         vertically /= other.y;
         return *this;
       }
operator==()
template<typename T> bool Scroom::Utils::Rectangle< T >::operator== (const Rectangle< T > & other) const inline
Definition at line 214 of file rectangle.hh.
       {
         if(isEmpty() != other.isEmpty())
         {
           return false;
         }
         else if(isEmpty())
         {
           return true;
         }
         else
         {
           return horizontally == other.horizontally && vertically == other.vertically;
         }
       }
reduceSizeToMultipleOf()
template<typename T> void Scroom::Utils::Rectangle< T >::reduceSizeToMultipleOf (value_type size) inline
Definition at line 93 of file rectangle.hh.
       {
         horizontally.reduceSizeToMultipleOf(size);
         vertically.reduceSizeToMultipleOf(size);
       }
rightOf() [1/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::rightOf (value_type v) const inline
Definition at line 159 of file rectangle.hh.
Referenced by drawOutOfBoundsWithoutBackground().
       {
         return Rectangle<value_type>(horizontally.after(v), vertically);
       }
rightOf() [2/2]
template<typename T> Rectangle<value_type> Scroom::Utils::Rectangle< T >::rightOf (Rectangle< value_type > const & r) const inline
Definition at line 184 of file rectangle.hh.
       {
         if(r.isEmpty())
         {
           return r;
         }
         return Rectangle<value_type>(horizontally.after(r.horizontally.getEnd()), vertically.intersection(r.vertically));
       }
setSize()
template<typename T> void Scroom::Utils::Rectangle< T >::setSize (Point< value_type > const & s) inline
Definition at line 273 of file rectangle.hh.
       {
         horizontally.setSize(s.x);
         vertically.setSize(s.y);
       }
toGdkRectangle()
template<typename T> GdkRectangle Scroom::Utils::Rectangle< T >::toGdkRectangle () const inline
Definition at line 64 of file rectangle.hh.
Referenced by TransparentOverlayViewInfo::redraw().
       {
         return Scroom::GtkHelpers::createGdkRectangle(getLeft(), getTop(), getWidth(), getHeight());
       }
toIntRectangle()
template<typename T> Rectangle<int> Scroom::Utils::Rectangle< T >::toIntRectangle () const inline
Definition at line 69 of file rectangle.hh.
Referenced by anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::getPixelAverages().
 { return Rectangle<int>(getLeft(), getTop(), getWidth(), getHeight()); }
width()
template<typename T> value_type Scroom::Utils::Rectangle< T >::width () const inline
Definition at line 128 of file rectangle.hh.
Referenced by TiledBitmap::drawTile(), Scroom::Utils::make_rect(), Scroom::Utils::roundOutward(), traceRectangleContour(), View::updateRulers(), View::updateScrollbars(), and View::updateZoom().
 { return getWidth(); }
x()
template<typename T> value_type Scroom::Utils::Rectangle< T >::x () const inline
Definition at line 124 of file rectangle.hh.
Referenced by Operations1bpp::draw(), Operations8bpp::draw(), Operations::draw(), TiledBitmap::drawTile(), Scroom::Utils::make_rect(), Scroom::Utils::roundOutward(), traceRectangleContour(), View::updateRulers(), and View::updateScrollbars().
 { return getLeft(); }
y()
template<typename T> value_type Scroom::Utils::Rectangle< T >::y () const inline
Definition at line 126 of file rectangle.hh.
Referenced by Operations1bpp::draw(), Operations8bpp::draw(), Operations::draw(), TiledBitmap::drawTile(), Scroom::Utils::make_rect(), Scroom::Utils::roundOutward(), traceRectangleContour(), View::updateRulers(), and View::updateScrollbars().
 { return getTop(); }
Member Data Documentation
horizontally
template<typename T> Segment<value_type> Scroom::Utils::Rectangle< T >::horizontally private
Definition at line 282 of file rectangle.hh.
Referenced by Scroom::Utils::Rectangle< int >::above(), Scroom::Utils::Rectangle< int >::below(), Scroom::Utils::Rectangle< int >::contains(), Scroom::Utils::Rectangle< int >::getBottomLeft(), Scroom::Utils::Rectangle< int >::getBottomRight(), Scroom::Utils::Rectangle< int >::getHorizontally(), Scroom::Utils::Rectangle< int >::getLeft(), Scroom::Utils::Rectangle< int >::getRight(), Scroom::Utils::Rectangle< int >::getSize(), Scroom::Utils::Rectangle< int >::getTopLeft(), Scroom::Utils::Rectangle< int >::getTopRight(), Scroom::Utils::Rectangle< int >::getWidth(), Scroom::Utils::Rectangle< int >::intersection(), Scroom::Utils::Rectangle< int >::intersects(), Scroom::Utils::Rectangle< int >::isEmpty(), Scroom::Utils::Rectangle< int >::leftOf(), Scroom::Utils::Rectangle< int >::moveTo(), Scroom::Utils::Rectangle< int >::operator*=(), Scroom::Utils::Rectangle< int >::operator+=(), Scroom::Utils::Rectangle< int >::operator/=(), Scroom::Utils::Rectangle< int >::operator==(), Scroom::Utils::Rectangle< int >::reduceSizeToMultipleOf(), Scroom::Utils::Rectangle< int >::rightOf(), and Scroom::Utils::Rectangle< int >::setSize().
vertically
template<typename T> Segment<value_type> Scroom::Utils::Rectangle< T >::vertically private
Definition at line 283 of file rectangle.hh.
Referenced by Scroom::Utils::Rectangle< int >::above(), Scroom::Utils::Rectangle< int >::below(), Scroom::Utils::Rectangle< int >::contains(), Scroom::Utils::Rectangle< int >::getBottom(), Scroom::Utils::Rectangle< int >::getBottomLeft(), Scroom::Utils::Rectangle< int >::getBottomRight(), Scroom::Utils::Rectangle< int >::getHeight(), Scroom::Utils::Rectangle< int >::getSize(), Scroom::Utils::Rectangle< int >::getTop(), Scroom::Utils::Rectangle< int >::getTopLeft(), Scroom::Utils::Rectangle< int >::getTopRight(), Scroom::Utils::Rectangle< int >::getVertically(), Scroom::Utils::Rectangle< int >::intersection(), Scroom::Utils::Rectangle< int >::intersects(), Scroom::Utils::Rectangle< int >::isEmpty(), Scroom::Utils::Rectangle< int >::leftOf(), Scroom::Utils::Rectangle< int >::moveTo(), Scroom::Utils::Rectangle< int >::operator*=(), Scroom::Utils::Rectangle< int >::operator+=(), Scroom::Utils::Rectangle< int >::operator/=(), Scroom::Utils::Rectangle< int >::operator==(), Scroom::Utils::Rectangle< int >::reduceSizeToMultipleOf(), Scroom::Utils::Rectangle< int >::rightOf(), and Scroom::Utils::Rectangle< int >::setSize().
The documentation for this class was generated from the following file:
inc/scroom/rectangle.hh