Scroom: PresentationBase Class Reference
PresentationBase Class Reference abstract
#include <presentationinterface.hh>
Public Member Functions
void open (ViewInterface::WeakPtr vi) override
Gets called just after the View is created.
void close (ViewInterface::WeakPtr vi) override
Gets called just before the View is destroyed.
Public Member Functions inherited from PresentationInterface
virtual Scroom::Utils::Rectangle< double > getRect ()=0
Return the dimensions of your presentation.
virtual void redraw (ViewInterface::Ptr const &vi, cairo_t *cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom)=0
Draw the requested ara at the requested zoom level.
virtual bool getProperty (const std::string &name, std::string &value)=0
Return the value of the requested property.
virtual bool isPropertyDefined (const std::string &name)=0
Return true if the named property exists.
virtual std::string getTitle ()=0
Return the title of the presentation.
virtual Scroom::Utils::Point< double > getAspectRatio () const
Public Member Functions inherited from Scroom::Utils::Observable< T >
Observable ()
~Observable () override
Observable (const Observable &)=delete
Observable (Observable &&)=delete
Observable operator= (const Observable &)=delete
Observable operator= (Observable &&)=delete
Scroom::Bookkeeping::Token registerStrongObserver (Observer const &observer)
Scroom::Bookkeeping::Token registerObserver (ObserverWeak const &observer)
Public Member Functions inherited from Scroom::Utils::Base
Base ()=default
Base (const Base &)=delete
Base (Base &&)=delete
Base & operator= (const Base &)=delete
Base & operator= (Base &&)=delete
virtual ~Base ()=default
template<typename R >
boost::shared_ptr< R > shared_from_this ()
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
Protected Member Functions
void observerAdded (Viewable::Ptr const &viewable, Scroom::Bookkeeping::Token const &t) override
virtual void viewAdded (ViewInterface::WeakPtr vi)=0
virtual void viewRemoved (ViewInterface::WeakPtr vi)=0
virtual std::set< ViewInterface::WeakPtr > getViews ()=0
Protected Member Functions inherited from Scroom::Utils::Observable< T >
std::list< Observer > getObservers ()
Retrieve a list of current observers.
virtual void observerAdded (Observer const &observer, Scroom::Bookkeeping::Token const &token)
Override this function if you want to be notified of new observers registering.
Additional Inherited Members
Public Types inherited from PresentationInterface
using Ptr = boost::shared_ptr< PresentationInterface >
using WeakPtr = boost::weak_ptr< PresentationInterface >
Public Types inherited from Viewable
using Ptr = boost::shared_ptr< Viewable >
using WeakPtr = boost::weak_ptr< Viewable >
Public Types inherited from Scroom::Utils::Observable< T >
using Observer = boost::shared_ptr< T >
using Ptr = boost::shared_ptr< Observable< T > >
Detailed Description
Definition at line 113 of file presentationinterface.hh.
Member Function Documentation
close()
void PresentationBase::close (ViewInterface::WeakPtr vi) override virtual
Gets called just before the View is destroyed.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements Viewable.
Reimplemented in TransformPresentation.
Definition at line 23 of file presentationinterface.cc.
Referenced by TransformPresentation::close().
 {
   std::list<Viewable::Ptr> const observers = getObservers();
   for(Viewable::Ptr const& observer: observers)
   {
     observer->close(vi);
   }
   viewRemoved(vi);
 }
getViews()
virtual std::set<ViewInterface::WeakPtr> PresentationBase::getViews () protected pure virtual
Implemented in PresentationBaseSimple, anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, and TransparentOverlayPresentation.
Referenced by observerAdded().
observerAdded()
void PresentationBase::observerAdded (Viewable::Ptr const & viewable, Scroom::Bookkeeping::Token const & t) override protected
Definition at line 35 of file presentationinterface.cc.
 {
   std::set<ViewInterface::WeakPtr> views = getViews();
   for(ViewInterface::WeakPtr const& view: views)
   {
     viewable->open(view);
   }
 }
open()
void PresentationBase::open (ViewInterface::WeakPtr vi) override virtual
Gets called just after the View is created.
Precondition
Should be called from within a Gdk critical section (i.e. between gdk_threads_enter() and gdk_threads_leave() calls)
Implements Viewable.
Reimplemented in TransformPresentation.
Definition at line 11 of file presentationinterface.cc.
Referenced by TransformPresentation::open().
 {
   viewAdded(vi);
   std::list<Viewable::Ptr> const observers = getObservers();
   for(Viewable::Ptr const& observer: observers)
   {
     observer->open(vi);
   }
 }
viewAdded()
virtual void PresentationBase::viewAdded (ViewInterface::WeakPtr vi) protected pure virtual
Implemented in PresentationBaseSimple, anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, and TransparentOverlayPresentation.
Referenced by open().
viewRemoved()
virtual void PresentationBase::viewRemoved (ViewInterface::WeakPtr vi) protected pure virtual
Implemented in PresentationBaseSimple, anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, and TransparentOverlayPresentation.
Referenced by close().
The documentation for this class was generated from the following files:
inc/scroom/presentationinterface.hh
libs/scroom/src/presentationinterface.cc