Scroom: Colormap Class Reference
Colormap Class Reference
Represent a colormap.
#include <colormappable.hh>
Public Types
using Ptr = boost::shared_ptr< Colormap >
using ConstPtr = boost::shared_ptr< const Colormap >
using WeakPtr = boost::weak_ptr< Colormap >
Public Member Functions
Ptr clone () const
void setAlpha (double alpha)
Ptr setAlpha (double alpha) const
Static Public Member Functions
static Colormap::Ptr create ()
Constructor.
static Colormap::Ptr createDefault (int n)
Constructor.
static Colormap::Ptr createDefaultInverted (int n)
Constructor.
Public Attributes
std::string name
Name of this colormap.
std::vector< Color > colors
Colors in this colormap.
Private Member Functions
Colormap ()
Constructor.
Detailed Description
Represent a colormap.
Definition at line 28 of file colormappable.hh.
Member Typedef Documentation
ConstPtr
using Colormap::ConstPtr = boost::shared_ptr<const Colormap>
Definition at line 32 of file colormappable.hh.
Ptr
using Colormap::Ptr = boost::shared_ptr<Colormap>
Definition at line 31 of file colormappable.hh.
WeakPtr
using Colormap::WeakPtr = boost::weak_ptr<Colormap>
Definition at line 33 of file colormappable.hh.
Constructor & Destructor Documentation
Colormap()
Colormap::Colormap () inline private
Constructor.
Create an empty colormap
Definition at line 41 of file colormappable.hh.
Referenced by clone(), and create().
     : name("Empty")
   {}
Member Function Documentation
clone()
Ptr Colormap::clone () const inline
Definition at line 81 of file colormappable.hh.
Referenced by setAlpha().
 { return Ptr(new Colormap(*this)); }
create()
static Colormap::Ptr Colormap::create () inline static
Constructor.
Create a smart pointer to an empty colormap
Definition at line 47 of file colormappable.hh.
Referenced by createDefault(), createDefaultInverted(), and Scroom::Tiff::getColorMap().
 { return Ptr(new Colormap()); }
createDefault()
static Colormap::Ptr Colormap::createDefault (int n) inline static
Constructor.
Create a smart pointer to a colormap of n grays.
Definition at line 50 of file colormappable.hh.
Referenced by ColormapHelper::create(), and MonochromeColormapHelper::generateInitialColormap().
   {
     Colormap::Ptr result = create();
     result->name         = "Default";
     result->colors.reserve(n);
     result->colors.clear();
     double max = n - 1;
     for(int i = 0; i < n; i++)
     {
       result->colors.emplace_back(i / max); // Min is black
     }
     return result;
   }
createDefaultInverted()
static Colormap::Ptr Colormap::createDefaultInverted (int n) inline static
Constructor.
Create a smart pointer to a colormap of n grays.
Definition at line 66 of file colormappable.hh.
Referenced by ColormapHelper::createInverted(), and MonochromeColormapHelper::generateInitialColormap().
   {
     Colormap::Ptr result = create();
     result->name         = "0 is white";
     result->colors.reserve(n);
     result->colors.clear();
     double max = n - 1;
     for(int i = 0; i < n; i++)
     {
       result->colors.emplace_back((max - i) / max); // Min is white
     }
     return result;
   }
setAlpha() [1/2]
void Colormap::setAlpha (double alpha) inline
Definition at line 83 of file colormappable.hh.
   {
     for(Color& c: colors)
     {
       c.setAlpha(alpha);
     }
   }
setAlpha() [2/2]
Ptr Colormap::setAlpha (double alpha) const inline
Definition at line 91 of file colormappable.hh.
   {
     Ptr result = clone();
     result->setAlpha(alpha);
     return result;
   }
Member Data Documentation
colors
std::vector<Color> Colormap::colors
Colors in this colormap.
Definition at line 37 of file colormappable.hh.
name
std::string Colormap::name
Name of this colormap.
Definition at line 36 of file colormappable.hh.
The documentation for this class was generated from the following file:
inc/scroom/colormappable.hh