Scroom: Scroom::Utils::Observable< T > Class Template Reference
Scroom::Utils::Observable< T > Class Template Reference
Base class for something that accepts observers.
#include <observable.hh>
Public Types
using Observer = boost::shared_ptr< T >
using Ptr = boost::shared_ptr< Observable< T > >
Public Member Functions
Observable ()
~Observable () override
Observable (const Observable &)=delete
Observable (Observable &&)=delete
Observable operator= (const Observable &)=delete
Observable operator= (Observable &&)=delete
Scroom::Bookkeeping::Token registerStrongObserver (Observer const &observer)
Scroom::Bookkeeping::Token registerObserver (ObserverWeak const &observer)
Public Member Functions inherited from Scroom::Utils::Base
Base ()=default
Base (const Base &)=delete
Base (Base &&)=delete
Base & operator= (const Base &)=delete
Base & operator= (Base &&)=delete
virtual ~Base ()=default
template<typename R >
boost::shared_ptr< R > shared_from_this ()
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
Protected Member Functions
std::list< Observer > getObservers ()
Retrieve a list of current observers.
virtual void observerAdded (Observer const &observer, Scroom::Bookkeeping::Token const &token)
Override this function if you want to be notified of new observers registering.
Private Types
using ObserverWeak = boost::weak_ptr< T >
using Registration = Detail::Registration< T >
Private Member Functions
void unregisterObserver (ObserverWeak const &observer)
Private Attributes
Scroom::Bookkeeping::Map< ObserverWeak, typename Registration::Ptr >::Ptr registrationMap
Map all registrations to their registration data.
Friends
class Detail::Registration< T >
Detailed Description
template<typename T>
class Scroom::Utils::Observable< T >
Base class for something that accepts observers.
Upon registering, observers are given a Registration. If the same Observer registers twice (using the same method), he'll still receive events only once. When the Observer destroys his Registration, he'll be unregistered.
There are two ways of registering: One can register a shared_ptr, or a weak_ptr, depending on whether you want the Observable to keep the Observer from being destructed.
Note
When you register one Observer with both a shared_ptr and a weak_ptr, unpredictable things will happen.
Definition at line 25 of file observable.hh.
Member Typedef Documentation
Observer
template<typename T> using Scroom::Utils::Observable< T >::Observer = boost::shared_ptr<T>
Definition at line 75 of file observable.hh.
ObserverWeak
template<typename T> using Scroom::Utils::Observable< T >::ObserverWeak = boost::weak_ptr<T> private
Definition at line 79 of file observable.hh.
Ptr
template<typename T> using Scroom::Utils::Observable< T >::Ptr = boost::shared_ptr<Observable<T> >
Definition at line 76 of file observable.hh.
Registration
template<typename T> using Scroom::Utils::Observable< T >::Registration = Detail::Registration<T> private
Definition at line 80 of file observable.hh.
Constructor & Destructor Documentation
Observable() [1/3]
template<typename T > Scroom::Utils::Observable< T >::Observable ()
Definition at line 172 of file observable.hh.
     {
       registrationMap = Scroom::Bookkeeping::Map<ObserverWeak, typename Registration::Ptr>::create();
     }
~Observable()
template<typename T > Scroom::Utils::Observable< T >::~Observable () override
Definition at line 178 of file observable.hh.
     {
       // Destroy strong references to any observers
       //
       // The one holding the token of the registration is in control
       // of the lifetime of the registration objects. Hence, as long
       // as the Token is valid, a reference to the Registration will
       // exist, which may, in turn, contain a (strong) reference to an
       // Observer. This is not desirable. As soon as the observable is
       // deleted (which is now), it should no longer hold any
       // references to any Observers. Hence, we should manually reset
       // references to observers here.
       for(const typename Registration::Ptr& registration: registrationMap->values())
       {
         registration->o.reset();
       }
     }
Observable() [2/3]
template<typename T> Scroom::Utils::Observable< T >::Observable (const Observable< T > &) delete
Observable() [3/3]
template<typename T> Scroom::Utils::Observable< T >::Observable (Observable< T > &&) delete
Member Function Documentation
getObservers()
template<typename T > std::list< typename Observable< T >::Observer > Scroom::Utils::Observable< T >::getObservers () protected
Retrieve a list of current observers.
Always, a list of shared_ptr objects is returned, regardless of whether the Observer registered a shared_ptr or a weak_ptr.
Definition at line 197 of file observable.hh.
Referenced by PresentationBase::close(), and PresentationBase::open().
     {
       std::list<typename Observable<T>::Observer> result;
       for(const typename Registration::Ptr& registration: registrationMap->values())
       {
         Observer o = registration->observer.lock();
         if(o)
         {
           result.push_back(o);
         }
       }
       return result;
     }
observerAdded()
template<typename T> void Scroom::Utils::Observable< T >::observerAdded (Observer const & observer, Scroom::Bookkeeping::Token const & token) protected virtual
Override this function if you want to be notified of new observers registering.
Reimplemented in CompressedTile, and CompressedTile.
Definition at line 259 of file observable.hh.
     {
       // Do nothing
     }
operator=() [1/2]
template<typename T> Observable Scroom::Utils::Observable< T >::operator= (const Observable< T > &) delete
operator=() [2/2]
template<typename T> Observable Scroom::Utils::Observable< T >::operator= (Observable< T > &&) delete
registerObserver()
template<typename T> Scroom::Bookkeeping::Token Scroom::Utils::Observable< T >::registerObserver (ObserverWeak const & observer)
Definition at line 233 of file observable.hh.
Referenced by CompressedTile::registerObserver().
     {
       Scroom::Bookkeeping::Token            t = registrationMap->reReserve(observer);
       typename Detail::Registration<T>::Ptr r = registrationMap->get(observer);
       if(r)
       {
         r->set(observer);
       }
       else
       {
         r = Detail::Registration<T>::create(shared_from_this<Observable<T>>(), observer);
         registrationMap->set(observer, r);
       }
       observerAdded(typename Observable<T>::Observer(observer), t);
       return t;
     }
registerStrongObserver()
template<typename T> Scroom::Bookkeeping::Token Scroom::Utils::Observable< T >::registerStrongObserver (Observer const & observer)
Definition at line 213 of file observable.hh.
Referenced by CompressedTile::registerStrongObserver().
     {
       Scroom::Bookkeeping::Token            t = registrationMap->reReserve(observer);
       typename Detail::Registration<T>::Ptr r = registrationMap->get(observer);
       if(r)
       {
         r->set(observer);
       }
       else
       {
         r = Detail::Registration<T>::create(shared_from_this<Observable<T>>(), observer);
         registrationMap->set(observer, r);
       }
       observerAdded(observer, t);
       return t;
     }
unregisterObserver()
template<typename T> void Scroom::Utils::Observable< T >::unregisterObserver (ObserverWeak const & observer) private
Definition at line 253 of file observable.hh.
     {
       registrationMap->remove(observer);
     }
Friends And Related Function Documentation
Detail::Registration< T >
template<typename T> friend class Detail::Registration< T > friend
Definition at line 118 of file observable.hh.
Member Data Documentation
registrationMap
template<typename T> Scroom::Bookkeeping::Map<ObserverWeak, typename Registration::Ptr>::Ptr Scroom::Utils::Observable< T >::registrationMap private
Map all registrations to their registration data.
Definition at line 84 of file observable.hh.
The documentation for this class was generated from the following file:
inc/scroom/observable.hh