Scroom: Scroom::Detail::ThreadPool::FunctionAdditor Class Reference
Scroom::Detail::ThreadPool::FunctionAdditor Class Reference
#include <function-additor.hh>
Public Member Functions
void addBefore (boost::function< void()> const &fn)
void addAfter (boost::function< void()> const &fn)
FunctionAdditor & operator+ (boost::function< void()> const &fn)
FunctionAdditor & operator+= (boost::function< void()> const &fn)
void operator() ()
Private Attributes
std::list< boost::function< void()> > functions
Detailed Description
Definition at line 20 of file function-additor.hh.
Member Function Documentation
addAfter()
void Scroom::Detail::ThreadPool::FunctionAdditor::addAfter (boost::function< void()> const & fn) inline
Definition at line 12 of file function-additor.cc.
Referenced by operator+(), and operator+=().
 { functions.push_back(fn); }
addBefore()
void Scroom::Detail::ThreadPool::FunctionAdditor::addBefore (boost::function< void()> const & fn)
Definition at line 10 of file function-additor.cc.
Referenced by operator+().
 { functions.push_front(fn); }
operator()()
void Scroom::Detail::ThreadPool::FunctionAdditor::operator() ()
Definition at line 30 of file function-additor.cc.
 {
   for(boost::function<void()>& f: functions)
   {
     f();
   }
 }
operator+()
Scroom::Detail::ThreadPool::FunctionAdditor & Scroom::Detail::ThreadPool::FunctionAdditor::operator+ (boost::function< void()> const & fn)
Definition at line 15 of file function-additor.cc.
 {
   addAfter(fn);
   return *this;
 }
operator+=()
Scroom::Detail::ThreadPool::FunctionAdditor & Scroom::Detail::ThreadPool::FunctionAdditor::operator+= (boost::function< void()> const & fn)
Definition at line 23 of file function-additor.cc.
 {
   addAfter(fn);
   return *this;
 }
Member Data Documentation
functions
std::list<boost::function<void()> > Scroom::Detail::ThreadPool::FunctionAdditor::functions private
Definition at line 23 of file function-additor.hh.
Referenced by addAfter(), addBefore(), and operator()().
The documentation for this class was generated from the following files:
inc/scroom/function-additor.hh
libs/threadpool/src/function-additor.cc