Scroom: Scroom::Utils::Detail::Registration< T > Class Template Reference
Scroom::Utils::Detail::Registration< T > Class Template Reference
Contain all info regarding the registration.
#include <observable.hh>
Public Types
using Ptr = boost::shared_ptr< Registration< T > >
Public Member Functions
Registration ()=default
Registration (boost::weak_ptr< Observable< T >> observable, boost::shared_ptr< T > observer)
Registration (boost::weak_ptr< Observable< T >> observable, boost::weak_ptr< T > observer)
void set (boost::shared_ptr< T > observer)
void set (boost::weak_ptr< T > observer)
Static Public Member Functions
static Ptr create (boost::weak_ptr< Observable< T >> observable, boost::shared_ptr< T > observer)
static Ptr create (boost::weak_ptr< Observable< T >> observable, boost::weak_ptr< T > observer)
Public Attributes
boost::weak_ptr< Observable< T > > observable
boost::shared_ptr< T > o
Reference to the observer (for non-weak registrations)
boost::weak_ptr< T > observer
Reference to the observer.
Detailed Description
template<typename T>
class Scroom::Utils::Detail::Registration< T >
Contain all info regarding the registration.
Performs de-registration on destruction
Definition at line 35 of file observable.hh.
Member Typedef Documentation
Ptr
template<typename T> using Scroom::Utils::Detail::Registration< T >::Ptr = boost::shared_ptr<Registration<T> >
Definition at line 42 of file observable.hh.
Constructor & Destructor Documentation
Registration() [1/3]
template<typename T> Scroom::Utils::Detail::Registration< T >::Registration () default
Registration() [2/3]
template<typename T> Scroom::Utils::Detail::Registration< T >::Registration (boost::weak_ptr< Observable< T >> observable, boost::shared_ptr< T > observer)
Definition at line 125 of file observable.hh.
       : observable(observable_)
       , o(observer_)
       , observer(observer_)
     {}
Registration() [3/3]
template<typename T> Scroom::Utils::Detail::Registration< T >::Registration (boost::weak_ptr< Observable< T >> observable, boost::weak_ptr< T > observer)
Definition at line 132 of file observable.hh.
       : observable(observable_)
       , o()
       , observer(observer_)
     {
       // We don't want to store a "hard" reference, so field o is intentionally empty.
     }
Member Function Documentation
create() [1/2]
template<typename T> Detail::Registration< T >::Ptr Scroom::Utils::Detail::Registration< T >::create (boost::weak_ptr< Observable< T >> observable, boost::shared_ptr< T > observer) static
Definition at line 156 of file observable.hh.
Referenced by Scroom::Utils::Observable< TileLoadingObserver >::registerObserver(), and Scroom::Utils::Observable< TileLoadingObserver >::registerStrongObserver().
     {
       return typename Detail::Registration<T>::Ptr(new Detail::Registration<T>(observable, observer));
     }
create() [2/2]
template<typename T> Detail::Registration< T >::Ptr Scroom::Utils::Detail::Registration< T >::create (boost::weak_ptr< Observable< T >> observable, boost::weak_ptr< T > observer) static
Definition at line 163 of file observable.hh.
     {
       return typename Detail::Registration<T>::Ptr(new Detail::Registration<T>(observable, observer));
     }
set() [1/2]
template<typename T> void Scroom::Utils::Detail::Registration< T >::set (boost::shared_ptr< T > observer)
Definition at line 141 of file observable.hh.
Referenced by Scroom::Utils::Observable< TileLoadingObserver >::registerObserver(), and Scroom::Utils::Observable< TileLoadingObserver >::registerStrongObserver().
     {
       o        = observer_;
       observer = observer_;
     }
set() [2/2]
template<typename T> void Scroom::Utils::Detail::Registration< T >::set (boost::weak_ptr< T > observer)
Definition at line 148 of file observable.hh.
     {
       // We don't want to store a "hard" reference, so field o is intentionally empty.
       o.reset();
       observer = observer_;
     }
Member Data Documentation
o
template<typename T> boost::shared_ptr<T> Scroom::Utils::Detail::Registration< T >::o
Reference to the observer (for non-weak registrations)
Definition at line 39 of file observable.hh.
Referenced by Scroom::Utils::Observable< TileLoadingObserver >::getObservers(), and Scroom::Utils::Detail::Registration< T >::set().
observable
template<typename T> boost::weak_ptr<Observable<T> > Scroom::Utils::Detail::Registration< T >::observable
Definition at line 38 of file observable.hh.
Referenced by Scroom::Utils::Detail::Registration< T >::create().
observer
template<typename T> boost::weak_ptr<T> Scroom::Utils::Detail::Registration< T >::observer
Reference to the observer.
Definition at line 40 of file observable.hh.
Referenced by Scroom::Utils::Detail::Registration< T >::set().
The documentation for this class was generated from the following file:
inc/scroom/observable.hh