Scroom: Scroom::Utils::ProgressStateInterface Class Reference
Scroom::Utils::ProgressStateInterface Class Reference abstract
Alternative interface used for reporting progress information.
#include <progressinterfacehelpers.hh>
Public Types
enum State { IDLE, WAITING, WORKING, FINISHED }
using Ptr = boost::shared_ptr< ProgressStateInterface >
using WeakPtr = boost::weak_ptr< ProgressStateInterface >
Public Member Functions
virtual void setProgress (State s, double progress=0.0)=0
Additional Inherited Members
Private Member Functions inherited from Interface
Interface ()=default
Interface (const Interface &)=delete
Interface & operator= (const Interface &)=delete
Interface (const Interface &&)=delete
Interface & operator= (const Interface &&)=delete
virtual ~Interface ()=default
Detailed Description
Alternative interface used for reporting progress information.
Definition at line 25 of file progressinterfacehelpers.hh.
Member Typedef Documentation
Ptr
using Scroom::Utils::ProgressStateInterface::Ptr = boost::shared_ptr<ProgressStateInterface>
Definition at line 28 of file progressinterfacehelpers.hh.
WeakPtr
using Scroom::Utils::ProgressStateInterface::WeakPtr = boost::weak_ptr<ProgressStateInterface>
Definition at line 29 of file progressinterfacehelpers.hh.
Member Enumeration Documentation
State
enum Scroom::Utils::ProgressStateInterface::State
Enumerator
IDLE
WAITING
WORKING
FINISHED
Definition at line 31 of file progressinterfacehelpers.hh.
       {
         IDLE,
         WAITING,
         WORKING,
         FINISHED
       };
Member Function Documentation
setProgress()
virtual void Scroom::Utils::ProgressStateInterface::setProgress (State s, double progress = 0.0) pure virtual
Implemented in Scroom::Utils::ProgressInterfaceMultiplexer::Child, Scroom::Utils::ProgressInterfaceMultiplexer::ChildData, Scroom::Utils::Detail::ProgressStore, Scroom::Utils::ProgressStateInterfaceFromProgressInterface, and Scroom::Utils::ProgressInterfaceFromProgressStateInterfaceForwarder.
Referenced by Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setFinished(), Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setIdle(), Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWaiting(), and Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWorking().
The documentation for this class was generated from the following file:
inc/scroom/progressinterfacehelpers.hh