Scroom: Scroom::Utils::Segment< T > Class Template Reference
Scroom::Utils::Segment< T > Class Template Reference
#include <linearsegment.hh>
Public Types
using value_type = T
Public Member Functions
Segment ()
Segment (value_type start_, value_type size_)
template<bool T_is_int = std::is_same<int, typename std::remove_cv<T>::type>::value>
Segment (typename std::enable_if<!T_is_int, Segment< int > const &>::type other)
Implicit conversion from Segment<int> to Segment<T>.
Segment moveTo (value_type p) const
bool contains (value_type p) const
bool contains (const Segment< value_type > &other) const
bool intersects (const Segment< value_type > &other) const
void reduceSizeToMultipleOf (value_type m)
Segment< value_type > intersection (const Segment< value_type > &other) const
void intersect (const Segment< value_type > &other)
Segment< value_type > before (value_type v) const
Segment< value_type > after (value_type v) const
value_type getStart () const
value_type getEnd () const
value_type getSize () const
bool isEmpty () const
bool operator== (const Segment< value_type > &other) const
bool operator!= (const Segment< value_type > &other) const
Segment< value_type > & operator+= (value_type n)
Segment< value_type > & operator-= (value_type n)
Segment< value_type > & operator*= (value_type n)
Segment< value_type > & operator/= (value_type n)
Segment< value_type > & operator &= (const Segment< value_type > &other)
void setSize (value_type n)
Private Attributes
value_type start
value_type size
Detailed Description
template<typename T>
class Scroom::Utils::Segment< T >
Definition at line 43 of file linearsegment.hh.
Member Typedef Documentation
value_type
template<typename T> using Scroom::Utils::Segment< T >::value_type = T
Definition at line 51 of file linearsegment.hh.
Constructor & Destructor Documentation
Segment() [1/3]
template<typename T> Scroom::Utils::Segment< T >::Segment () inline
Definition at line 53 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::moveTo().
         : start(0)
         , size(0)
       {}
Segment() [2/3]
template<typename T> Scroom::Utils::Segment< T >::Segment (value_type start_, value_type size_) inline
Definition at line 58 of file linearsegment.hh.
         : start(start_)
         , size(size_)
       {
         if(size < 0)
         {
           start += size;
           size = -size;
         }
       }
Segment() [3/3]
template<typename T> template<bool T_is_int = std::is_same<int, typename std::remove_cv<T>::type>::value> Scroom::Utils::Segment< T >::Segment (typename std::enable_if<!T_is_int, Segment< int > const &>::type other) inline
Implicit conversion from Segment<int> to Segment<T>.
If T!=int
Definition at line 71 of file linearsegment.hh.
         : start(other.getStart())
         , size(other.getSize())
       {}
Member Function Documentation
after()
template<typename T> Segment<value_type> Scroom::Utils::Segment< T >::after (value_type v) const inline
Definition at line 123 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::below(), and Scroom::Utils::Rectangle< int >::rightOf().
       {
         if(v > start + size)
         {
           return Segment<value_type>();
         }
         if(v > start)
         {
           return Segment<value_type>(v, start + size - v);
         }
         return *this;
       }
before()
template<typename T> Segment<value_type> Scroom::Utils::Segment< T >::before (value_type v) const inline
Definition at line 110 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::above(), and Scroom::Utils::Rectangle< int >::leftOf().
       {
         if(v < start)
         {
           return Segment<value_type>();
         }
         if(v < start + size)
         {
           return Segment<value_type>(start, v - start);
         }
         return *this;
       }
contains() [1/2]
template<typename T> bool Scroom::Utils::Segment< T >::contains (value_type p) const inline
Definition at line 78 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::contains().
 { return start <= p && p < (start + size); }
contains() [2/2]
template<typename T> bool Scroom::Utils::Segment< T >::contains (const Segment< value_type > & other) const inline
Definition at line 80 of file linearsegment.hh.
       {
         return getStart() <= other.getStart() && other.getEnd() <= getEnd();
       }
getEnd()
template<typename T> value_type Scroom::Utils::Segment< T >::getEnd () const inline
Definition at line 138 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::below(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Rectangle< int >::getBottom(), Scroom::Utils::Rectangle< int >::getBottomLeft(), Scroom::Utils::Rectangle< int >::getBottomRight(), Scroom::Utils::Rectangle< int >::getRight(), Scroom::Utils::Rectangle< int >::getTopRight(), Scroom::Utils::Segment< value_type >::intersection(), Scroom::Utils::Segment< value_type >::intersects(), and Scroom::Utils::Rectangle< int >::rightOf().
 { return start + size; }
getSize()
template<typename T> value_type Scroom::Utils::Segment< T >::getSize () const inline
Definition at line 140 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::getHeight(), Scroom::Utils::Rectangle< int >::getSize(), Scroom::Utils::Rectangle< int >::getWidth(), and Scroom::Utils::Segment< value_type >::isEmpty().
 { return size; }
getStart()
template<typename T> value_type Scroom::Utils::Segment< T >::getStart () const inline
Definition at line 136 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::above(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Rectangle< int >::getBottomLeft(), Scroom::Utils::Rectangle< int >::getLeft(), Scroom::Utils::Rectangle< int >::getTop(), Scroom::Utils::Rectangle< int >::getTopLeft(), Scroom::Utils::Rectangle< int >::getTopRight(), Scroom::Utils::Segment< value_type >::intersection(), Scroom::Utils::Segment< value_type >::intersects(), Scroom::Utils::Rectangle< int >::leftOf(), and Scroom::Utils::operator<<().
 { return start; }
intersect()
template<typename T> void Scroom::Utils::Segment< T >::intersect (const Segment< value_type > & other) inline
Definition at line 108 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::operator&=().
 { *this = intersection(other); }
intersection()
template<typename T> Segment<value_type> Scroom::Utils::Segment< T >::intersection (const Segment< value_type > & other) const inline
Definition at line 92 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::above(), Scroom::Utils::Rectangle< int >::below(), Scroom::Utils::Segment< value_type >::intersect(), Scroom::Utils::Rectangle< int >::intersection(), Scroom::Utils::Rectangle< int >::leftOf(), and Scroom::Utils::Rectangle< int >::rightOf().
       {
         const value_type newStart = std::max(getStart(), other.getStart());
         const value_type newEnd   = std::min(getEnd(), other.getEnd());
         const value_type newSize  = newEnd - newStart;
         if(newSize >= 0)
         {
           return Segment<value_type>(newStart, newSize);
         }
         else
         {
           return Segment<value_type>(); // empty segment
         }
       }
intersects()
template<typename T> bool Scroom::Utils::Segment< T >::intersects (const Segment< value_type > & other) const inline
Definition at line 85 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::intersects().
       {
         return getStart() < other.getEnd() && other.getStart() < getEnd() && !isEmpty() && !other.isEmpty();
       }
isEmpty()
template<typename T> bool Scroom::Utils::Segment< T >::isEmpty () const inline
Definition at line 142 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::intersects(), Scroom::Utils::Rectangle< int >::isEmpty(), and Scroom::Utils::Segment< value_type >::operator==().
 { return isZero(getSize()); }
moveTo()
template<typename T> Segment Scroom::Utils::Segment< T >::moveTo (value_type p) const inline
Definition at line 76 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::moveTo().
 { return Segment(p, size); }
operator &=()
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator&= (const Segment< value_type > & other) inline
Definition at line 184 of file linearsegment.hh.
       {
         intersect(other);
         return *this;
       }
operator!=()
template<typename T> bool Scroom::Utils::Segment< T >::operator!= (const Segment< value_type > & other) const inline
Definition at line 160 of file linearsegment.hh.
 { return !(*this == other); }
operator*=()
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator*= (value_type n) inline
Definition at line 172 of file linearsegment.hh.
       {
         start *= n;
         size *= n;
         return *this;
       }
operator+=()
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator+= (value_type n) inline
Definition at line 162 of file linearsegment.hh.
       {
         start += n;
         return *this;
       }
operator-=()
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator-= (value_type n) inline
Definition at line 167 of file linearsegment.hh.
       {
         start -= n;
         return *this;
       }
operator/=()
template<typename T> Segment<value_type>& Scroom::Utils::Segment< T >::operator/= (value_type n) inline
Definition at line 178 of file linearsegment.hh.
       {
         start /= n;
         size /= n;
         return *this;
       }
operator==()
template<typename T> bool Scroom::Utils::Segment< T >::operator== (const Segment< value_type > & other) const inline
Definition at line 144 of file linearsegment.hh.
       {
         if(isEmpty() != other.isEmpty())
         {
           return false;
         }
         else if(isEmpty())
         {
           return true;
         }
         else
         {
           return areEqual(start, other.start) && areEqual(size, other.size);
         }
       }
reduceSizeToMultipleOf()
template<typename T> void Scroom::Utils::Segment< T >::reduceSizeToMultipleOf (value_type m) inline
Definition at line 90 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::reduceSizeToMultipleOf().
 { size -= size % m; }
setSize()
template<typename T> void Scroom::Utils::Segment< T >::setSize (value_type n) inline
Definition at line 189 of file linearsegment.hh.
Referenced by Scroom::Utils::Rectangle< int >::setSize().
 { size = n; }
Member Data Documentation
size
template<typename T> value_type Scroom::Utils::Segment< T >::size private
Definition at line 193 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::after(), Scroom::Utils::Segment< value_type >::before(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Segment< value_type >::getEnd(), Scroom::Utils::Segment< value_type >::getSize(), Scroom::Utils::make_segment(), Scroom::Utils::Segment< value_type >::moveTo(), Scroom::Utils::Segment< value_type >::operator*=(), Scroom::Utils::Segment< value_type >::operator/=(), Scroom::Utils::Segment< value_type >::operator==(), Scroom::Utils::Segment< value_type >::reduceSizeToMultipleOf(), Scroom::Utils::Segment< value_type >::Segment(), and Scroom::Utils::Segment< value_type >::setSize().
start
template<typename T> value_type Scroom::Utils::Segment< T >::start private
Definition at line 192 of file linearsegment.hh.
Referenced by Scroom::Utils::Segment< value_type >::after(), Scroom::Utils::Segment< value_type >::before(), Scroom::Utils::Segment< value_type >::contains(), Scroom::Utils::Segment< value_type >::getEnd(), Scroom::Utils::Segment< value_type >::getStart(), Scroom::Utils::make_segment(), Scroom::Utils::Segment< value_type >::operator*=(), Scroom::Utils::Segment< value_type >::operator+=(), Scroom::Utils::Segment< value_type >::operator-=(), Scroom::Utils::Segment< value_type >::operator/=(), Scroom::Utils::Segment< value_type >::operator==(), and Scroom::Utils::Segment< value_type >::Segment().
The documentation for this class was generated from the following file:
inc/scroom/linearsegment.hh