Scroom: Scroom::Utils::ProgressInterfaceFromProgressStateInterface Class Reference
Scroom::Utils::ProgressInterfaceFromProgressStateInterface Class Reference
#include <progressinterfacehelpers.hh>
Public Member Functions
void setIdle () override
void setWaiting (double progress=0.0) override
void setWorking (double progress) override
void setFinished () override
Additional Inherited Members
Public Types inherited from ProgressInterface
using Ptr = boost::shared_ptr< ProgressInterface >
using WeakPtr = boost::weak_ptr< ProgressInterface >
Protected Types inherited from Scroom::Utils::ProgressStateInterface
enum State { IDLE, WAITING, WORKING, FINISHED }
using Ptr = boost::shared_ptr< ProgressStateInterface >
using WeakPtr = boost::weak_ptr< ProgressStateInterface >
Protected Member Functions inherited from Scroom::Utils::ProgressStateInterface
virtual void setProgress (State s, double progress=0.0)=0
Detailed Description
Definition at line 42 of file progressinterfacehelpers.hh.
Member Function Documentation
setFinished()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setFinished () override virtual
Implements ProgressInterface.
Definition at line 25 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
 { setProgress(FINISHED, 1.0); }
setIdle()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setIdle () override virtual
Implements ProgressInterface.
Definition at line 19 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
 { setProgress(IDLE); }
setWaiting()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWaiting (double progress = 0.0) override virtual
Implements ProgressInterface.
Definition at line 21 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
 { setProgress(WAITING, progress); }
setWorking()
void Scroom::Utils::ProgressInterfaceFromProgressStateInterface::setWorking (double progress) override virtual
Implements ProgressInterface.
Definition at line 23 of file progressinterfacehelpers.cc.
Referenced by Scroom::Utils::ProgressStateInterfaceFromProgressInterface::setProgress().
 { setProgress(WORKING, progress); }
The documentation for this class was generated from the following files:
inc/scroom/progressinterfacehelpers.hh
libs/util/src/progressinterfacehelpers.cc