Scroom: Scroom::Bitmap::SampleIterator< ConstBase > Class Template Reference
Scroom::Bitmap::SampleIterator< ConstBase > Class Template Reference
Iterate over samples (bits) within a larger type, for example a byte.
#include <bitmap-helpers.hh>
Public Types
using Base = typename std::remove_const< ConstBase >::type
Public Member Functions
SampleIterator (ConstBase *base, int offset=0, int bps_=1)
Construct a new SampleIterator.
Base get ()
Get the value of the current sample.
void set (ConstBase value)
Set the value of the current sample.
SampleIterator & operator++ ()
Move to the next sample.
SampleIterator operator++ (int)
Move to the next sample.
SampleIterator & operator+= (unsigned int x)
Move x samples further.
Base operator* ()
Get the value of the current sample.
bool operator== (const SampleIterator< ConstBase > &other) const
Public Attributes
const int bps
const int samplesPerBase
const int pixelOffset
const ConstBase pixelMask
ConstBase * currentBase
int currentOffset
Static Public Attributes
static const int bitsPerBase {8 * sizeof(ConstBase) / sizeof(byte)}
Private Member Functions
SampleIterator (div_t d, ConstBase *base, int bps_)
Static Private Member Functions
static Base mask (int bps)
Detailed Description
template<typename ConstBase>
class Scroom::Bitmap::SampleIterator< ConstBase >
Iterate over samples (bits) within a larger type, for example a byte.
Allows you to extract (or set) specific bits in a larger datatype, as well as iterate over samples within the larger datatype, or even continuing with the next, if you reach the end of the current one
Parameters
Base the larger type that contains the samples. Typically uint8_t
Definition at line 63 of file bitmap-helpers.hh.
Member Typedef Documentation
Base
template<typename ConstBase> using Scroom::Bitmap::SampleIterator< ConstBase >::Base = typename std::remove_const<ConstBase>::type
Definition at line 66 of file bitmap-helpers.hh.
Constructor & Destructor Documentation
SampleIterator() [1/2]
template<typename ConstBase> Scroom::Bitmap::SampleIterator< ConstBase >::SampleIterator (div_t d, ConstBase * base, int bps_) inline private
Definition at line 81 of file bitmap-helpers.hh.
         : bps(bps_)
         , samplesPerBase(bitsPerBase / bps)
         , pixelOffset(bps)
         , pixelMask(mask(bps))
         , currentBase(base + d.quot)
         , currentOffset(samplesPerBase - 1 - d.rem)
       {}
SampleIterator() [2/2]
template<typename ConstBase> Scroom::Bitmap::SampleIterator< ConstBase >::SampleIterator (ConstBase * base, int offset = 0, int bps_ = 1) inline explicit
Construct a new SampleIterator.
Parameters
base Pointer to the element that contains the current sample
offset number of the sample within that element
bps Number of bits per sample
Definition at line 100 of file bitmap-helpers.hh.
         : SampleIterator(div(offset, /* samplesPerBase */ bitsPerBase / bps_), base, bps_)
       {}
Member Function Documentation
get()
template<typename ConstBase> Base Scroom::Bitmap::SampleIterator< ConstBase >::get () inline
Get the value of the current sample.
Definition at line 105 of file bitmap-helpers.hh.
 { return (*currentBase >> (currentOffset * pixelOffset)) & pixelMask; }
mask()
template<typename ConstBase> static Base Scroom::Bitmap::SampleIterator< ConstBase >::mask (int bps) inline static private
Definition at line 79 of file bitmap-helpers.hh.
 { return (((ConstBase(1) << (bps - 1)) - 1) << 1) | 1; }
operator*()
template<typename ConstBase> Base Scroom::Bitmap::SampleIterator< ConstBase >::operator* () inline
Get the value of the current sample.
Definition at line 153 of file bitmap-helpers.hh.
 { return (*currentBase >> (currentOffset * pixelOffset)) & pixelMask; }
operator++() [1/2]
template<typename ConstBase> SampleIterator& Scroom::Bitmap::SampleIterator< ConstBase >::operator++ () inline
Move to the next sample.
Definition at line 114 of file bitmap-helpers.hh.
       {
         // Prefix operator
         if(!(currentOffset--))
         {
           currentOffset = samplesPerBase - 1;
           ++currentBase;
         }
         return *this;
       }
operator++() [2/2]
template<typename ConstBase> SampleIterator Scroom::Bitmap::SampleIterator< ConstBase >::operator++ (int) inline
Move to the next sample.
Definition at line 127 of file bitmap-helpers.hh.
       {
         // Postfix operator
         SampleIterator<ConstBase> result = *this;
         if(!(currentOffset--))
         {
           currentOffset = samplesPerBase - 1;
           ++currentBase;
         }
         return result;
       }
operator+=()
template<typename ConstBase> SampleIterator& Scroom::Bitmap::SampleIterator< ConstBase >::operator+= (unsigned int x) inline
Move x samples further.
Definition at line 142 of file bitmap-helpers.hh.
       {
         int   offset = samplesPerBase - 1 - currentOffset + x;
         div_t d      = div(offset, samplesPerBase);
         currentBase += d.quot;
         currentOffset = samplesPerBase - 1 - d.rem;
         return *this;
       }
operator==()
template<typename ConstBase> bool Scroom::Bitmap::SampleIterator< ConstBase >::operator== (const SampleIterator< ConstBase > & other) const inline
Definition at line 155 of file bitmap-helpers.hh.
       {
         return currentBase == other.currentBase && currentOffset == other.currentOffset && bps == other.bps;
       }
set()
template<typename ConstBase> void Scroom::Bitmap::SampleIterator< ConstBase >::set (ConstBase value) inline
Set the value of the current sample.
Definition at line 108 of file bitmap-helpers.hh.
Referenced by Operations::reduce(), OperationsColormapped::reduce(), and Operations1bppClipped::reduce().
       {
         *currentBase = (*currentBase & ~(pixelMask << currentOffset * pixelOffset)) | (value << (currentOffset * pixelOffset));
       }
Member Data Documentation
bitsPerBase
template<typename ConstBase> const int Scroom::Bitmap::SampleIterator< ConstBase >::bitsPerBase {8 * sizeof(ConstBase) / sizeof(byte)} static
Definition at line 68 of file bitmap-helpers.hh.
bps
template<typename ConstBase> const int Scroom::Bitmap::SampleIterator< ConstBase >::bps
Definition at line 70 of file bitmap-helpers.hh.
Referenced by Scroom::Bitmap::SampleIterator< ConstBase >::operator==().
currentBase
template<typename ConstBase> ConstBase* Scroom::Bitmap::SampleIterator< ConstBase >::currentBase
Definition at line 75 of file bitmap-helpers.hh.
Referenced by Scroom::Bitmap::SampleIterator< ConstBase >::operator==().
currentOffset
template<typename ConstBase> int Scroom::Bitmap::SampleIterator< ConstBase >::currentOffset
Definition at line 76 of file bitmap-helpers.hh.
Referenced by Scroom::Bitmap::SampleIterator< ConstBase >::operator==().
pixelMask
template<typename ConstBase> const ConstBase Scroom::Bitmap::SampleIterator< ConstBase >::pixelMask
Definition at line 73 of file bitmap-helpers.hh.
pixelOffset
template<typename ConstBase> const int Scroom::Bitmap::SampleIterator< ConstBase >::pixelOffset
Definition at line 72 of file bitmap-helpers.hh.
samplesPerBase
template<typename ConstBase> const int Scroom::Bitmap::SampleIterator< ConstBase >::samplesPerBase
Definition at line 71 of file bitmap-helpers.hh.
The documentation for this class was generated from the following file:
inc/scroom/bitmap-helpers.hh