Scroom: ColormapHelperBase Class Reference
ColormapHelperBase Class Reference abstract
#include <colormappable.hh>
Public Types
using Ptr = boost::shared_ptr< ColormapHelperBase >
Public Types inherited from ColormapProvider
using Ptr = boost::shared_ptr< ColormapProvider >
Public Types inherited from Colormappable
using Ptr = boost::shared_ptr< Colormappable >
using WeakPtr = boost::weak_ptr< Colormappable >
Public Member Functions
ColormapHelperBase (Colormap::Ptr const &colormap)
virtual std::map< std::string, std::string > getProperties ()=0
void setColormap (Colormap::Ptr colormap) override
Request that the presentation use the given colormap.
Colormap::Ptr getOriginalColormap () override
Retrieve the images colormap (if any)
int getNumberOfColors () override
Retrieve the number of colors in use by the presentation.
Color getMonochromeColor () override
void setMonochromeColor (const Color &c) override
void setTransparentBackground () override
void disableTransparentBackground () override
bool getTransparentBackground () override
Colormap::Ptr getColormap () override
virtual void setOriginalColormap (Colormap::Ptr colormap)
For monochrome presentations: Set/Get the current color
Manipulate the "Transparent Background" setting of the presentation
Public Attributes
Colormap::Ptr colormap
Colormap::Ptr originalColormap
Static Private Member Functions
static void OperationNotSupported ()
Detailed Description
Definition at line 154 of file colormappable.hh.
Member Typedef Documentation
Ptr
using ColormapHelperBase::Ptr = boost::shared_ptr<ColormapHelperBase>
Definition at line 159 of file colormappable.hh.
Constructor & Destructor Documentation
ColormapHelperBase()
ColormapHelperBase::ColormapHelperBase (Colormap::Ptr const & colormap) explicit
Definition at line 17 of file colormap-helpers.cc.
   : colormap(colormap_)
   , originalColormap(colormap_)
 {}
Member Function Documentation
disableTransparentBackground()
void ColormapHelperBase::disableTransparentBackground () override virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 40 of file colormap-helpers.cc.
 { OperationNotSupported(); }
getColormap()
Colormap::Ptr ColormapHelperBase::getColormap () override virtual
Implements ColormapProvider.
Definition at line 44 of file colormap-helpers.cc.
 { return colormap; }
getMonochromeColor()
Color ColormapHelperBase::getMonochromeColor () override virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 30 of file colormap-helpers.cc.
 { OperationNotSupported(); }
getNumberOfColors()
int ColormapHelperBase::getNumberOfColors () override virtual
Retrieve the number of colors in use by the presentation.
Implements Colormappable.
Definition at line 28 of file colormap-helpers.cc.
 { return originalColormap->colors.size(); }
getOriginalColormap()
Colormap::Ptr ColormapHelperBase::getOriginalColormap () override virtual
Retrieve the images colormap (if any)
Implements Colormappable.
Definition at line 26 of file colormap-helpers.cc.
 { return originalColormap; }
getProperties()
virtual std::map<std::string, std::string> ColormapHelperBase::getProperties () pure virtual
Implemented in MonochromeColormapHelper, and ColormapHelper.
getTransparentBackground()
bool ColormapHelperBase::getTransparentBackground () override virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 42 of file colormap-helpers.cc.
 { OperationNotSupported(); }
OperationNotSupported()
void ColormapHelperBase::OperationNotSupported () static private
Definition at line 46 of file colormap-helpers.cc.
Referenced by disableTransparentBackground(), getMonochromeColor(), getTransparentBackground(), setMonochromeColor(), and setTransparentBackground().
 { throw std::runtime_error("Operation not supported"); }
setColormap()
void ColormapHelperBase::setColormap (Colormap::Ptr colormap) override virtual
Request that the presentation use the given colormap.
Implements Colormappable.
Definition at line 22 of file colormap-helpers.cc.
 { colormap = colormap_; }
setMonochromeColor()
void ColormapHelperBase::setMonochromeColor (const Color & c) override virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 32 of file colormap-helpers.cc.
 {
   UNUSED(c);
   OperationNotSupported();
 }
setOriginalColormap()
void ColormapHelperBase::setOriginalColormap (Colormap::Ptr colormap) virtual
Definition at line 24 of file colormap-helpers.cc.
 { originalColormap = colormap_; }
setTransparentBackground()
void ColormapHelperBase::setTransparentBackground () override virtual
Implements Colormappable.
Reimplemented in MonochromeColormapHelper.
Definition at line 38 of file colormap-helpers.cc.
 { OperationNotSupported(); }
Member Data Documentation
colormap
Colormap::Ptr ColormapHelperBase::colormap
Definition at line 162 of file colormappable.hh.
Referenced by getColormap(), MonochromeColormapHelper::regenerateColormap(), and setColormap().
originalColormap
Colormap::Ptr ColormapHelperBase::originalColormap
Definition at line 163 of file colormappable.hh.
Referenced by getNumberOfColors(), getOriginalColormap(), and setOriginalColormap().
The documentation for this class was generated from the following files:
inc/scroom/colormappable.hh
libs/scroom/src/colormap-helpers.cc