Scroom: PresentationInterface Class Reference
PresentationInterface Class Reference abstract
Represent some 2D content.
#include <presentationinterface.hh>
Public Types
using Ptr = boost::shared_ptr< PresentationInterface >
using WeakPtr = boost::weak_ptr< PresentationInterface >
Public Types inherited from Viewable
using Ptr = boost::shared_ptr< Viewable >
using WeakPtr = boost::weak_ptr< Viewable >
Public Types inherited from Scroom::Utils::Observable< T >
using Observer = boost::shared_ptr< T >
using Ptr = boost::shared_ptr< Observable< T > >
Public Member Functions
virtual Scroom::Utils::Rectangle< double > getRect ()=0
Return the dimensions of your presentation.
virtual void redraw (ViewInterface::Ptr const &vi, cairo_t *cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom)=0
Draw the requested ara at the requested zoom level.
virtual bool getProperty (const std::string &name, std::string &value)=0
Return the value of the requested property.
virtual bool isPropertyDefined (const std::string &name)=0
Return true if the named property exists.
virtual std::string getTitle ()=0
Return the title of the presentation.
virtual Scroom::Utils::Point< double > getAspectRatio () const
Public Member Functions inherited from Viewable
virtual void open (ViewInterface::WeakPtr vi)=0
Gets called just after the View is created.
virtual void close (ViewInterface::WeakPtr vi)=0
Gets called just before the View is destroyed.
Public Member Functions inherited from Scroom::Utils::Observable< T >
Observable ()
~Observable () override
Observable (const Observable &)=delete
Observable (Observable &&)=delete
Observable operator= (const Observable &)=delete
Observable operator= (Observable &&)=delete
Scroom::Bookkeeping::Token registerStrongObserver (Observer const &observer)
Scroom::Bookkeeping::Token registerObserver (ObserverWeak const &observer)
Public Member Functions inherited from Scroom::Utils::Base
Base ()=default
Base (const Base &)=delete
Base (Base &&)=delete
Base & operator= (const Base &)=delete
Base & operator= (Base &&)=delete
virtual ~Base ()=default
template<typename R >
boost::shared_ptr< R > shared_from_this ()
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
Additional Inherited Members
Protected Member Functions inherited from Scroom::Utils::Observable< T >
std::list< Observer > getObservers ()
Retrieve a list of current observers.
virtual void observerAdded (Observer const &observer, Scroom::Bookkeeping::Token const &token)
Override this function if you want to be notified of new observers registering.
Detailed Description
Represent some 2D content.
Anything that should be shown by Scroom in a window should implement this interface.
Objects implementing this interface are typically returned by NewPresentationInterface::createNew() and OpenPresentationInterface::open().
Definition at line 69 of file presentationinterface.hh.
Member Typedef Documentation
Ptr
using PresentationInterface::Ptr = boost::shared_ptr<PresentationInterface>
Definition at line 74 of file presentationinterface.hh.
WeakPtr
using PresentationInterface::WeakPtr = boost::weak_ptr<PresentationInterface>
Definition at line 75 of file presentationinterface.hh.
Member Function Documentation
getAspectRatio()
virtual Scroom::Utils::Point<double> PresentationInterface::getAspectRatio () const inline virtual
Reimplemented in TransformPresentation.
Definition at line 110 of file presentationinterface.hh.
 { return Scroom::Utils::make_point(1.0, 1.0); }
getProperty()
virtual bool PresentationInterface::getProperty (const std::string & name, std::string & value) pure virtual
Return the value of the requested property.
Parameters
[in] name The name of the requested property
[out] value The value of the requested property
Return values
true if the property existed
false if the property didn't exist
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
getRect()
virtual Scroom::Utils::Rectangle<double> PresentationInterface::getRect () pure virtual
Return the dimensions of your presentation.
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
getTitle()
virtual std::string PresentationInterface::getTitle () pure virtual
Return the title of the presentation.
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
isPropertyDefined()
virtual bool PresentationInterface::isPropertyDefined (const std::string & name) pure virtual
Return true if the named property exists.
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
redraw()
virtual void PresentationInterface::redraw (ViewInterface::Ptr const & vi, cairo_t * cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom) pure virtual
Draw the requested ara at the requested zoom level.
Parameters
vi The ViewInterface on whose behalf the request is made
cr The context to draw the area on
presentationArea the area that is to be drawn. The given x and y coordinates should map on 0,0 of the given context cr.
zoom The requested zoom level. One pixel of your presentation should have size 2**zoom when drawn. zoom may be negative.
Implemented in anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation, TransformPresentation, and TransparentOverlayPresentation.
Referenced by PresentationMock::create().
The documentation for this class was generated from the following file:
inc/scroom/presentationinterface.hh