Scroom: Scroom::Bookkeeping::Token Class Reference
Scroom::Bookkeeping::Token Class Reference
#include <bookkeeping.hh>
Public Member Functions
Token (const boost::shared_ptr< Detail::TokenImpl > &t)
Token (const boost::weak_ptr< Detail::TokenImpl > &t)
Token ()
Token (const Stuff &s)
Token (const StuffList &l)
void add (const Stuff &s) const
void add (const StuffList &l) const
void merge (Token &rhs) const
void merge (StuffList &l) const
Detail::TokenAddition operator+ (const Stuff &rhs) const
Token const & operator+= (const Stuff &rhs) const
Detailed Description
Definition at line 39 of file bookkeeping.hh.
Constructor & Destructor Documentation
Token() [1/5]
Scroom::Bookkeeping::Token::Token (const boost::shared_ptr< Detail::TokenImpl > & t) inline
Definition at line 161 of file bookkeepingimpl.hh.
       : boost::shared_ptr<Detail::TokenImpl>(t)
     {}
Token() [2/5]
Scroom::Bookkeeping::Token::Token (const boost::weak_ptr< Detail::TokenImpl > & t) inline
Definition at line 165 of file bookkeepingimpl.hh.
       : boost::shared_ptr<Detail::TokenImpl>(t)
     {}
Token() [3/5]
Scroom::Bookkeeping::Token::Token () inline
Definition at line 169 of file bookkeepingimpl.hh.
       : boost::shared_ptr<Detail::TokenImpl>(Detail::TokenImpl::create())
     {}
Token() [4/5]
Scroom::Bookkeeping::Token::Token (const Stuff & s) inline
Definition at line 173 of file bookkeepingimpl.hh.
       : boost::shared_ptr<Detail::TokenImpl>(Detail::TokenImpl::create())
     {
       get()->add(s);
     }
Token() [5/5]
Scroom::Bookkeeping::Token::Token (const StuffList & l) inline
Definition at line 179 of file bookkeepingimpl.hh.
       : boost::shared_ptr<Detail::TokenImpl>(Detail::TokenImpl::create())
     {
       get()->add(l);
     }
Member Function Documentation
add() [1/2]
void Scroom::Bookkeeping::Token::add (const Stuff & s) const inline
Definition at line 185 of file bookkeepingimpl.hh.
Referenced by add(), CompressedTile::observerAdded(), on_view_created(), Scroom::Bookkeeping::Detail::TokenAddition::operator+(), Scroom::Bookkeeping::Detail::TokenAddition::operator+=(), operator+=(), Layer::registerObserver(), Scroom::Bookkeeping::MapBase< ObserverWeak, typename Registration::Ptr >::reReserve(), Scroom::Bookkeeping::MapBase< ObserverWeak, typename Registration::Ptr >::reserve(), and Token().
 { get()->add(s); }
add() [2/2]
void Scroom::Bookkeeping::Token::add (const StuffList & l) const inline
Definition at line 187 of file bookkeepingimpl.hh.
 { get()->add(l); }
merge() [1/2]
void Scroom::Bookkeeping::Token::merge (Token & rhs) const inline
Definition at line 189 of file bookkeepingimpl.hh.
Referenced by merge(), Scroom::Bookkeeping::Detail::TokenAddition::operator+(), and Scroom::Bookkeeping::Detail::TokenAddition::operator+=().
 { get()->merge(rhs); }
merge() [2/2]
void Scroom::Bookkeeping::Token::merge (StuffList & l) const inline
Definition at line 191 of file bookkeepingimpl.hh.
 { get()->merge(l); }
operator+()
Detail::TokenAddition Scroom::Bookkeeping::Token::operator+ (const Stuff & rhs) const inline
Definition at line 193 of file bookkeepingimpl.hh.
 { return Detail::TokenAddition(*this) + rhs; }
operator+=()
Token const & Scroom::Bookkeeping::Token::operator+= (const Stuff & rhs) const inline
Definition at line 195 of file bookkeepingimpl.hh.
     {
       add(rhs);
       return *this;
     }
The documentation for this class was generated from the following files:
inc/scroom/bookkeeping.hh
inc/scroom/impl/bookkeepingimpl.hh