Scroom: MeasureHandler Class Reference
MeasureHandler Class Reference
#include <measure.hh>
Public Types
using Ptr = boost::shared_ptr< MeasureHandler >
Public Types inherited from ToolStateListener
using Ptr = boost::shared_ptr< ToolStateListener >
Public Types inherited from PostRenderer
using Ptr = boost::shared_ptr< PostRenderer >
Public Types inherited from SelectionListener
using Ptr = boost::shared_ptr< SelectionListener >
Public Member Functions
MeasureHandler ()
void render (ViewInterface::Ptr const &vi, cairo_t *cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom) override
void onSelectionStart (GdkPoint p, ViewInterface::Ptr view) override
void onSelectionUpdate (Selection::Ptr s, ViewInterface::Ptr view) override
void onSelectionEnd (Selection::Ptr s, ViewInterface::Ptr view) override
void onEnable () override
This function is called whenever the tool button is selected.
void onDisable () override
Then function is called whenever the tool button is deselected.
Public Member Functions inherited from PostRenderer
virtual void render (boost::shared_ptr< ViewInterface > const &vi, cairo_t *cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom)=0
This function is called after the presentation finishes redrawing.
Public Member Functions inherited from SelectionListener
virtual void onSelectionStart (GdkPoint start, boost::shared_ptr< ViewInterface > view)=0
This function is called whenever the user clicks a view.
virtual void onSelectionUpdate (Selection::Ptr selection, boost::shared_ptr< ViewInterface > view)=0
This function is called whenever the selection updates.
virtual void onSelectionEnd (Selection::Ptr selection, boost::shared_ptr< ViewInterface > view)=0
This function is called whenever the selection ends.
Public Member Functions inherited from Scroom::Utils::Base
Base ()=default
Base (const Base &)=delete
Base (Base &&)=delete
Base & operator= (const Base &)=delete
Base & operator= (Base &&)=delete
virtual ~Base ()=default
template<typename R >
boost::shared_ptr< R > shared_from_this ()
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
Static Public Member Functions
static Ptr create ()
Private Member Functions
virtual void displayMeasurement (ViewInterface::Ptr view)
virtual void drawCross (cairo_t *cr, Scroom::Utils::Point< double > p)
Private Attributes
Selection::Ptr selection
bool enabled {false}
Detailed Description
Definition at line 15 of file measure.hh.
Member Typedef Documentation
Ptr
using MeasureHandler::Ptr = boost::shared_ptr<MeasureHandler>
Definition at line 25 of file measure.hh.
Constructor & Destructor Documentation
MeasureHandler()
MeasureHandler::MeasureHandler ()
Definition at line 58 of file measure.cc.
Referenced by create().
   : selection(nullptr)
 {}
Member Function Documentation
create()
MeasureHandler::Ptr MeasureHandler::create () static
Definition at line 63 of file measure.cc.
Referenced by Measure::viewAdded().
 { return Ptr(new MeasureHandler()); }
displayMeasurement()
void MeasureHandler::displayMeasurement (ViewInterface::Ptr view) private virtual
Definition at line 65 of file measure.cc.
Referenced by onSelectionEnd(), and onSelectionUpdate().
 {
   std::ostringstream s;
   s.precision(1);
   fixed(s);
   s << "l: " << selection->length() << ", dx: " << selection->width() << ", dy: " << selection->height() << ", from: ("
     << selection->start.x << "," << selection->start.y << ")"
     << ", to: (" << selection->end.x << "," << selection->end.y << ")";
   view->setStatusMessage(s.str());
 }
drawCross()
void MeasureHandler::drawCross (cairo_t * cr, Scroom::Utils::Point< double > p) private virtual
Definition at line 78 of file measure.cc.
Referenced by render().
 {
   static const int size = 10;
   cairo_move_to(cr, p.x - size, p.y);
   cairo_line_to(cr, p.x + size, p.y);
   cairo_move_to(cr, p.x, p.y - size);
   cairo_line_to(cr, p.x, p.y + size);
 }
onDisable()
void MeasureHandler::onDisable () override virtual
Then function is called whenever the tool button is deselected.
Implements ToolStateListener.
Definition at line 161 of file measure.cc.
 {
   selection = nullptr;
   enabled   = false;
 }
onEnable()
void MeasureHandler::onEnable () override virtual
This function is called whenever the tool button is selected.
Implements ToolStateListener.
Definition at line 167 of file measure.cc.
 { enabled = true; }
onSelectionEnd()
void MeasureHandler::onSelectionEnd (Selection::Ptr s, ViewInterface::Ptr view) override
Definition at line 102 of file measure.cc.
 {
   if(enabled)
   {
     selection = s;
     displayMeasurement(view);
   }
 }
onSelectionStart()
void MeasureHandler::onSelectionStart (GdkPoint p, ViewInterface::Ptr view) override
Definition at line 91 of file measure.cc.
 {}
onSelectionUpdate()
void MeasureHandler::onSelectionUpdate (Selection::Ptr s, ViewInterface::Ptr view) override
Definition at line 93 of file measure.cc.
 {
   if(enabled)
   {
     selection = s;
     displayMeasurement(view);
   }
 }
render()
void MeasureHandler::render (ViewInterface::Ptr const & vi, cairo_t * cr, Scroom::Utils::Rectangle< double > presentationArea, int zoom) override
Definition at line 115 of file measure.cc.
 {
   UNUSED(vi);
   if(selection)
   {
     auto aspectRatio = vi->getCurrentPresentation()->getAspectRatio();
     auto start       = Scroom::Utils::Point<int>(selection->start) - presentationArea.getTopLeft();
     auto end         = Scroom::Utils::Point<int>(selection->end) - presentationArea.getTopLeft();
     if(zoom >= 0)
     {
       const int pixelSize = 1 << zoom;
       start *= pixelSize;
       start *= aspectRatio;
       end *= pixelSize;
       end *= aspectRatio;
     }
     else
     {
       const int pixelSize = 1 << -zoom;
       start *= aspectRatio;
       start /= pixelSize;
       end *= aspectRatio;
       end /= pixelSize;
     }
     cairo_set_line_width(cr, 1);
     cairo_set_source_rgb(cr, 0.75, 0, 0); // Dark Red
     drawCross(cr, start);
     drawCross(cr, end);
     cairo_stroke(cr);
     cairo_set_source_rgb(cr, 1, 0, 0); // Red
     cairo_move_to(cr, start.x, start.y);
     cairo_line_to(cr, end.x, end.y);
     cairo_stroke(cr);
   }
 }
Member Data Documentation
enabled
bool MeasureHandler::enabled {false} private
Definition at line 29 of file measure.hh.
Referenced by onDisable(), onEnable(), onSelectionEnd(), and onSelectionUpdate().
selection
Selection::Ptr MeasureHandler::selection private
Definition at line 28 of file measure.hh.
Referenced by displayMeasurement(), onDisable(), onSelectionEnd(), onSelectionUpdate(), and render().
The documentation for this class was generated from the following files:
plugins/measure/src/measure.hh
plugins/measure/src/measure.cc