Scroom: Scroom::Bitmap::BitmapSurface Class Reference
Scroom::Bitmap::BitmapSurface Class Reference
#include <bitmap-helpers.hh>
Public Types
using Ptr = boost::shared_ptr< BitmapSurface >
Public Member Functions
~BitmapSurface ()
BitmapSurface (const BitmapSurface &)=delete
BitmapSurface (BitmapSurface &&)=delete
BitmapSurface & operator= (const BitmapSurface &)=delete
BitmapSurface & operator= (BitmapSurface &&)=delete
cairo_surface_t * get ()
Static Public Member Functions
static Ptr create (int width, int height, cairo_format_t format)
static Ptr create (int width, int height, cairo_format_t format, int stride, boost::shared_ptr< unsigned char > const &data)
Private Member Functions
BitmapSurface (int width, int height, cairo_format_t format)
BitmapSurface (int width, int height, cairo_format_t format, int stride, boost::shared_ptr< unsigned char > const &data)
Private Attributes
cairo_surface_t *const surface
boost::shared_ptr< unsigned char > const data
Detailed Description
Definition at line 24 of file bitmap-helpers.hh.
Member Typedef Documentation
Ptr
using Scroom::Bitmap::BitmapSurface::Ptr = boost::shared_ptr<BitmapSurface>
Definition at line 27 of file bitmap-helpers.hh.
Constructor & Destructor Documentation
~BitmapSurface()
Scroom::Bitmap::BitmapSurface::~BitmapSurface ()
Definition at line 29 of file bitmap-helpers.cc.
 { cairo_surface_destroy(surface); }
BitmapSurface() [1/4]
Scroom::Bitmap::BitmapSurface::BitmapSurface (const BitmapSurface &) delete
Referenced by create().
BitmapSurface() [2/4]
Scroom::Bitmap::BitmapSurface::BitmapSurface (BitmapSurface &&) delete
BitmapSurface() [3/4]
Scroom::Bitmap::BitmapSurface::BitmapSurface (int width, int height, cairo_format_t format) private
Definition at line 33 of file bitmap-helpers.cc.
       : surface(cairo_image_surface_create(format, width, height))
     {}
BitmapSurface() [4/4]
Scroom::Bitmap::BitmapSurface::BitmapSurface (int width, int height, cairo_format_t format, int stride, boost::shared_ptr< unsigned char > const & data) private
Definition at line 37 of file bitmap-helpers.cc.
       : surface(cairo_image_surface_create_for_data(data_.get(), format, width, height, stride))
       , data(data_)
     {}
Member Function Documentation
create() [1/2]
BitmapSurface::Ptr Scroom::Bitmap::BitmapSurface::create (int width, int height, cairo_format_t format) static
Definition at line 15 of file bitmap-helpers.cc.
Referenced by OperationsCMYK32::cache(), OperationsCMYK16::cache(), OperationsCMYK8::cache(), OperationsCMYK4::cache(), and CommonOperations::cacheZoom().
     {
       return BitmapSurface::Ptr(new BitmapSurface(width, height, format));
     }
create() [2/2]
BitmapSurface::Ptr Scroom::Bitmap::BitmapSurface::create (int width, int height, cairo_format_t format, int stride, boost::shared_ptr< unsigned char > const & data) static
Definition at line 20 of file bitmap-helpers.cc.
     {
       return BitmapSurface::Ptr(new BitmapSurface(width, height, format, stride, data));
     }
get()
cairo_surface_t * Scroom::Bitmap::BitmapSurface::get ()
Definition at line 31 of file bitmap-helpers.cc.
 { return surface; }
operator=() [1/2]
BitmapSurface& Scroom::Bitmap::BitmapSurface::operator= (const BitmapSurface &) delete
operator=() [2/2]
BitmapSurface& Scroom::Bitmap::BitmapSurface::operator= (BitmapSurface &&) delete
Member Data Documentation
data
boost::shared_ptr<unsigned char> const Scroom::Bitmap::BitmapSurface::data private
Definition at line 31 of file bitmap-helpers.hh.
surface
cairo_surface_t* const Scroom::Bitmap::BitmapSurface::surface private
Definition at line 30 of file bitmap-helpers.hh.
Referenced by get(), and ~BitmapSurface().
The documentation for this class was generated from the following files:
inc/scroom/bitmap-helpers.hh
libs/scroom/src/bitmap-helpers.cc