Scroom: inc/scroom/color.hh File Reference
color.hh File Reference
#include <cmath>
#include <cstdint>
#include <boost/operators.hpp>
#include <gdk/gdk.h>
#include <cairo.h>
Classes
class Color
Represent a (ARGB) color.
Namespaces
anonymous_namespace{color.hh}
Functions
uint8_t byteFromDouble (double d)
double doubleFromByte (uint8_t b)
uint16_t shortFromDouble (double d)
double anonymous_namespace{color.hh}::computeC (double c)
Color mix (const Color &a, const Color &b, double alpha)
Function Documentation
byteFromDouble()
uint8_t byteFromDouble (double d) inline
Definition at line 19 of file color.hh.
Referenced by Color::getARGB32(), and Color::getRGB24().
 { return uint8_t(255 * d); }
doubleFromByte()
double doubleFromByte (uint8_t b) inline
Definition at line 20 of file color.hh.
 { return b / 255.0; }
mix()
Color mix (const Color & a, const Color & b, double alpha) inline
Definition at line 115 of file color.hh.
Referenced by Operations8bpp::cache(), OperationsColormapped::cache(), Operations8bpp::draw(), and MonochromeColormapHelper::regenerateColormap().
 { return a * alpha + b * (1.0 - alpha); }
shortFromDouble()
uint16_t shortFromDouble (double d) inline
Definition at line 21 of file color.hh.
Referenced by Color::getGdkColor().
 { return uint16_t(0xFFFF * d); }