Scroom: gui/src/loader.cc File Reference
loader.cc File Reference
#include "loader.hh"
#include <cstdio>
#include <boost/filesystem.hpp>
#include <scroom/threadpool.hh>
#include "callbacks.hh"
#include "pluginmanager.hh"
Classes
class GObjectUnref< T >
class GtkFileFilterInfoDeleter
class GtkFileFilterListDestroyer
class ScroomInterfaceImpl
Typedefs
using GtkFileFilterInfoPtr = std::unique_ptr< GtkFileFilterInfo, GtkFileFilterInfoDeleter >
Functions
void destroyGtkFileFilterList (std::list< GtkFileFilter *> &l)
char * charpFromString (std::string const &s)
GtkFileFilterInfoPtr filterInfoFromPath (const std::string &filename)
bool filterMatchesInfo (GtkFileFilterInfo const &info, std::list< GtkFileFilter *> const &filters)
void create (NewPresentationInterface *interface)
PresentationInterface::Ptr loadPresentation (const std::string &filename)
PresentationInterface::Ptr loadPresentation (GtkFileFilterInfo const &info)
PresentationInterface::Ptr loadPresentation (GtkFileFilterInfoPtr const &info)
void load (GtkFileFilterInfo const &info)
void load (GtkFileFilterInfoPtr const &info)
void load (const std::string &filename)
Typedef Documentation
GtkFileFilterInfoPtr
using GtkFileFilterInfoPtr = std::unique_ptr<GtkFileFilterInfo, GtkFileFilterInfoDeleter>
Definition at line 44 of file loader.cc.
Function Documentation
charpFromString()
char* charpFromString (std::string const & s)
Definition at line 91 of file loader.cc.
Referenced by filterInfoFromPath().
 {
   size_t                  n = s.size();
   std::unique_ptr<char[]> result(new char[n + 1]);
   if(!result)
   {
     throw std::bad_alloc();
   }
   strncpy(result.get(), s.c_str(), n + 1);
   if(result[n] != 0)
   {
     throw std::length_error("String size changed during copying");
   }
   return result.release();
 }
create()
void create (NewPresentationInterface * interface)
Definition at line 175 of file loader.cc.
Referenced by Operations1bpp::cache(), Operations8bpp::cache(), Operations24bpp::cache(), Operations::cache(), OperationsColormapped::cache(), Operations1bppClipped::cacheZoom(), ColormapHelper::create(), ColormapHelper::createInverted(), on_new_activate(), anonymous_namespace{tiledbitmappresentation.cc}::OpenTiledBitmapAsPresentation::open(), TransparentOverlayViewInfo::redraw(), Scroom::Utils::ProgressInterfaceBroadcaster::subscribe(), and Scroom::TiledBitmap::ToOpenPresentationInterface().
 {
   PresentationInterface::Ptr presentation = interface->createNew();
   if(presentation)
   {
     on_presentation_created(presentation);
     find_or_create_scroom(presentation);
   }
   else
   {
     throw std::invalid_argument("Unable to create requested presentation");
   }
 }
destroyGtkFileFilterList()
void destroyGtkFileFilterList (std::list< GtkFileFilter *> & l)
Definition at line 46 of file loader.cc.
 {
   while(!l.empty())
   {
     GtkFileFilter* f = l.front();
     g_object_ref_sink(f);
     g_object_unref(f);
     l.pop_front();
   }
 }
filterInfoFromPath()
GtkFileFilterInfoPtr filterInfoFromPath (const std::string & filename)
Definition at line 109 of file loader.cc.
Referenced by load(), and loadPresentation().
 {
   GtkFileFilterInfoPtr filterInfo;
   std::unique_ptr<GFile, GObjectUnref<GFile>>         file(g_file_new_for_path(filename.c_str()));
   std::unique_ptr<GFileInfo, GObjectUnref<GFileInfo>> fileInfo(
     g_file_query_info(file.get(), "standard::*", G_FILE_QUERY_INFO_NONE, nullptr, nullptr));
   if(fileInfo)
   {
     // g_file_info_get_name(fileInfo) doesn't provide path info.
     // charpFromString might throw.
     std::unique_ptr<gchar> filenameCopy(charpFromString(filename));
     std::unique_ptr<gchar> mime_type(charpFromString(g_content_type_get_mime_type(g_file_info_get_content_type(fileInfo.get()))));
     std::unique_ptr<gchar> display_name(charpFromString(g_file_info_get_display_name(fileInfo.get())));
     filterInfo.reset(new GtkFileFilterInfo()); // filterInfo->filename uninitialized, so a delete is dangerous
     filterInfo->filename     = filenameCopy.release();
     filterInfo->mime_type    = mime_type.release();
     filterInfo->display_name = display_name.release();
     filterInfo->contains =
       static_cast<GtkFileFilterFlags>(GTK_FILE_FILTER_FILENAME | GTK_FILE_FILTER_DISPLAY_NAME | GTK_FILE_FILTER_MIME_TYPE);
   }
   else
   {
     throw std::invalid_argument("No fileinfo for file " + filename);
   }
   return filterInfo;
 }
filterMatchesInfo()
bool filterMatchesInfo (GtkFileFilterInfo const & info, std::list< GtkFileFilter *> const & filters)
Definition at line 140 of file loader.cc.
Referenced by load(), and loadPresentation().
 {
   for(auto const& f: filters)
   {
     if(gtk_file_filter_filter(f, &info))
     {
       return true;
     }
   }
   return false;
 }
load() [1/3]
void load (GtkFileFilterInfo const & info)
Definition at line 240 of file loader.cc.
Referenced by load(), on_done_loading_plugins(), on_open_activate(), onDragDataReceived(), Tiff::open(), and anonymous_namespace{tiledbitmappresentation.cc}::OpenTiledBitmapAsPresentation::open().
 {
   const auto  pm                         = PluginManager::getInstance();
   const auto& openPresentationInterfaces = pm->getOpenPresentationInterfaces();
   const auto& openInterfaces             = pm->getOpenInterfaces();
   for(auto const& cur: openPresentationInterfaces)
   {
     std::list<GtkFileFilter*>  filters = cur.first->getFilters();
     GtkFileFilterListDestroyer destroyer(filters);
     if(filterMatchesInfo(info, filters))
     {
       PresentationInterface::Ptr presentation = cur.first->open(info.filename);
       if(presentation)
       {
         on_presentation_created(presentation);
         find_or_create_scroom(presentation);
         return;
       }
     }
   }
   for(auto const& cur: openInterfaces)
   {
     std::list<GtkFileFilter*>  filters = cur.first->getFilters();
     GtkFileFilterListDestroyer destroyer(filters);
     if(filterMatchesInfo(info, filters))
     {
       cur.first->open(info.filename, ScroomInterfaceImpl::instance());
       return;
     }
   }
   throw std::invalid_argument("Don't know how to open file " + std::string(info.filename));
 }
load() [2/3]
void load (GtkFileFilterInfoPtr const & info)
Definition at line 275 of file loader.cc.
 { load(*info); }
load() [3/3]
void load (const std::string & filename)
Definition at line 277 of file loader.cc.
 { load(filterInfoFromPath(filename)); }
loadPresentation() [1/3]
PresentationInterface::Ptr loadPresentation (const std::string & filename)
Definition at line 189 of file loader.cc.
Referenced by loadPresentation(), ScroomInterfaceImpl::loadPresentation(), and on_done_loading_plugins().
 {
   return loadPresentation(*filterInfoFromPath(filename));
 }
loadPresentation() [2/3]
PresentationInterface::Ptr loadPresentation (GtkFileFilterInfo const & info)
Definition at line 194 of file loader.cc.
 {
   static std::map<boost::filesystem::path, PresentationInterface::WeakPtr> loadedPresentations;
   // Create canonical path from filename
   const std::map<OpenPresentationInterface::Ptr, std::string>& openPresentationInterfaces =
     PluginManager::getInstance()->getOpenPresentationInterfaces();
 #ifdef HAVE_BOOST_FILESYSTEM_CANONICAL
   boost::filesystem::path key(canonical(boost::filesystem::path(info.filename)));
 #else
   boost::filesystem::path key(absolute(boost::filesystem::path(info.filename)));
 #endif
   PresentationInterface::Ptr presentation = loadedPresentations[key].lock();
   if(!presentation)
   {
     for(auto const& cur: openPresentationInterfaces)
     {
       std::list<GtkFileFilter*> filters = cur.first->getFilters();
       if(filterMatchesInfo(info, filters))
       {
         presentation = cur.first->open(info.filename);
         if(presentation)
         {
           loadedPresentations[key] = presentation;
           on_presentation_created(presentation);
           break;
         }
       }
     }
   }
   if(presentation)
   {
     return presentation;
   }
   else
   {
     throw std::invalid_argument("Don't know how to load presentation " + std::string(info.filename));
   }
 }
loadPresentation() [3/3]
PresentationInterface::Ptr loadPresentation (GtkFileFilterInfoPtr const & info)
Definition at line 238 of file loader.cc.
 { return loadPresentation(*info); }