Scroom: gui/src/loader.hh File Reference
loader.hh File Reference
#include <gtk/gtk.h>
#include <scroom/scroominterface.hh>
Functions
void create (NewPresentationInterface *interface)
void load (const GtkFileFilterInfo &info)
void load (const std::string &filename)
PresentationInterface::Ptr loadPresentation (const GtkFileFilterInfo &info)
PresentationInterface::Ptr loadPresentation (const std::string &filename)
void destroyGtkFileFilterList (std::list< GtkFileFilter *> &l)
Function Documentation
create()
void create (NewPresentationInterface * interface)
Definition at line 175 of file loader.cc.
Referenced by Operations1bpp::cache(), Operations8bpp::cache(), Operations24bpp::cache(), Operations::cache(), OperationsColormapped::cache(), Operations1bppClipped::cacheZoom(), ColormapHelper::create(), ColormapHelper::createInverted(), on_new_activate(), anonymous_namespace{tiledbitmappresentation.cc}::OpenTiledBitmapAsPresentation::open(), TransparentOverlayViewInfo::redraw(), Scroom::Utils::ProgressInterfaceBroadcaster::subscribe(), and Scroom::TiledBitmap::ToOpenPresentationInterface().
 {
   PresentationInterface::Ptr presentation = interface->createNew();
   if(presentation)
   {
     on_presentation_created(presentation);
     find_or_create_scroom(presentation);
   }
   else
   {
     throw std::invalid_argument("Unable to create requested presentation");
   }
 }
destroyGtkFileFilterList()
void destroyGtkFileFilterList (std::list< GtkFileFilter *> & l)
Definition at line 46 of file loader.cc.
 {
   while(!l.empty())
   {
     GtkFileFilter* f = l.front();
     g_object_ref_sink(f);
     g_object_unref(f);
     l.pop_front();
   }
 }
load() [1/2]
void load (const GtkFileFilterInfo & info)
Definition at line 240 of file loader.cc.
Referenced by load(), on_done_loading_plugins(), on_open_activate(), onDragDataReceived(), Tiff::open(), and anonymous_namespace{tiledbitmappresentation.cc}::OpenTiledBitmapAsPresentation::open().
 {
   const auto  pm                         = PluginManager::getInstance();
   const auto& openPresentationInterfaces = pm->getOpenPresentationInterfaces();
   const auto& openInterfaces             = pm->getOpenInterfaces();
   for(auto const& cur: openPresentationInterfaces)
   {
     std::list<GtkFileFilter*>  filters = cur.first->getFilters();
     GtkFileFilterListDestroyer destroyer(filters);
     if(filterMatchesInfo(info, filters))
     {
       PresentationInterface::Ptr presentation = cur.first->open(info.filename);
       if(presentation)
       {
         on_presentation_created(presentation);
         find_or_create_scroom(presentation);
         return;
       }
     }
   }
   for(auto const& cur: openInterfaces)
   {
     std::list<GtkFileFilter*>  filters = cur.first->getFilters();
     GtkFileFilterListDestroyer destroyer(filters);
     if(filterMatchesInfo(info, filters))
     {
       cur.first->open(info.filename, ScroomInterfaceImpl::instance());
       return;
     }
   }
   throw std::invalid_argument("Don't know how to open file " + std::string(info.filename));
 }
load() [2/2]
void load (const std::string & filename)
Definition at line 277 of file loader.cc.
 { load(filterInfoFromPath(filename)); }
loadPresentation() [1/2]
PresentationInterface::Ptr loadPresentation (const GtkFileFilterInfo & info)
Definition at line 194 of file loader.cc.
 {
   static std::map<boost::filesystem::path, PresentationInterface::WeakPtr> loadedPresentations;
   // Create canonical path from filename
   const std::map<OpenPresentationInterface::Ptr, std::string>& openPresentationInterfaces =
     PluginManager::getInstance()->getOpenPresentationInterfaces();
 #ifdef HAVE_BOOST_FILESYSTEM_CANONICAL
   boost::filesystem::path key(canonical(boost::filesystem::path(info.filename)));
 #else
   boost::filesystem::path key(absolute(boost::filesystem::path(info.filename)));
 #endif
   PresentationInterface::Ptr presentation = loadedPresentations[key].lock();
   if(!presentation)
   {
     for(auto const& cur: openPresentationInterfaces)
     {
       std::list<GtkFileFilter*> filters = cur.first->getFilters();
       if(filterMatchesInfo(info, filters))
       {
         presentation = cur.first->open(info.filename);
         if(presentation)
         {
           loadedPresentations[key] = presentation;
           on_presentation_created(presentation);
           break;
         }
       }
     }
   }
   if(presentation)
   {
     return presentation;
   }
   else
   {
     throw std::invalid_argument("Don't know how to load presentation " + std::string(info.filename));
   }
 }
loadPresentation() [2/2]
PresentationInterface::Ptr loadPresentation (const std::string & filename)
Definition at line 189 of file loader.cc.
Referenced by loadPresentation(), ScroomInterfaceImpl::loadPresentation(), and on_done_loading_plugins().
 {
   return loadPresentation(*filterInfoFromPath(filename));
 }