Scroom: Colors Namespace Reference
Colors Namespace Reference
Functions
const Color OUT_OF_BOUNDS (0.75, 0.75, 1)
Variables
const Color OUT_OF_BOUNDS
const Color IN_BOUNDS (1, 1, 1)
Function Documentation
OUT_OF_BOUNDS()
const Color Colors::OUT_OF_BOUNDS (0. 75, 0. 75, 1)
Variable Documentation
IN_BOUNDS
const Color Colors::IN_BOUNDS(1, 1, 1)
Referenced by drawOutOfBoundsWithBackground().
OUT_OF_BOUNDS
const Color Colors::OUT_OF_BOUNDS(0.75, 0.75, 1)
Referenced by drawOutOfBoundsWithBackground(), drawOutOfBoundsWithoutBackground(), and CommonOperations::drawState().