Scroom: Scroom::Utils::Detail Namespace Reference
Scroom::Utils::Detail Namespace Reference
Classes
class ErrorSignalHandler
class ProgressStore
class Registration
Contain all info regarding the registration.
Functions
void assertionFailed (const char *type, const char *expr, const char *function, const char *filename, unsigned int line) __attribute__((noreturn))
Gets called when an assertion failed.
void stackTrace (std::ostream &os, size_t cutoff)
void abort () __attribute__((noreturn))
Variables
static ErrorSignalHandler errorSignalHandler
Function Documentation
abort()
void Scroom::Utils::Detail::abort ()
Definition at line 119 of file assertions.cc.
Referenced by assertionFailed(), Scroom::TiledBitmap::scheduleLoadingBitmap(), stackTrace(), and anonymous_namespace{threadpoolimpl.cc}::ThreadList::wait().
       {
         signal(SIGABRT, SIG_DFL);
         ::abort();
         signal(SIGABRT, errorSignalHandler.handler);
       }
assertionFailed()
void Scroom::Utils::Detail::assertionFailed (const char * type, const char * expr, const char * function, const char * filename, unsigned int line)
Gets called when an assertion failed.
Definition at line 45 of file assertions.cc.
       {
         std::cerr << "PROGRAM DEFECTIVE: " << filename << ":" << line << ": " << type << " " << expr << " violated in "
                   << function;
         stackTrace(std::cerr, 1);
         std::cerr << std::endl << std::flush;
         abort();
       }
stackTrace()
void Scroom::Utils::Detail::stackTrace (std::ostream & os, size_t cutoff)
Definition at line 21 of file assertions.cc.
Referenced by assertionFailed(), and Scroom::Utils::Detail::ErrorSignalHandler::handler().
       {
 #ifdef _WIN32
         // Stack traces generated by this are not very informative, they just show the DLLs.
         // Showing more than then DDLs would probably require an additional dependency
         os << boost::stacktrace::stacktrace();
         // Silence the compiler warning for unused variable
         (void)cutoff;
 #else
         os << "stack trace (innermost first):" << std::endl;
         static const size_t maxTraces = 100;
         void*               array[maxTraces];
         size_t              nTraces = backtrace(array, maxTraces);
         char**              strings = backtrace_symbols(array, static_cast<int>(nTraces));
         for(size_t i = cutoff + 1; i < nTraces; i++)
         {
           os << '#' << i << "  " << strings[i] << std::endl;
         }
         free(strings);
 #endif
       }
Variable Documentation
errorSignalHandler
ErrorSignalHandler Scroom::Utils::Detail::errorSignalHandler static
Definition at line 117 of file assertions.cc.