Scroom: anonymous_namespace{layeroperations.cc} Namespace Reference
anonymous_namespace{layeroperations.cc} Namespace Reference
Functions
boost::shared_ptr< unsigned char > shared_malloc (size_t size)
Function Documentation
shared_malloc()
boost::shared_ptr<unsigned char> anonymous_namespace{layeroperations.cc}::shared_malloc (size_t size)
Definition at line 30 of file layeroperations.cc.
Referenced by Operations1bpp::cache(), Operations8bpp::cache(), Operations24bpp::cache(), Operations::cache(), OperationsColormapped::cache(), and Operations1bppClipped::cacheZoom().
   {
     return boost::shared_ptr<unsigned char>(static_cast<unsigned char*>(malloc(size)), free);
   }