Scroom: Scroom::TiledBitmap Namespace Reference
Scroom::TiledBitmap Namespace Reference
Namespaces
anonymous_namespace{layerspecforbitmap.cc}
Classes
struct BitmapMetaData
class LayerSpecForBitmapper
class OpenTiledBitmapInterface
Typedefs
using ReloadFunction = std::function< Scroom::Utils::Stuff(const ProgressInterface::Ptr &)>
Function type for starting the loading of the bottom Layer of a bitmap.
using LayerSpecResult = std::tuple< LayerSpec, ColormapHelperBase::Ptr >
using LayerSpecForBitmapFunc = std::function< LayerSpecResult(const BitmapMetaData &bitmapMetaData)>
Functions
std::ostream & to_stream (std::ostream &os, const BitmapMetaData &bmd)
std::string to_string (const BitmapMetaData &bmd)
OpenPresentationInterface::Ptr ToOpenPresentationInterface (OpenTiledBitmapInterface::Ptr openTiledBitmapInterface)
LayerSpecResult LayerSpecForBitmap (const BitmapMetaData &bitmapMetaData)
Scroom::Utils::Stuff scheduleLoadingBitmap (const SourcePresentation::Ptr &sp, const Layer::Ptr &layer, const ProgressInterface::Ptr &progress)
LayerSpecResult RGBBitmap (const BitmapMetaData &bmd)
LayerSpecResult CMYKBitmap (const BitmapMetaData &bmd)
LayerSpecResult GreyscaleBitmap (const BitmapMetaData &bmd)
LayerSpecResult ColormappedBitmap (const BitmapMetaData &bmd)
Variables
const std::string RGB = "RGB"
const std::string CMYK = "CMYK"
const std::string Greyscale = "Greyscale"
const std::string Colormapped = "Colormapped"
Typedef Documentation
LayerSpecForBitmapFunc
using Scroom::TiledBitmap::LayerSpecForBitmapFunc = typedef std::function<LayerSpecResult(const BitmapMetaData& bitmapMetaData)>
Definition at line 76 of file opentiledbitmapinterface.hh.
LayerSpecResult
using Scroom::TiledBitmap::LayerSpecResult = typedef std::tuple<LayerSpec, ColormapHelperBase::Ptr>
Definition at line 75 of file opentiledbitmapinterface.hh.
ReloadFunction
using Scroom::TiledBitmap::ReloadFunction = typedef std::function<Scroom::Utils::Stuff(const ProgressInterface::Ptr&)>
Function type for starting the loading of the bottom Layer of a bitmap.
This function is called on the UI thread. You cannot do a significant amount of work in this function, or you'll block the UI. Typical implementations will schedule work on the Sequentially() ThreadPool, such that bitmaps will be loaded sequentially.
Parameters
progressInterface call setProgress(0) on this once the work actually starts
Returns
a shared pointer. Typically a ThreadPool::Queue or similar. The expectation is that when this object is destroyed by the caller, the loading is cancelled.
See also
Layer
OpenTiledBitmapInterface::open()
Sequentially()
scheduleLoadingBitmap() for an example implementation
Definition at line 40 of file opentiledbitmapinterface.hh.
Function Documentation
CMYKBitmap()
LayerSpecResult Scroom::TiledBitmap::CMYKBitmap (const BitmapMetaData & bmd)
Definition at line 110 of file layerspecforbitmap.cc.
Referenced by Scroom::TiledBitmap::LayerSpecForBitmapper::LayerSpecForBitmapper().
     {
       if(bmd.type != CMYK)
       {
         return {};
       }
       require(bmd.samplesPerPixel == 4);
       require(!bmd.colormapHelper);
       LayerSpec ls;
       if(bmd.bitsPerSample == 8)
       {
         ls.push_back(OperationsCMYK32::create());
       }
       else if(bmd.bitsPerSample == 4)
       {
         ls.push_back(OperationsCMYK16::create());
         ls.push_back(OperationsCMYK32::create());
       }
       else if(bmd.bitsPerSample == 2)
       {
         ls.push_back(OperationsCMYK8::create());
         ls.push_back(OperationsCMYK32::create());
       }
       else if(bmd.bitsPerSample == 1)
       {
         ls.push_back(OperationsCMYK4::create());
         ls.push_back(OperationsCMYK32::create());
       }
       else
       {
         printf("ERROR: CMYK bitmaps with %u bits per sample are not supported\n", bmd.bitsPerSample);
         return {};
       }
       return LayerSpecResult(ls, nullptr);
     }
ColormappedBitmap()
LayerSpecResult Scroom::TiledBitmap::ColormappedBitmap (const BitmapMetaData & bmd)
Definition at line 189 of file layerspecforbitmap.cc.
Referenced by Scroom::TiledBitmap::LayerSpecForBitmapper::LayerSpecForBitmapper().
     {
       if(bmd.type != Colormapped)
       {
         return {};
       }
       require(bmd.samplesPerPixel == 1);
       require(bmd.colormapHelper);
       if(bmd.bitsPerSample != 1 && bmd.bitsPerSample != 2 && bmd.bitsPerSample != 4 && bmd.bitsPerSample != 8)
       {
         printf("ERROR: Colormapped bitmaps with %u bits per pixel are not supported (yet)\n", bmd.bitsPerSample);
         return {};
       }
       LayerSpec ls;
       ls.push_back(Operations::create(bmd.colormapHelper, bmd.bitsPerSample));
       ls.push_back(OperationsColormapped::create(bmd.colormapHelper, bmd.bitsPerSample));
       return LayerSpecResult(ls, bmd.colormapHelper);
     }
GreyscaleBitmap()
LayerSpecResult Scroom::TiledBitmap::GreyscaleBitmap (const BitmapMetaData & bmd)
Definition at line 150 of file layerspecforbitmap.cc.
Referenced by Scroom::TiledBitmap::LayerSpecForBitmapper::LayerSpecForBitmapper().
     {
       if(bmd.type != Greyscale)
       {
         return {};
       }
       require(bmd.samplesPerPixel == 1);
       if(bmd.bitsPerSample != 1 && bmd.bitsPerSample != 2 && bmd.bitsPerSample != 4 && bmd.bitsPerSample != 8)
       {
         printf("ERROR: Greyscale bitmaps with %u bits per pixel are not supported (yet)\n", bmd.bitsPerSample);
         return {};
       }
       LayerSpec               ls;
       ColormapHelperBase::Ptr colormapHelper = bmd.colormapHelper;
       if(!colormapHelper)
       {
         colormapHelper = MonochromeColormapHelper::create(2);
       }
       if(bmd.bitsPerSample == 2 || bmd.bitsPerSample == 4)
       {
         ls.push_back(Operations::create(colormapHelper, bmd.bitsPerSample));
         ls.push_back(OperationsColormapped::create(colormapHelper, bmd.bitsPerSample));
       }
       else
       {
         if(bmd.bitsPerSample == 1)
         {
           ls.push_back(Operations1bpp::create(colormapHelper));
         }
         ls.push_back(Operations8bpp::create(colormapHelper));
       }
       return LayerSpecResult(ls, colormapHelper);
     }
LayerSpecForBitmap()
LayerSpecResult Scroom::TiledBitmap::LayerSpecForBitmap (const BitmapMetaData & bitmapMetaData)
Definition at line 212 of file layerspecforbitmap.cc.
Referenced by anonymous_namespace{tiledbitmappresentation.cc}::OpenTiledBitmapAsPresentation::open().
     {
       return LayerSpecForBitmapper::instance()->get(bitmapMetaData);
     }
RGBBitmap()
LayerSpecResult Scroom::TiledBitmap::RGBBitmap (const BitmapMetaData & bmd)
Definition at line 91 of file layerspecforbitmap.cc.
Referenced by Scroom::TiledBitmap::LayerSpecForBitmapper::LayerSpecForBitmapper().
     {
       if(bmd.type != RGB)
       {
         return {};
       };
       require(bmd.samplesPerPixel == 3);
       require(!bmd.colormapHelper);
       if(bmd.bitsPerSample != 8)
       {
         printf("ERROR: RGB bitmaps with %u bits per sample are not supported\n", bmd.bitsPerSample);
         return {};
       }
       return LayerSpecResult({Operations24bpp::create()}, nullptr);
     }
scheduleLoadingBitmap()
Scroom::Utils::Stuff Scroom::TiledBitmap::scheduleLoadingBitmap (const SourcePresentation::Ptr & sp, const Layer::Ptr & layer, const ProgressInterface::Ptr & progress)
Definition at line 30 of file tiled-bitmap.cc.
Referenced by Tiff::open(), and TiledBitmap::setSource().
 {
   auto wait_until_done = boost::make_shared<Scroom::Semaphore>();
   auto queue           = ThreadPool::Queue::createAsync();
   auto weakQueue       = queue->getWeak();
   auto abort           = [wait_until_done, queue]() mutable {
     queue.reset();
     wait_until_done->V();
   };
   auto on_finished = [wait_until_done] { wait_until_done->V(); };
   progress->setWaiting();
   Sequentially()->schedule([progress, layer, sp, weakQueue, on_finished, wait_until_done] {
     gdk_threads_enter();
     progress->setWorking(0);
     gdk_threads_leave();
     layer->fetchData(sp, weakQueue, on_finished);
     wait_until_done->P();
   });
   return Scroom::Utils::on_destruction(abort);
 }
to_stream()
std::ostream & Scroom::TiledBitmap::to_stream (std::ostream & os, const BitmapMetaData & bmd)
Definition at line 22 of file layerspecforbitmap.cc.
Referenced by to_string().
     {
       os << "Type=\"" << bmd.type << "\", rect=" << bmd.rect << ", spp=" << bmd.samplesPerPixel << ", bps=" << bmd.bitsPerSample
          << ", colormapped=" << to_string(static_cast<bool>(bmd.colormapHelper));
       return os;
     }
to_string()
std::string Scroom::TiledBitmap::to_string (const BitmapMetaData & bmd)
Definition at line 30 of file layerspecforbitmap.cc.
Referenced by Scroom::Tiff::Source::reset(), and to_stream().
     {
       std::stringstream ss;
       to_stream(ss, bmd);
       return ss.str();
     }
ToOpenPresentationInterface()
OpenPresentationInterface::Ptr Scroom::TiledBitmap::ToOpenPresentationInterface (OpenTiledBitmapInterface::Ptr openTiledBitmapInterface)
Definition at line 396 of file tiledbitmappresentation.cc.
Referenced by PluginManager::registerOpenTiledBitmapInterface().
     {
       return OpenTiledBitmapAsPresentation::create(std::move(openTiledBitmapInterface));
     }
Variable Documentation
CMYK
const std::string Scroom::TiledBitmap::CMYK = "CMYK"
Definition at line 39 of file layerspecforbitmap.cc.
Referenced by Scroom::Tiff::open().
Colormapped
const std::string Scroom::TiledBitmap::Colormapped = "Colormapped"
Definition at line 41 of file layerspecforbitmap.cc.
Referenced by Scroom::Tiff::open().
Greyscale
const std::string Scroom::TiledBitmap::Greyscale = "Greyscale"
Definition at line 40 of file layerspecforbitmap.cc.
Referenced by Scroom::Tiff::open().
RGB
const std::string Scroom::TiledBitmap::RGB = "RGB"
Definition at line 38 of file layerspecforbitmap.cc.
Referenced by Scroom::Tiff::open().