Scroom: gui/src/pluginmanager.cc File Reference
pluginmanager.cc File Reference
#include "pluginmanager.hh"
#include <cstdio>
#include <cstdlib>
#include <string>
#include <sys/types.h>
#include <boost/filesystem.hpp>
#include <scroom/plugininformationinterface.hh>
#include "callbacks.hh"
Functions
void startPluginManager (bool devMode)
Variables
const std::string SCROOM_PLUGIN_DIRS = "SCROOM_PLUGIN_DIRS"
static PluginManager::Ptr pluginManager = PluginManager::create()
Function Documentation
startPluginManager()
void startPluginManager (bool devMode)
Definition at line 32 of file pluginmanager.cc.
Referenced by on_scroom_bootstrap().
 { pluginManager->addHook(devMode); }
Variable Documentation
pluginManager
PluginManager::Ptr pluginManager = PluginManager::create() static
Definition at line 28 of file pluginmanager.cc.
Referenced by PluginManager::getInstance(), startPluginManager(), and View::View().
SCROOM_PLUGIN_DIRS
const std::string SCROOM_PLUGIN_DIRS = "SCROOM_PLUGIN_DIRS"
Definition at line 26 of file pluginmanager.cc.
Referenced by PluginManager::doWork().