Scroom: ThreadPool::Job Struct Reference
ThreadPool::Job Struct Reference
Public Member Functions
Job ()=default
Job (boost::function< void()> fn, WeakQueue::Ptr queue)
ThreadPool::Job.
Public Attributes
boost::shared_ptr< Scroom::Detail::ThreadPool::QueueImpl > queue
boost::function< void()> fn
Detailed Description
Definition at line 165 of file threadpool.hh.
Constructor & Destructor Documentation
Job() [1/2]
ThreadPool::Job::Job () default
Job() [2/2]
ThreadPool::Job::Job (boost::function< void()> fn, WeakQueue::Ptr queue)
ThreadPool::Job.
Definition at line 420 of file threadpoolimpl.cc.
   : queue(queue_->get())
   , fn(fn_)
 {}
Member Data Documentation
fn
boost::function<void()> ThreadPool::Job::fn
Definition at line 168 of file threadpool.hh.
Referenced by ThreadPool::do_one(), QueueJumper::operator()(), and QueueJumper::setWork().
queue
boost::shared_ptr<Scroom::Detail::ThreadPool::QueueImpl> ThreadPool::Job::queue
Definition at line 167 of file threadpool.hh.
Referenced by ThreadPool::do_one().
The documentation for this struct was generated from the following files:
inc/scroom/threadpool.hh
libs/threadpool/src/threadpoolimpl.cc