Scroom: inc/scroom/threadpool.hh File Reference
threadpool.hh File Reference
#include <queue>
#include <vector>
#include <boost/function.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/thread.hpp>
#include <scroom/semaphore.hh>
#include <scroom/impl/threadpoolimpl.hh>
Classes
class ThreadPool
Generic threadpool.
class ThreadPool::Queue
Represent a Queue in the ThreadPool.
class ThreadPool::WeakQueue
Represent a weak Queue reference ThreadPool.
struct ThreadPool::Job
class ThreadPool::PrivateData
Data needed by the threads to do their work.
class QueueJumper
Jump the queue of a ThreadPool.
Namespaces
Scroom
Scroom::Detail
Scroom::Detail::ThreadPool
Enumerations
enum {
PRIO_HIGHEST = 100, PRIO_HIGHER, PRIO_HIGH, PRIO_NORMAL,
PRIO_LOW, PRIO_LOWER, PRIO_LOWEST
}
Priorities for scheduling on the ThreadPool.
Functions
ThreadPool::Ptr CpuBound ()
ThreadPool for cpu-bound tasks.
ThreadPool::Ptr Sequentially ()
ThreadPool for executing tasks sequentially.
Enumeration Type Documentation
anonymous enum
anonymous enum
Priorities for scheduling on the ThreadPool.
Enumerator
PRIO_HIGHEST
PRIO_HIGHER
PRIO_HIGH
PRIO_NORMAL
PRIO_LOW
PRIO_LOWER
PRIO_LOWEST
Definition at line 24 of file threadpool.hh.
 {
   PRIO_HIGHEST = 100,
   PRIO_HIGHER,
   PRIO_HIGH,
   PRIO_NORMAL,
   PRIO_LOW,
   PRIO_LOWER,
   PRIO_LOWEST,
 };
Function Documentation
CpuBound()
ThreadPool::Ptr CpuBound ()
ThreadPool for cpu-bound tasks.
This ThreadPool has one thread per core in your system. For CpuBound tasks, this is the optimum. Make sure your tasks do not block or wait for anything.
Returns
a shared pointer to this ThreadPool instance
See also
https://github.com/kees-jan/scroom/wiki/StaticInitializationOrderFiasco
Definition at line 462 of file threadpoolimpl.cc.
Referenced by Layer::fetchData(), CompressedTile::observerAdded(), and LayerCoordinator::tileFinished().
 {
   static ThreadPool::Ptr cpuBound = NotifyThreadList<ThreadPool>(ThreadPool::Ptr(new ThreadPool()), "CpuBound threadpool");
   return cpuBound;
 }
Sequentially()
ThreadPool::Ptr Sequentially ()
ThreadPool for executing tasks sequentially.
Tasks that are cpu and/or memory intensive (think "loading large bitmaps") are typically scheduled here, such that only one such task runs at a time.
Note that it is rare to do any actual work on this thread. Especially the cpu-intensive tasks are best delegated to CpuBound(). On this thread, you just wait for the work to complete.
Returns
a shared pointer to this ThreadPool instance
See also
https://github.com/kees-jan/scroom/wiki/StaticInitializationOrderFiasco
Definition at line 469 of file threadpoolimpl.cc.
Referenced by PipetteHandler::onSelectionEnd(), and Scroom::TiledBitmap::scheduleLoadingBitmap().
 {
   static ThreadPool::Ptr sequentially = NotifyThreadList<ThreadPool>(ThreadPool::Ptr(new ThreadPool(1)), "Sequential threadpool");
   return sequentially;
 }