Scroom: libs/threadpool/src/threadpoolimpl.cc File Reference
threadpoolimpl.cc File Reference
#include <cstdio>
#include <cstdlib>
#include <list>
#include <string>
#include <utility>
#include <vector>
#include <scroom/async-deleter.hh>
#include <scroom/threadpool.hh>
#include "queue.hh"
Classes
class anonymous_namespace{threadpoolimpl.cc}::ThreadList
List of threads to wait for (when terminating)
class anonymous_namespace{threadpoolimpl.cc}::ThreadWaiter
Actually wait for all threads registered to the ThreadList.
class anonymous_namespace{threadpoolimpl.cc}::NotifyThreadList< T >
Namespaces
anonymous_namespace{threadpoolimpl.cc}
ThreadList / ThreadWaiter.
Functions
ThreadPool::Ptr CpuBound ()
ThreadPool for cpu-bound tasks.
ThreadPool::Ptr Sequentially ()
ThreadPool for executing tasks sequentially.
Variables
ThreadWaiter anonymous_namespace{threadpoolimpl.cc}::waiter
Function Documentation
CpuBound()
ThreadPool::Ptr CpuBound ()
ThreadPool for cpu-bound tasks.
This ThreadPool has one thread per core in your system. For CpuBound tasks, this is the optimum. Make sure your tasks do not block or wait for anything.
Returns
a shared pointer to this ThreadPool instance
See also
https://github.com/kees-jan/scroom/wiki/StaticInitializationOrderFiasco
Definition at line 462 of file threadpoolimpl.cc.
Referenced by Layer::fetchData(), CompressedTile::observerAdded(), and LayerCoordinator::tileFinished().
 {
   static ThreadPool::Ptr cpuBound = NotifyThreadList<ThreadPool>(ThreadPool::Ptr(new ThreadPool()), "CpuBound threadpool");
   return cpuBound;
 }
Sequentially()
ThreadPool::Ptr Sequentially ()
ThreadPool for executing tasks sequentially.
Tasks that are cpu and/or memory intensive (think "loading large bitmaps") are typically scheduled here, such that only one such task runs at a time.
Note that it is rare to do any actual work on this thread. Especially the cpu-intensive tasks are best delegated to CpuBound(). On this thread, you just wait for the work to complete.
Returns
a shared pointer to this ThreadPool instance
See also
https://github.com/kees-jan/scroom/wiki/StaticInitializationOrderFiasco
Definition at line 469 of file threadpoolimpl.cc.
Referenced by PipetteHandler::onSelectionEnd(), and Scroom::TiledBitmap::scheduleLoadingBitmap().
 {
   static ThreadPool::Ptr sequentially = NotifyThreadList<ThreadPool>(ThreadPool::Ptr(new ThreadPool(1)), "Sequential threadpool");
   return sequentially;
 }