Scroom: SizeDeterminer Class Reference
SizeDeterminer Class Reference
#include <sizedeterminer.hh>
Classes
class PresentationData
Public Types
using Ptr = boost::shared_ptr< SizeDeterminer >
Public Member Functions
void add (PresentationInterface::Ptr const &p)
Scroom::Utils::Rectangle< double > getRect () const
void open (PresentationInterface::Ptr const &p, ViewInterface::WeakPtr const &vi)
void close (PresentationInterface::Ptr const &p, ViewInterface::WeakPtr const &vi)
Static Public Member Functions
static Ptr create ()
Private Member Functions
SizeDeterminer ()=default
void sendUpdates ()
Private Attributes
std::list< PresentationInterface::Ptr > presentations
std::map< PresentationInterface::Ptr, PresentationData > resizablePresentationData
Detailed Description
Definition at line 19 of file sizedeterminer.hh.
Member Typedef Documentation
Ptr
using SizeDeterminer::Ptr = boost::shared_ptr<SizeDeterminer>
Definition at line 22 of file sizedeterminer.hh.
Constructor & Destructor Documentation
SizeDeterminer()
SizeDeterminer::SizeDeterminer () private default
Referenced by create().
Member Function Documentation
add()
void SizeDeterminer::add (PresentationInterface::Ptr const & p)
Definition at line 66 of file sizedeterminer.cc.
 {
   ResizablePresentationInterface::Ptr r = boost::dynamic_pointer_cast<ResizablePresentationInterface>(p);
   if(r)
   {
     resizablePresentationData.insert(std::make_pair(p, PresentationData(r)));
   }
   else
   {
     presentations.push_back(p);
   }
   sendUpdates();
 }
close()
void SizeDeterminer::close (PresentationInterface::Ptr const & p, ViewInterface::WeakPtr const & vi)
Definition at line 110 of file sizedeterminer.cc.
 {
   if(resizablePresentationData.count(p))
   {
     PresentationData& d = resizablePresentationData[p];
     require(d.views.count(vi));
     d.views.erase(vi);
   }
   else
   {
     require(!boost::dynamic_pointer_cast<ResizablePresentationInterface>(p));
   }
 }
create()
SizeDeterminer::Ptr SizeDeterminer::create () static
Definition at line 64 of file sizedeterminer.cc.
 { return Ptr(new SizeDeterminer()); }
getRect()
Scroom::Utils::Rectangle< double > SizeDeterminer::getRect () const
Definition at line 81 of file sizedeterminer.cc.
Referenced by open(), and sendUpdates().
 {
   if(!presentations.empty())
   {
     return DetermineSize(presentations);
   }
   if(!resizablePresentationData.empty())
   {
     return DetermineSize(keys(resizablePresentationData));
   }
   return Scroom::Utils::Rectangle<double>();
 }
open()
void SizeDeterminer::open (PresentationInterface::Ptr const & p, ViewInterface::WeakPtr const & vi)
Definition at line 94 of file sizedeterminer.cc.
 {
   if(resizablePresentationData.count(p))
   {
     PresentationData& d = resizablePresentationData[p];
     require(!d.views.count(vi));
     d.views.insert(vi);
     d.resizablePresentationInterface->setRect(vi, getRect());
   }
   else
   {
     require(!boost::dynamic_pointer_cast<ResizablePresentationInterface>(p));
   }
 }
sendUpdates()
void SizeDeterminer::sendUpdates () private
Definition at line 124 of file sizedeterminer.cc.
Referenced by add().
 {
   Scroom::Utils::Rectangle<double> rect = getRect();
   for(auto const& data: resizablePresentationData)
   {
     for(auto const& view: data.second.views)
     {
       data.second.resizablePresentationInterface->setRect(view, rect);
     }
   }
 }
Member Data Documentation
presentations
std::list<PresentationInterface::Ptr> SizeDeterminer::presentations private
Definition at line 37 of file sizedeterminer.hh.
Referenced by add(), and getRect().
resizablePresentationData
std::map<PresentationInterface::Ptr, PresentationData> SizeDeterminer::resizablePresentationData private
Definition at line 38 of file sizedeterminer.hh.
Referenced by add(), close(), getRect(), open(), and sendUpdates().
The documentation for this class was generated from the following files:
plugins/transparent-overlay/src/sizedeterminer.hh
plugins/transparent-overlay/src/sizedeterminer.cc