Scroom: PluginManager Class Reference
PluginManager Class Reference
#include <pluginmanager.hh>
Public Types
using Ptr = boost::shared_ptr< PluginManager >
Public Types inherited from ScroomPluginInterface
using Ptr = boost::shared_ptr< ScroomPluginInterface >
Public Member Functions
bool doWork () override
void addHook (bool devMode)
void registerNewPresentationInterface (const std::string &identifier, NewPresentationInterface::Ptr newPresentationInterface) override
void registerNewAggregateInterface (const std::string &identifier, NewAggregateInterface::Ptr newAggregateInterface) override
void registerOpenPresentationInterface (const std::string &extension, OpenPresentationInterface::Ptr openPresentationInterface) override
void registerOpenTiledBitmapInterface (const std::string &identifier, boost::shared_ptr< Scroom::TiledBitmap::OpenTiledBitmapInterface > openTiledBitmapInterface) override
void registerOpenInterface (const std::string &extension, OpenInterface::Ptr openInterface) override
void registerViewObserver (const std::string &identifier, ViewObserver::Ptr observer) override
void registerPresentationObserver (const std::string &identifier, PresentationObserver::Ptr observer) override
const std::map< NewPresentationInterface::Ptr, std::string > & getNewPresentationInterfaces ()
const std::map< std::string, NewAggregateInterface::Ptr > & getNewAggregateInterfaces ()
const std::map< OpenPresentationInterface::Ptr, std::string > & getOpenPresentationInterfaces ()
const std::map< Scroom::TiledBitmap::OpenTiledBitmapInterface::Ptr, std::string > & getOpenTiledBitmapInterfaces ()
const std::map< OpenInterface::Ptr, std::string > & getOpenInterfaces ()
const std::map< ViewObserver::Ptr, std::string > & getViewObservers ()
const std::map< PresentationObserver::Ptr, std::string > & getPresentationObservers ()
Public Member Functions inherited from Scroom::Utils::Base
Base ()=default
Base (const Base &)=delete
Base (Base &&)=delete
Base & operator= (const Base &)=delete
Base & operator= (Base &&)=delete
virtual ~Base ()=default
template<typename R >
boost::shared_ptr< R > shared_from_this ()
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
template<typename R >
boost::shared_ptr< R const > shared_from_this () const
Calls shared_from_this() with a built-in dynamic cast, to make it usable in subclasses.
Static Public Member Functions
static Ptr create ()
static PluginManager::Ptr getInstance ()
Private Types
enum PluginManagerState { FINDING_DIRECTORIES, SCANNING_DIRECTORIES, LOADING_FILES, DONE }
Private Member Functions
void setStatusBarMessage (const char *message)
PluginManager ()=default
Private Attributes
bool devMode {false}
PluginManagerState state {FINDING_DIRECTORIES}
std::list< std::string > dirs
std::list< std::string >::iterator currentDir
std::list< std::string > files
std::list< std::string >::iterator currentFile
std::list< PluginInformation > pluginInformationList
std::map< NewPresentationInterface::Ptr, std::string > newPresentationInterfaces
std::map< std::string, NewAggregateInterface::Ptr > newAggregateInterfaces
std::map< OpenPresentationInterface::Ptr, std::string > openPresentationInterfaces
std::map< Scroom::TiledBitmap::OpenTiledBitmapInterface::Ptr, std::string > openTiledBitmapInterfaces
std::map< OpenInterface::Ptr, std::string > openInterfaces
std::map< ViewObserver::Ptr, std::string > viewObservers
std::map< PresentationObserver::Ptr, std::string > presentationObservers
Detailed Description
Definition at line 36 of file pluginmanager.hh.
Member Typedef Documentation
Ptr
using PluginManager::Ptr = boost::shared_ptr<PluginManager>
Definition at line 42 of file pluginmanager.hh.
Member Enumeration Documentation
PluginManagerState
enum PluginManager::PluginManagerState private
Enumerator
FINDING_DIRECTORIES
SCANNING_DIRECTORIES
LOADING_FILES
DONE
Definition at line 45 of file pluginmanager.hh.
   {
     FINDING_DIRECTORIES,
     SCANNING_DIRECTORIES,
     LOADING_FILES,
     DONE
   };
Constructor & Destructor Documentation
PluginManager()
PluginManager::PluginManager () private default
Referenced by create().
Member Function Documentation
addHook()
void PluginManager::addHook (bool devMode)
Definition at line 218 of file pluginmanager.cc.
 {
   devMode = devMode_;
   gtk_idle_add(on_idle, static_cast<WorkInterface*>(this));
   // progressbar = GTK_PROGRESS_BAR(lookup_widget(scroom, "progressbar"));
   // statusbar = GTK_STATUSBAR(lookup_widget(scroom, "statusbar"));
   //
   // status_context_id = gtk_statusbar_get_context_id(statusbar, "Plugin Manager");
   state = FINDING_DIRECTORIES;
 }
create()
PluginManager::Ptr PluginManager::create () static
Definition at line 30 of file pluginmanager.cc.
 { return Ptr(new PluginManager()); }
doWork()
bool PluginManager::doWork () override virtual
Implements WorkInterface.
Definition at line 34 of file pluginmanager.cc.
 {
   bool retval = true;
   gdk_threads_enter();
   switch(state)
   {
   case FINDING_DIRECTORIES:
   {
     setStatusBarMessage("Locating plugin directories");
     char* path = getenv(SCROOM_PLUGIN_DIRS.c_str());
     dirs.clear();
     if(!devMode)
     {
 #ifdef _WIN32
       // We want to keep everything portable on windows so we look for the plugin folder in the same directory as the .exe
       std::string plugin_path = (boost::dll::program_location().parent_path() / "plugins").generic_string();
       dirs.push_back(plugin_path);
 #else
       dirs.emplace_back(PLUGIN_DIR);
 #endif
     }
     if(path != nullptr)
     {
       printf("%s = %s\n", SCROOM_PLUGIN_DIRS.c_str(), path);
       for(char* i = path; *i != '\0'; i++)
       {
 // Windows uses semicolons for delimiting environment variables, Linux uses colons
 #ifdef _WIN32
         const char envDelim = ';';
 #else
         const char envDelim = ':';
 #endif
         if(*i != envDelim)
         {
           continue;
         }
         *i = '\0';
         dirs.emplace_back(path);
         path = i + 1;
       }
       dirs.emplace_back(path);
     }
     currentDir = dirs.begin();
     files.clear();
     state = SCANNING_DIRECTORIES;
     break;
   }
   case SCANNING_DIRECTORIES:
   {
     setStatusBarMessage("Scanning plugin directories");
     if(currentDir == dirs.end())
     {
       state       = LOADING_FILES;
       currentFile = files.begin();
       break;
     }
     printf("Scanning directory: %s\n", currentDir->c_str());
     const char* folder = currentDir->c_str();
     namespace fs       = boost::filesystem;
     boost::system::error_code ec;
     if(!fs::is_directory(folder, ec))
     {
       printf("Can't open directory...\n");
       currentDir++;
       break;
     }
     for(const auto& entry: fs::directory_iterator(folder))
     {
       if(fs::is_regular_file(entry) || fs::is_symlink(entry) || fs::is_other(entry))
       {
         files.push_back(entry.path().generic_string());
       }
     }
     currentDir++;
     break;
   }
   case LOADING_FILES:
   {
     setStatusBarMessage("Loading Plugins");
     if(currentFile == files.end())
     {
       state = DONE;
       break;
     }
 #ifdef _WIN32
     // Only read .dll files
     if(currentFile->compare(currentFile->size() - 4, 4, ".dll") == 0)
     {
 #else
     // Only read .so files
     if(currentFile->compare(currentFile->size() - 3, 3, ".so") == 0)
     {
 #endif
       printf("Reading file: %s\n", currentFile->c_str());
       GModule* plugin = g_module_open(currentFile->c_str(), static_cast<GModuleFlags>(0));
       if(plugin)
       {
         // Need to pass a gpointer to g_module_symbol. If I pass a
         // PluginFunc, glib 2.16.6/gcc 4.2.4 will complain about
         // type-punned pointers.
         gpointer pgpi;
         if(g_module_symbol(plugin, "getPluginInformation", &pgpi))
         {
           auto gpi = reinterpret_cast<PluginFunc>(pgpi);
           if(gpi)
           {
             PluginInformationInterface::Ptr pi = (*gpi)();
             if(pi)
             {
               if(pi->pluginApiVersion == PLUGIN_API_VERSION)
               {
                 pluginInformationList.emplace_back(plugin, pi);
                 pi->registerCapabilities(shared_from_this<PluginManager>());
                 plugin = nullptr;
                 gpi    = nullptr;
                 pi.reset();
               }
               else
               {
                 printf("Plugin has incorrect API version %d, instead of %d\n", pi->pluginApiVersion, PLUGIN_API_VERSION);
               }
             }
             else
             {
               printf("GetPluginInformation returned NULL\n");
             }
           }
           else
           {
             printf("Can't find the getPluginInterface function: %s\n", g_module_error());
           }
         }
         else
         {
           printf("Can't lookup symbols: %s\n", g_module_error());
         }
         if(plugin)
         {
           g_module_close(plugin);
         }
       }
       else
       {
         printf("Something went wrong: %s\n", g_module_error());
       }
     }
   }
     currentFile++;
     break;
   case DONE:
   {
     setStatusBarMessage("Done loading plugins");
     on_done_loading_plugins();
     retval = false;
     break;
   }
   }
   gdk_threads_leave();
   return retval;
 }
getInstance()
PluginManager::Ptr PluginManager::getInstance () static
Definition at line 312 of file pluginmanager.cc.
Referenced by load(), loadPresentation(), ScroomInterfaceImpl::newAggregate(), ScroomInterfaceImpl::newPresentation(), on_done_loading_plugins(), on_open_activate(), on_presentation_created(), on_presentation_possibly_destroyed(), on_view_created(), and View::View().
 { return pluginManager; }
getNewAggregateInterfaces()
const std::map< std::string, NewAggregateInterface::Ptr > & PluginManager::getNewAggregateInterfaces ()
Definition at line 288 of file pluginmanager.cc.
 {
   return newAggregateInterfaces;
 }
getNewPresentationInterfaces()
const std::map< NewPresentationInterface::Ptr, std::string > & PluginManager::getNewPresentationInterfaces ()
Definition at line 283 of file pluginmanager.cc.
 {
   return newPresentationInterfaces;
 }
getOpenInterfaces()
const std::map< OpenInterface::Ptr, std::string > & PluginManager::getOpenInterfaces ()
Definition at line 303 of file pluginmanager.cc.
 { return openInterfaces; }
getOpenPresentationInterfaces()
const std::map< OpenPresentationInterface::Ptr, std::string > & PluginManager::getOpenPresentationInterfaces ()
Definition at line 293 of file pluginmanager.cc.
 {
   return openPresentationInterfaces;
 }
getOpenTiledBitmapInterfaces()
const std::map< Scroom::TiledBitmap::OpenTiledBitmapInterface::Ptr, std::string > & PluginManager::getOpenTiledBitmapInterfaces ()
Definition at line 298 of file pluginmanager.cc.
 {
   return openTiledBitmapInterfaces;
 }
getPresentationObservers()
const std::map< PresentationObserver::Ptr, std::string > & PluginManager::getPresentationObservers ()
Definition at line 307 of file pluginmanager.cc.
 {
   return presentationObservers;
 }
getViewObservers()
const std::map< ViewObserver::Ptr, std::string > & PluginManager::getViewObservers ()
Definition at line 305 of file pluginmanager.cc.
 { return viewObservers; }
registerNewAggregateInterface()
void PluginManager::registerNewAggregateInterface (const std::string & identifier, NewAggregateInterface::Ptr newAggregateInterface) override virtual
Implements ScroomPluginInterface.
Definition at line 238 of file pluginmanager.cc.
 {
   printf("I learned how to create a new %s aggregate!\n", identifier.c_str());
   newAggregateInterfaces[identifier] = newAggregateInterface;
 }
registerNewPresentationInterface()
void PluginManager::registerNewPresentationInterface (const std::string & identifier, NewPresentationInterface::Ptr newPresentationInterface) override virtual
Implements ScroomPluginInterface.
Definition at line 229 of file pluginmanager.cc.
 {
   printf("I learned how to create a new %s!\n", identifier.c_str());
   newPresentationInterfaces[newPresentationInterface] = identifier;
   on_newPresentationInterfaces_update(newPresentationInterfaces);
 }
registerOpenInterface()
void PluginManager::registerOpenInterface (const std::string & extension, OpenInterface::Ptr openInterface) override virtual
Implements ScroomPluginInterface.
Definition at line 262 of file pluginmanager.cc.
 {
   printf("I learned how to open a %s file!\n", extension.c_str());
   openInterfaces[openInterface] = extension;
 }
registerOpenPresentationInterface()
void PluginManager::registerOpenPresentationInterface (const std::string & extension, OpenPresentationInterface::Ptr openPresentationInterface) override virtual
Implements ScroomPluginInterface.
Definition at line 244 of file pluginmanager.cc.
 {
   printf("I learned how to open a %s file!\n", extension.c_str());
   openPresentationInterfaces[openPresentationInterface] = extension;
 }
registerOpenTiledBitmapInterface()
void PluginManager::registerOpenTiledBitmapInterface (const std::string & identifier, boost::shared_ptr< Scroom::TiledBitmap::OpenTiledBitmapInterface > openTiledBitmapInterface) override virtual
Implements ScroomPluginInterface.
Definition at line 252 of file pluginmanager.cc.
 {
   printf("I learned how to open a %s file!\n", extension.c_str());
   openTiledBitmapInterfaces[openTiledBitmapInterface]                               = extension;
   openPresentationInterfaces[ToOpenPresentationInterface(openTiledBitmapInterface)] = extension;
 }
registerPresentationObserver()
void PluginManager::registerPresentationObserver (const std::string & identifier, PresentationObserver::Ptr observer) override virtual
Implements ScroomPluginInterface.
Definition at line 277 of file pluginmanager.cc.
 {
   printf("Observing Presentations for %s!\n", identifier.c_str());
   presentationObservers[observer] = identifier;
 }
registerViewObserver()
void PluginManager::registerViewObserver (const std::string & identifier, ViewObserver::Ptr observer) override virtual
Implements ScroomPluginInterface.
Definition at line 269 of file pluginmanager.cc.
 {
   printf("Observing Views for %s!\n", identifier.c_str());
   viewObservers[observer] = identifier;
   on_new_viewobserver(observer);
 }
setStatusBarMessage()
void PluginManager::setStatusBarMessage (const char * message) private
Definition at line 211 of file pluginmanager.cc.
Referenced by doWork().
 {
   // gtk_statusbar_pop(statusbar, status_context_id);
   // gtk_statusbar_push(statusbar, status_context_id, message);
   // printf("Statusbar update: %s\n", message);
 }
Member Data Documentation
currentDir
std::list<std::string>::iterator PluginManager::currentDir private
Definition at line 57 of file pluginmanager.hh.
Referenced by doWork().
currentFile
std::list<std::string>::iterator PluginManager::currentFile private
Definition at line 59 of file pluginmanager.hh.
Referenced by doWork().
devMode
bool PluginManager::devMode {false} private
Definition at line 54 of file pluginmanager.hh.
Referenced by addHook(), and doWork().
dirs
std::list<std::string> PluginManager::dirs private
Definition at line 56 of file pluginmanager.hh.
Referenced by doWork().
files
std::list<std::string> PluginManager::files private
Definition at line 58 of file pluginmanager.hh.
Referenced by doWork().
newAggregateInterfaces
std::map<std::string, NewAggregateInterface::Ptr> PluginManager::newAggregateInterfaces private
Definition at line 62 of file pluginmanager.hh.
Referenced by getNewAggregateInterfaces(), and registerNewAggregateInterface().
newPresentationInterfaces
std::map<NewPresentationInterface::Ptr, std::string> PluginManager::newPresentationInterfaces private
Definition at line 61 of file pluginmanager.hh.
Referenced by getNewPresentationInterfaces(), and registerNewPresentationInterface().
openInterfaces
std::map<OpenInterface::Ptr, std::string> PluginManager::openInterfaces private
Definition at line 65 of file pluginmanager.hh.
Referenced by getOpenInterfaces(), and registerOpenInterface().
openPresentationInterfaces
std::map<OpenPresentationInterface::Ptr, std::string> PluginManager::openPresentationInterfaces private
Definition at line 63 of file pluginmanager.hh.
Referenced by getOpenPresentationInterfaces(), registerOpenPresentationInterface(), and registerOpenTiledBitmapInterface().
openTiledBitmapInterfaces
std::map<Scroom::TiledBitmap::OpenTiledBitmapInterface::Ptr, std::string> PluginManager::openTiledBitmapInterfaces private
Definition at line 64 of file pluginmanager.hh.
Referenced by getOpenTiledBitmapInterfaces(), and registerOpenTiledBitmapInterface().
pluginInformationList
std::list<PluginInformation> PluginManager::pluginInformationList private
Definition at line 60 of file pluginmanager.hh.
Referenced by doWork().
presentationObservers
std::map<PresentationObserver::Ptr, std::string> PluginManager::presentationObservers private
Definition at line 67 of file pluginmanager.hh.
Referenced by getPresentationObservers(), and registerPresentationObserver().
state
PluginManagerState PluginManager::state {FINDING_DIRECTORIES} private
Definition at line 55 of file pluginmanager.hh.
Referenced by addHook(), and doWork().
viewObservers
std::map<ViewObserver::Ptr, std::string> PluginManager::viewObservers private
Definition at line 66 of file pluginmanager.hh.
Referenced by getViewObservers(), and registerViewObserver().
The documentation for this class was generated from the following files:
gui/src/pluginmanager.hh
gui/src/pluginmanager.cc