Scroom: ProgressBarManager Class Reference
ProgressBarManager Class Reference
#include <progressbarmanager.hh>
Public Types
using Ptr = boost::shared_ptr< ProgressBarManager >
Public Types inherited from ProgressInterface
using Ptr = boost::shared_ptr< ProgressInterface >
using WeakPtr = boost::weak_ptr< ProgressInterface >
Public Member Functions
~ProgressBarManager () override
ProgressBarManager (const ProgressBarManager &)=delete
ProgressBarManager (ProgressBarManager &&)=delete
ProgressBarManager operator= (const ProgressBarManager &)=delete
ProgressBarManager operator= (ProgressBarManager &&)=delete
void setProgressBar (GtkProgressBar *progressBar)
void setIdle () override
void setWaiting (double progress=0.0) override
void setWorking (double progress) override
void setFinished () override
Static Public Member Functions
static Ptr create (GtkProgressBar *progressBar=nullptr)
Private Member Functions
ProgressBarManager (GtkProgressBar *progressBar)
void stopWaiting ()
void startWaiting ()
Private Attributes
GtkProgressBar * progressBar
bool isWaiting
Detailed Description
Definition at line 14 of file progressbarmanager.hh.
Member Typedef Documentation
Ptr
using ProgressBarManager::Ptr = boost::shared_ptr<ProgressBarManager>
Definition at line 17 of file progressbarmanager.hh.
Constructor & Destructor Documentation
ProgressBarManager() [1/3]
ProgressBarManager::ProgressBarManager (GtkProgressBar * progressBar) private
Definition at line 111 of file progressbarmanager.cc.
Referenced by create().
   : progressBar(progressBar_)
   , isWaiting(false)
 {}
~ProgressBarManager()
ProgressBarManager::~ProgressBarManager () override
Definition at line 121 of file progressbarmanager.cc.
 { stopWaiting(); }
ProgressBarManager() [2/3]
ProgressBarManager::ProgressBarManager (const ProgressBarManager &) delete
ProgressBarManager() [3/3]
ProgressBarManager::ProgressBarManager (ProgressBarManager &&) delete
Member Function Documentation
create()
ProgressBarManager::Ptr ProgressBarManager::create (GtkProgressBar * progressBar = nullptr) static
Definition at line 116 of file progressbarmanager.cc.
Referenced by View::View().
 {
   return Ptr(new ProgressBarManager(progressBar));
 }
operator=() [1/2]
ProgressBarManager ProgressBarManager::operator= (const ProgressBarManager &) delete
operator=() [2/2]
ProgressBarManager ProgressBarManager::operator= (ProgressBarManager &&) delete
setFinished()
void ProgressBarManager::setFinished () override virtual
Implements ProgressInterface.
Definition at line 163 of file progressbarmanager.cc.
 { setIdle(); }
setIdle()
void ProgressBarManager::setIdle () override virtual
Implements ProgressInterface.
Definition at line 151 of file progressbarmanager.cc.
Referenced by setFinished().
 { setWorking(0.0); }
setProgressBar()
void ProgressBarManager::setProgressBar (GtkProgressBar * progressBar)
Definition at line 123 of file progressbarmanager.cc.
 {
   stopWaiting();
   progressBar = progressBar_;
 }
setWaiting()
void ProgressBarManager::setWaiting (double progress = 0.0) override virtual
Implements ProgressInterface.
Definition at line 153 of file progressbarmanager.cc.
 { startWaiting(); }
setWorking()
void ProgressBarManager::setWorking (double progress) override virtual
Implements ProgressInterface.
Definition at line 155 of file progressbarmanager.cc.
Referenced by setIdle().
 {
   stopWaiting();
   Scroom::GtkHelpers::TakeGdkLock gdkLock;
   gtk_progress_bar_set_fraction(progressBar, progress);
 }
startWaiting()
void ProgressBarManager::startWaiting () private
Definition at line 129 of file progressbarmanager.cc.
Referenced by setWaiting().
 {
   if(!isWaiting)
   {
     // Start pulsing
     instance()->start(progressBar);
     isWaiting = true;
   }
 }
stopWaiting()
void ProgressBarManager::stopWaiting () private
Definition at line 139 of file progressbarmanager.cc.
Referenced by setProgressBar(), setWorking(), and ~ProgressBarManager().
 {
   if(isWaiting)
   {
     // Stop pulsing
     instance()->stop(progressBar);
     isWaiting = false;
   }
 }
Member Data Documentation
isWaiting
bool ProgressBarManager::isWaiting private
Definition at line 21 of file progressbarmanager.hh.
Referenced by startWaiting(), and stopWaiting().
progressBar
GtkProgressBar* ProgressBarManager::progressBar private
Definition at line 20 of file progressbarmanager.hh.
Referenced by setProgressBar(), setWorking(), startWaiting(), and stopWaiting().
The documentation for this class was generated from the following files:
gui/src/progressbarmanager.hh
gui/src/progressbarmanager.cc