var namespaceanonymous__namespace_02transparentoverlaypresentation_8cc_03 =
[
    [ "ColorComparer", "structanonymous__namespace_02transparentoverlaypresentation_8cc_03_1_1ColorComparer.html", "structanonymous__namespace_02transparentoverlaypresentation_8cc_03_1_1ColorComparer" ]
];