Scroom: Scroom::Tiff Namespace Reference
Scroom::Tiff Namespace Reference
Classes
class Source
Typedefs
using TIFFPtr = boost::shared_ptr< TIFF >
Functions
Colormap::Ptr getColorMap (const TIFFPtr &tif, uint16_t bps)
boost::optional< Scroom::Utils::Point< double > > getAspectRatio (const TIFFPtr &tif)
ColormapHelperBase::Ptr getColormapHelper (const TIFFPtr &tif, uint16_t bps)
boost::optional< std::tuple< Scroom::TiledBitmap::BitmapMetaData, TIFFPtr > > open (const std::string &fileName)
Typedef Documentation
TIFFPtr
using Scroom::Tiff::TIFFPtr = typedef boost::shared_ptr<TIFF>
Definition at line 30 of file tiffsource.hh.
Function Documentation
getAspectRatio()
boost::optional<Scroom::Utils::Point<double> > Scroom::Tiff::getAspectRatio (const TIFFPtr & tif)
Definition at line 89 of file tiffsource.cc.
Referenced by open().
     {
       float  resolutionX{};
       float  resolutionY{};
       uint16 resolutionUnit{};
       if(TIFFGetField(tif.get(), TIFFTAG_XRESOLUTION, &resolutionX) && TIFFGetField(tif.get(), TIFFTAG_YRESOLUTION, &resolutionY)
          && TIFFGetField(tif.get(), TIFFTAG_RESOLUTIONUNIT, &resolutionUnit))
       {
         if(resolutionUnit != RESUNIT_NONE)
         {
           // Fix aspect ratio only
           float base  = std::max(resolutionX, resolutionY);
           resolutionX = base / resolutionX;
           resolutionY = base / resolutionY;
         }
         return Scroom::Utils::make_point<double>(resolutionX, resolutionY);
       }
       return {};
     }
getColorMap()
Colormap::Ptr Scroom::Tiff::getColorMap (const TIFFPtr & tif, uint16_t bps)
Definition at line 65 of file tiffsource.cc.
Referenced by getColormapHelper().
     {
       uint16*       r{};
       uint16*       g{};
       uint16*       b{};
       Colormap::Ptr colormap;
       int result = TIFFGetField(tif.get(), TIFFTAG_COLORMAP, &r, &g, &b);
       if(result == 1)
       {
         colormap       = Colormap::create();
         colormap->name = "Original";
         size_t count   = 1UL << bps;
         colormap->colors.resize(count);
         for(size_t i = 0; i < count; i++)
         {
           colormap->colors[i] = Color(1.0 * r[i] / 0xFFFF, 1.0 * g[i] / 0xFFFF, 1.0 * b[i] / 0xFFFF);
         }
       }
       return colormap;
     }
getColormapHelper()
ColormapHelperBase::Ptr Scroom::Tiff::getColormapHelper (const TIFFPtr & tif, uint16_t bps)
Definition at line 111 of file tiffsource.cc.
Referenced by open().
     {
       auto colorMap = getColorMap(tif, bps);
       return colorMap ? ColormapHelper::create(colorMap) : nullptr;
     }
open()
boost::optional< std::tuple< Scroom::TiledBitmap::BitmapMetaData, TIFFPtr > > Scroom::Tiff::open (const std::string & fileName)
Definition at line 117 of file tiffsource.cc.
Referenced by anonymous_namespace{tiledbitmappresentation.cc}::OpenTiledBitmapAsPresentation::getFilters(), Layer::getPageProvider(), Tiff::open(), CompressedTile::registerObserver(), and Scroom::Tiff::Source::reset().
     {
       try
       {
         TIFFPtr tif(TIFFOpen(fileName.c_str(), "r"), &TIFFCloseUnlessNull);
         if(!tif)
         {
           // Todo: report error
           printf("PANIC: Failed to open file %s\n", fileName.c_str());
           return {};
         }
         auto spp = TIFFGetFieldCheckedOr<uint16_t>(tif, TT(TIFFTAG_SAMPLESPERPIXEL), 1); // Default value, according to tiff spec
         auto bps = TIFFGetFieldCheckedOr<uint16_t>(tif, TT(TIFFTAG_BITSPERSAMPLE), (spp == 1) ? 1 : 8);
         auto width       = TIFFGetFieldChecked<uint32_t>(tif, TT(TIFFTAG_IMAGEWIDTH));
         auto height      = TIFFGetFieldChecked<uint32_t>(tif, TT(TIFFTAG_IMAGELENGTH));
         auto photometric = TIFFGetFieldChecked<uint16_t>(tif, TT(TIFFTAG_PHOTOMETRIC));
         ColormapHelperBase::Ptr colormapHelper = getColormapHelper(tif, bps);
         if(photometric != PHOTOMETRIC_PALETTE && colormapHelper)
         {
           printf("WARNING: Tiff contains a colormap, but photometric isn't palette\n");
           colormapHelper.reset();
         }
         auto numberOfGreyscaleColors = (bps == 2 || bps == 4) ? (1 << bps) : 2; // Yuk
         switch(photometric)
         {
         case PHOTOMETRIC_MINISBLACK:
           colormapHelper = MonochromeColormapHelper::create(numberOfGreyscaleColors);
           break;
         case PHOTOMETRIC_MINISWHITE:
           colormapHelper = MonochromeColormapHelper::createInverted(numberOfGreyscaleColors);
           break;
         case PHOTOMETRIC_PALETTE:
           if(!colormapHelper)
           {
             printf("WEIRD: Photometric is palette, but tiff doesn't contain a colormap\n");
             colormapHelper = ColormapHelper::create(1 << bps);
           }
           break;
         case PHOTOMETRIC_RGB:
         case PHOTOMETRIC_SEPARATED:
           break;
         default:
           printf("ERROR: Unrecognized value %d for photometric\n", photometric);
           return {};
         }
         auto aspectRatio = getAspectRatio(tif);
         if(aspectRatio)
         {
           printf("This bitmap has size %u*%u, aspect ratio %.1f*%.1f\n", width, height, aspectRatio->x, aspectRatio->y);
         }
         else
         {
           printf("This bitmap has size %u*%u\n", width, height);
         }
         BitmapMetaData bmd{{}, bps, spp, Scroom::Utils::make_rect<int>(0, 0, width, height), aspectRatio, colormapHelper};
         if(bps != 1 && bps != 2 && bps != 4 && bps != 8)
         {
           printf("ERROR: %u bits per sample not supported (yet)\n", bps);
           return {};
         }
         if(spp == 4)
         {
           bmd.type = CMYK;
         }
         else if(spp == 3)
         {
           bmd.type = RGB;
           if(bps != 8)
           {
             printf("ERROR: A RGB bitmap with %u samples per pixel isn't supported (yet)", bps);
             return {};
           }
         }
         else if(spp == 1)
         {
           bmd.type = (photometric == PHOTOMETRIC_PALETTE) ? Colormapped : Greyscale;
         }
         else
         {
           printf("PANIC: %u samples per pixel not supported (yet)\n", spp);
           return {};
         }
         return std::make_tuple(bmd, tif);
       }
       catch(const std::exception& ex)
       {
         printf("PANIC: %s\n", ex.what());
         return {};
       }
     }