/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include "callbacks.h"

int
main (int argc, char *argv[])
{
  GtkWidget *scroom;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  g_thread_init(NULL);
  gdk_threads_init();
  
  gdk_threads_enter();
  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  scroom = create_scroom ();
  gtk_widget_show (scroom);
  on_scroom_bootstrap(scroom);
  
  gtk_main ();
  gdk_threads_leave();
  return 0;
}

