Scroom: libs/scroom/inc/scroom/cairo-helpers.hh File Reference
cairo-helpers.hh File Reference
#include <list>
#include <gdk/gdk.h>
#include <cairo.h>
#include <scroom/color.hh>
#include <scroom/rectangle.hh>
Namespaces
Colors
Functions
void traceRectangleContour (cairo_t *cr, Scroom::Utils::Rectangle< double > const &viewArea)
void drawRectangleContour (cairo_t *cr, Scroom::Utils::Rectangle< double > const &viewArea)
void drawRectangleContour (cairo_t *cr, Color const &c, Scroom::Utils::Rectangle< double > const &viewArea)
void setClip (cairo_t *cr, double x, double y, double width, double height)
void setClip (cairo_t *cr, const Scroom::Utils::Rectangle< double > &area)
void drawRectangle (cairo_t *cr, Color const &c, Scroom::Utils::Rectangle< double > const &viewArea)
void drawOutOfBoundsWithBackground (cairo_t *cr, Scroom::Utils::Rectangle< double > const &requestedPresentationArea, Scroom::Utils::Rectangle< double > const &actualPresentationArea, double pixelSize)
void drawOutOfBoundsWithBackgroundColor (cairo_t *cr, const Color &background, Scroom::Utils::Rectangle< double > const &requestedPresentationArea, Scroom::Utils::Rectangle< double > const &actualPresentationArea, double pixelSize)
void drawOutOfBoundsWithoutBackground (cairo_t *cr, Scroom::Utils::Rectangle< double > const &requestedPresentationArea, Scroom::Utils::Rectangle< double > const &actualPresentationArea, double pixelSize)
double pixelSizeFromZoom (int zoom)
Variables
const Color Colors::OUT_OF_BOUNDS
Function Documentation
drawOutOfBoundsWithBackground()
void drawOutOfBoundsWithBackground (cairo_t * cr, Scroom::Utils::Rectangle< double > const & requestedPresentationArea, Scroom::Utils::Rectangle< double > const & actualPresentationArea, double pixelSize)
 {
   drawRectangle(cr, Colors::OUT_OF_BOUNDS, pixelSize * (requestedPresentationArea.moveTo(0, 0)));
   drawRectangle(cr, Colors::IN_BOUNDS, pixelSize * (actualPresentationArea - requestedPresentationArea.getTopLeft()));
 }
Referenced by ExamplePresentation::redraw().
drawOutOfBoundsWithBackgroundColor()
void drawOutOfBoundsWithBackgroundColor (cairo_t * cr, const Color & background, Scroom::Utils::Rectangle< double > const & requestedPresentationArea, Scroom::Utils::Rectangle< double > const & actualPresentationArea, double pixelSize)
 {
   drawOutOfBoundsWithoutBackground(cr, requestedPresentationArea, actualPresentationArea, pixelSize);
   drawRectangle(cr, background, pixelSize * (actualPresentationArea - requestedPresentationArea.getTopLeft()));
 }
drawOutOfBoundsWithoutBackground()
void drawOutOfBoundsWithoutBackground (cairo_t * cr, Scroom::Utils::Rectangle< double > const & requestedPresentationArea, Scroom::Utils::Rectangle< double > const & actualPresentationArea, double pixelSize)
 {
   std::list<Rectangle<double>> const border =
     boost::assign::list_of(requestedPresentationArea.leftOf(actualPresentationArea.getLeft()))(requestedPresentationArea.rightOf(
       actualPresentationArea.getRight()))(requestedPresentationArea.above(actualPresentationArea.getTop()))(
       requestedPresentationArea.below(actualPresentationArea.getBottom()));
   for(const Rectangle<double>& r: border)
   {
     if(!r.isEmpty())
     {
       drawRectangle(cr, Colors::OUT_OF_BOUNDS, pixelSize * (r - requestedPresentationArea.getTopLeft()));
     }
   }
 }
Referenced by drawOutOfBoundsWithBackgroundColor(), and anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::redraw().
drawRectangle()
void drawRectangle (cairo_t * cr, Color const & c, Scroom::Utils::Rectangle< double > const & viewArea)
 {
   cairo_save(cr);
   c.setColor(cr);
   setClip(cr, viewArea);
   cairo_paint(cr);
   cairo_restore(cr);
 }
Referenced by drawOutOfBoundsWithBackground(), drawOutOfBoundsWithBackgroundColor(), drawOutOfBoundsWithoutBackground(), and CommonOperations::drawState().
drawRectangleContour() [1/2]
void drawRectangleContour (cairo_t * cr, Color const & c, Scroom::Utils::Rectangle< double > const & viewArea)
 {
   cairo_save(cr);
   c.setColor(cr);
   drawRectangleContour(cr, viewArea);
   cairo_restore(cr);
 }
drawRectangleContour() [2/2]
void drawRectangleContour (cairo_t * cr, Scroom::Utils::Rectangle< double > const & viewArea)
 {
   traceRectangleContour(cr, viewArea);
   cairo_stroke(cr);
 }
Referenced by drawRectangleContour(), and TiledBitmap::drawTile().
pixelSizeFromZoom()
double pixelSizeFromZoom (int zoom)
 {
   double pixelSize = 1.0;
   if(zoom >= 0)
   {
     pixelSize *= 1 << zoom;
   }
   else
   {
     pixelSize /= 1 << (-zoom);
   }
   return pixelSize;
 }
Referenced by TweakPositionTextBox::display(), View::on_motion_notify(), View::on_window_size_changed(), View::on_zoombox_changed(), TweakPositionTextBox::parse(), View::presentationPointToWindowPoint(), ExamplePresentation::redraw(), TestData::redraw(), TiledBitmap::redraw(), anonymous_namespace{tiledbitmappresentation.cc}::TiledBitmapPresentation::redraw(), TransformPresentation::redraw(), View::redraw(), MeasureHandler::render(), PipetteHandler::render(), View::setPresentation(), TweakPresentationPosition::tweakPosition(), TweakRulers::tweakRulers(), View::updateScrollbar(), and View::windowPointToPresentationPoint().
setClip() [1/2]
void setClip (cairo_t * cr, const Scroom::Utils::Rectangle< double > & area)
 {
   setClip(cr, area.getLeft(), area.getTop(), area.getWidth(), area.getHeight());
 }
setClip() [2/2]
void setClip (cairo_t * cr, double x, double y, double width, double height)
 {
   cairo_move_to(cr, x, y);
   cairo_line_to(cr, x + width, y);
   cairo_line_to(cr, x + width, y + height);
   cairo_line_to(cr, x, y + height);
   cairo_line_to(cr, x, y);
   cairo_clip(cr);
 }
Referenced by CommonOperations::draw(), drawRectangle(), and setClip().
traceRectangleContour()
void traceRectangleContour (cairo_t * cr, Scroom::Utils::Rectangle< double > const & viewArea)
 {
   cairo_move_to(cr, viewArea.x(), viewArea.y());
   cairo_line_to(cr, viewArea.x() + viewArea.width(), viewArea.y());
   cairo_line_to(cr, viewArea.x() + viewArea.width(), viewArea.y() + viewArea.height());
   cairo_line_to(cr, viewArea.x(), viewArea.y() + viewArea.height());
   cairo_line_to(cr, viewArea.x(), viewArea.y());
 }
Referenced by drawRectangleContour().