Scroom: Scroom::Metadata::anonymous_namespace{showmetadata.cc} Namespace Reference
Scroom::Metadata::anonymous_namespace{showmetadata.cc} Namespace Reference
Classes
struct MetaDataWindowData
Functions
GtkWidget * gtk_label_with_markup (const char *text)
GtkWidget * addNewKeyToGrid (const GtkWidget *grid, GtkWidget *previousKey, const std::string &keyText)
GtkWidget * addNewValueToGrid (const GtkWidget *grid, const std::string &valueText, GtkWidget *key)
void addKeyAndValueToSizeGroup (GtkWidget *key, GtkWidget *value)
void on_metadata_destroyed (GtkWidget *, gpointer user_data)
Function Documentation
addKeyAndValueToSizeGroup()
void Scroom::Metadata::anonymous_namespace{showmetadata.cc}::addKeyAndValueToSizeGroup (GtkWidget * key, GtkWidget * value)
     {
       auto* group = gtk_size_group_new(GTK_SIZE_GROUP_HORIZONTAL);
       gtk_size_group_add_widget(group, key);
       gtk_size_group_add_widget(group, value);
       g_object_unref(group);
     }
Referenced by Scroom::Metadata::showMetaData().
addNewKeyToGrid()
GtkWidget* Scroom::Metadata::anonymous_namespace{showmetadata.cc}::addNewKeyToGrid (const GtkWidget * grid, GtkWidget * previousKey, const std::string & keyText)
     {
       GtkWidget* key = gtk_label_with_markup(keyText.c_str());
       if(previousKey)
       {
         gtk_grid_attach_next_to(GTK_GRID(grid), key, previousKey, GTK_POS_BOTTOM, 3, 3);
       }
       else
       {
         gtk_grid_attach(GTK_GRID(grid), key, 0, GTK_POS_RIGHT, 3, 3);
       }
       return key;
     }
Referenced by Scroom::Metadata::showMetaData().
addNewValueToGrid()
GtkWidget* Scroom::Metadata::anonymous_namespace{showmetadata.cc}::addNewValueToGrid (const GtkWidget * grid, const std::string & valueText, GtkWidget * key)
     {
       GtkWidget* value = gtk_label_new(valueText.c_str());
       gtk_grid_attach_next_to(GTK_GRID(grid), value, key, GTK_POS_RIGHT, 3, 3);
       return value;
     }
Referenced by Scroom::Metadata::showMetaData().
gtk_label_with_markup()
GtkWidget* Scroom::Metadata::anonymous_namespace{showmetadata.cc}::gtk_label_with_markup (const char * text)
     {
       GtkWidget* label = gtk_label_new(text);
       gtk_label_set_use_markup(GTK_LABEL(label), true);
       return label;
     }
Referenced by addNewKeyToGrid().
on_metadata_destroyed()
void Scroom::Metadata::anonymous_namespace{showmetadata.cc}::on_metadata_destroyed (GtkWidget * , gpointer user_data)
     {
       delete static_cast<const MetaDataWindowData*>(user_data); // NOLINT(cppcoreguidelines-owning-memory)
     }
Referenced by Scroom::Metadata::showMetaData().