Scroom: libs/util/inc/scroom/rounding.hh File Reference
rounding.hh File Reference
#include <cmath>
Functions
double rounded_divide_by (double value, double factor)
double ceiled_divide_by (double value, double factor)
double floored_divide_by (double value, double factor)
int rounded_divide_by (int value, int factor)
int ceiled_divide_by (int value, int factor)
int floored_divide_by (int value, int factor)
template<typename T >
T round_to_multiple_of (T value, T factor)
template<typename T >
T round_up_to_multiple_of (T value, T factor)
template<typename T >
T round_down_to_multiple_of (T value, T factor)
Function Documentation
ceiled_divide_by() [1/2]
double ceiled_divide_by (double value, double factor) inline
 { return std::ceil(value / factor); }
Referenced by ceiled_divide_by(), and round_up_to_multiple_of().
ceiled_divide_by() [2/2]
int ceiled_divide_by (int value, int factor) inline
 {
   return static_cast<int>(ceiled_divide_by(static_cast<double>(value), static_cast<double>(factor)));
 }
floored_divide_by() [1/2]
double floored_divide_by (double value, double factor) inline
 { return std::floor(value / factor); }
Referenced by floored_divide_by(), and round_down_to_multiple_of().
floored_divide_by() [2/2]
int floored_divide_by (int value, int factor) inline
 {
   return static_cast<int>(floored_divide_by(static_cast<double>(value), static_cast<double>(factor)));
 }
round_down_to_multiple_of()
template<typename T > T round_down_to_multiple_of (T value, T factor)
 {
   return factor * floored_divide_by(value, factor);
 }
Referenced by Scroom::Utils::roundOutward().
round_to_multiple_of()
template<typename T > T round_to_multiple_of (T value, T factor)
 {
   return factor * rounded_divide_by(value, factor);
 }
Referenced by Scroom::Utils::roundCorners(), and TweakPresentationPosition::tweakPosition().
round_up_to_multiple_of()
template<typename T > T round_up_to_multiple_of (T value, T factor)
 {
   return factor * ceiled_divide_by(value, factor);
 }
Referenced by Scroom::Utils::roundOutward().
rounded_divide_by() [1/2]
double rounded_divide_by (double value, double factor) inline
 { return std::round(value / factor); }
Referenced by round_to_multiple_of(), and rounded_divide_by().
rounded_divide_by() [2/2]
int rounded_divide_by (int value, int factor) inline
 {
   return static_cast<int>(rounded_divide_by(static_cast<double>(value), static_cast<double>(factor)));
 }