Scroom: gui/src/view.cc File Reference
view.cc File Reference
#include "view.hh"
#include <array>
#include <sstream>
#include <spdlog/spdlog.h>
#include <boost/lexical_cast.hpp>
#include <glib-object.h>
#include <scroom/assertions.hh>
#include <scroom/cairo-helpers.hh>
#include <scroom/format_stuff.hh>
#include <scroom/rounding.hh>
#include "callbacks.hh"
#include "pluginmanager.hh"
Classes
class TweakPresentationPosition
Tweakers.
class TweakRulers
class ITweakSelection
class TweakSelection
class TweakGridSelection
class TweakPixelSelection
class TweakPositionTextBox
Macros
#define G_VALUE_INIT
Enumerations
enum { COLUMN_TEXT, COLUMN_ZOOM, N_COLUMNS }
enum Corner { Corner::TOP_LEFT, Corner::TOP_RIGHT, Corner::BOTTOM_LEFT, Corner::BOTTOM_RIGHT }
Functions
std::function< Scroom::Utils::Point< double >Scroom::Utils::Rectangle< double >)> corner_getter (Corner c)
Corner find_closest_corner (Scroom::Utils::Point< double > p, Scroom::Utils::Rectangle< double > r)
Corner find_opposed_corner (Corner c)
Scroom::Utils::Rectangle< double > toRectangle (Selection s)
static Scroom::Utils::Point< double > eventToPoint (GdkEventButton *event)
Helpers.
static Scroom::Utils::Point< double > eventToPoint (GdkEventMotion *event)
static void on_newWindow_activate (GtkMenuItem *, gpointer user_data)
static void tool_button_toggled (GtkToggleButton *button, gpointer data)
Variables
static const std::array< const char *, 36 > zoomfactor
static const int MaxZoom = 5
Macro Definition Documentation
G_VALUE_INIT
#define G_VALUE_INIT
Value:
    {                  \
      0,               \
      {                \
        {              \
          0            \
        }              \
      }                \
    }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLUMN_TEXT
COLUMN_ZOOM
N_COLUMNS
 {
   COLUMN_TEXT,
   COLUMN_ZOOM,
   N_COLUMNS
 };
Corner
enum Corner strong
Enumerator
TOP_LEFT
TOP_RIGHT
BOTTOM_LEFT
BOTTOM_RIGHT
 {
   TOP_LEFT,
   TOP_RIGHT,
   BOTTOM_LEFT,
   BOTTOM_RIGHT
 };
Function Documentation
corner_getter()
std::function<Scroom::Utils::Point<double>Scroom::Utils::Rectangle<double>)> corner_getter (Corner c)
 {
   switch(c)
   {
   case Corner::TOP_LEFT:
     return [](Scroom::Utils::Rectangle<double> r) { return r.getTopLeft(); };
   case Corner::TOP_RIGHT:
     return [](Scroom::Utils::Rectangle<double> r) { return r.getTopRight(); };
   case Corner::BOTTOM_LEFT:
     return [](Scroom::Utils::Rectangle<double> r) { return r.getBottomLeft(); };
   case Corner::BOTTOM_RIGHT:
     return [](Scroom::Utils::Rectangle<double> r) { return r.getBottomRight(); };
   }
   defect();
 }
Referenced by TweakSelection::tweakSelection().
eventToPoint() [1/2]
static Scroom::Utils::Point<double> eventToPoint (GdkEventButton * event) static
Helpers.
 { return {event->x, event->y}; }
Referenced by View::on_buttonPress(), View::on_buttonRelease(), and View::on_motion_notify().
eventToPoint() [2/2]
static Scroom::Utils::Point<double> eventToPoint (GdkEventMotion * event) static
 { return {event->x, event->y}; }
find_closest_corner()
Corner find_closest_corner (Scroom::Utils::Point< double > p, Scroom::Utils::Rectangle< double > r)
 {
   const std::array<std::array<Corner, 2>, 2> corners = {{
     {Corner::TOP_LEFT, Corner::BOTTOM_LEFT},
     {Corner::TOP_RIGHT, Corner::BOTTOM_RIGHT},
   }};
   const auto c = center(r);
   return corners.at(c.x < p.x).at(c.y < p.y);
 }
Referenced by TweakSelection::tweakSelection().
find_opposed_corner()
Corner find_opposed_corner (Corner c)
 {
   switch(c)
   {
   case Corner::TOP_LEFT:
     return Corner::BOTTOM_RIGHT;
   case Corner::TOP_RIGHT:
     return Corner::BOTTOM_LEFT;
   case Corner::BOTTOM_LEFT:
     return Corner::TOP_RIGHT;
   case Corner::BOTTOM_RIGHT:
     return Corner::TOP_LEFT;
   }
   defect();
 }
Referenced by TweakSelection::tweakSelection().
on_newWindow_activate()
static void on_newWindow_activate (GtkMenuItem * , gpointer user_data) static
 {
   PresentationInterface::WeakPtr const& wp = *static_cast<PresentationInterface::WeakPtr*>(user_data); // Yuk!
   PresentationInterface::Ptr const      p  = wp.lock();
   if(p)
   {
     find_or_create_scroom(p);
   }
 }
Referenced by View::updateNewWindowMenu().
tool_button_toggled()
static void tool_button_toggled (GtkToggleButton * button, gpointer data) static
 { static_cast<View*>(data)->toolButtonToggled(button); }
Referenced by View::addToolButton().
toRectangle()
Scroom::Utils::Rectangle<double> toRectangle (Selection s)
 { return Scroom::Utils::make_rect_from_start_end(s.start, s.end); }
Referenced by TweakSelection::tweakSelection().
Variable Documentation
MaxZoom
const int MaxZoom = 5 static
Referenced by View::on_scrollwheel(), and View::updateZoom().
zoomfactor
const std::array<const char*, 36> zoomfactor static
Initial value:
= {
  "32:1",          "16:1",          "8:1",           "4:1",         "2:1",         "1:1",          "1:2",          "1:4",
  "1:8",           "1:16",          "1:32",          "1:64",        "1:128",       "1:250",        "1:500",        "1:1000",
  "1:2000",        "1:4000",        "1:8000",        "1:16000",     "1:32000",     "1:64000",      "1:128000",     "1:250000",
  "1:500000",      "1:1 million",   "1:2 million",   "1:4 million", "1:8 million", "1:16 million", "1:32 million", "1:64 million",
  "1:128 million", "1:250 million", "1:500 million", "1:1 billion",
}
Referenced by View::updateZoom().