if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/.git")
  git_describe(GIT_PROJECT_VERSION)

  file(
    GENERATE
    OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/.scroom-version
    CONTENT "${GIT_PROJECT_VERSION}")
else()
  file(READ ${CMAKE_CURRENT_SOURCE_DIR}/.scroom-version GIT_PROJECT_VERSION)
endif()

file(
  GENERATE
  OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/inc/version.h
  CONTENT "#define PACKAGE_VERSION \"${GIT_PROJECT_VERSION}\"")
