name: Generate documentation

on: [ push, pull_request ]

jobs:
  generate-documentation:
    runs-on: ubuntu-20.04
    concurrency: generate-gh-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout docs
        run: git worktree add -b gh-pages ../doc origin/gh-pages

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Update apt package repos
        run: >
          sudo apt-get update

      - name: Install apt packages
        run: >
          sudo apt-get -yq --no-install-suggests --no-install-recommends install
          libboost-dev
          libboost-filesystem-dev
          libboost-program-options-dev
          libboost-system-dev
          libboost-test-dev
          libboost-thread-dev
          libcairo2-dev
          libglib2.0-dev
          libgtest-dev
          libgtk-3-dev
          libtiff5-dev
          pkg-config
          doxygen
          graphviz
          plantuml

      - name: Install python packages
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --no-warn-script-location sphinx sphinxcontrib-plantuml sphinxcontrib-doxylink

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DENABLE_DOXYGEN=TRUE

      - name: Doxygen
        working-directory: ${{runner.workspace}}
        run: cmake --build build --target doxygen-docs

      - name: Add doxygen to Sphinx
        working-directory: ${{runner.workspace}}/build
        run: |
          mv html ${GITHUB_WORKSPACE}/doc/_static/doxygen

      - name: Sphinx
        working-directory: ${{runner.workspace}}/scroom/doc
        run: |
          make

      - name: Upload to Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: build_scripts/github/upload_doxygen_to_github ${{runner.workspace}}
